### ISSUE TITLE
Reaffirm original Submitting organizations, add new

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#100]
The original "Submitting organizations" for GeoSPARQL were:

a) Australian Bureau of Meteorology
b) Bentley Systems, Inc.
c) CSIRO
d) Defence Geospatial Information Working Group (DGIWG)
e) GeoConnections - Natural Resources Canada
f) Interactive Instruments GmbH
g) Oracle America
h) Ordnance Survey
i) Raytheon Company
j) Traverse Technologies, Inc.
k) US Geological Survey (USGS)

These are not necessarily the same as implementers.

We need to reaffirm their interest/connection to GeoSAPRQL.

Here is my best guess for contacts:

**Organization** | **Person**
--- | ---
Australian Bureau of Meteorology | ?
Bentley Systems, Inc. | ?
CSIRO | @dr-shorthair 
DGIWG | ?
GeoConnections - Natural Resources Canada | Ryan Ahola
Interactive Instruments GmbH | ?
Mainz University Of Applied Sciences | @situx 
Oracle America | @mperry455 
Ordnance Survey | ?
Raytheon Company | ?
Traverse Technologies, Inc. | ? - ask Josh Lieberman
US Geological Survey (USGS) | ? Dalia

* please suggest contact people in comments

New submitting orgs could be:

l) SURROUND Australia Pty Ltd.
m) Mainz University Of Applied Sciences
n) Geoscape Australia
o) Geonovum
p) ...

* please suggest new submitters

**Comment by dvaranka** [comment]
I am not sure how to reply to the message below, as I am an observer of the discussion.
At the USGS, we tested triplestores supporting GeoSPARQL but ended up writing our own GeoSPARQL support software due to storage needs and to determine relations between polygons and lines. I was/am the primary contact person at the USGS.

________________________________

**Comment by nicholascar** [comment]
Thanks @dvaranka, you being in contact like this is just fine. Shortly we'll have a first full draft of GeoSPARQL 1.1 ready for external review. At that point we'll contact original supporter organizations via their contact people, such as yourself, to ensure you're all aware of the new version and supply any feedback.

We are contacting GeoSPARQL implementers separately (see Issue #59) and we will tabulate implementations of 1.0 and 1.1 soon too. It sounds as though USGS is a unilateral GeoSPARQL implementer though! Can you supply any more info on your "own GeoSPARQL support software"? Is it available? If not, can you at least describe the implementation for our implementations table?

**Comment by jabhay** [comment]
@ogcscotts : what is the usual process that OGC goes through wrt original Submitting Organisations when a standard is updated? Should we be reaching out to contacts within the organisations to see if they want to remain SOs or removed from the list?

**Comment by nicholascar** [comment]
This list should appear for 1.1 _below_ the list for 1.0 which should be retained.
