### ISSUE TITLE
Spatial Agg Funcs duplicative of existing

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#101]
The new _Spatial Aggregate Functions_ are:

* geosaf:BBOX
* geosaf:BoundingCircle
* geosaf:Centroid
* geosaf:ConcatLines
* geosaf:ConcaveHull
* geosaf:ConvexHull
* geosaf:Union

Existing _Non-topological Query Functions_ from 1.0 are:

* geof:distance
* geof:buffer
* geof:convexHull
* geof:intersection
* geof:union
* geof:difference
* geof:symDifference
* geof:envelope
* geof:boundary
* geof:getSRID

1. We have the following duplicates:
    * geosaf:BBOX == geof:envelope
    * geosaf:Union == geof:union
    * geosaf:ConvexHull == geof:convexHull
2. We have introduced a new namespace, `geoaf` when the previous ones used `geof`
3. We have used leading capitals when the previous ones use leading lowercase

Proposal:
* Remove _Spatial Aggregate Functions_ section
* Add missing functions to existing _Non-topological Query Functions_
* Use lower-case letter for function names

So the result will be the following additions to _Non-topological Query Functions_:

1. geosf:boundingCircle
2. geosf:centroid
3. geosf:concatLines
4. geosf:concaveHull

**Comment by nicholascar** [comment]
@situx oops, we should have picked these all up at review time... Do you agree with the proposals above? If not, can you suggest alternates?

**Comment by situx** [comment]
I was aware of these functions, but it was my understanding that we need to define new function signatures in order to state that those can act as spatial aggregate functions. I was not aware that it was simply sufficient to define new non-topological query functions.
Can all defined SPARQL extension functions listed there be used in a SELECT statement, so that we do not need those definitions then or do we need to modify the definitions to state that those may also be used as spatial aggregate functions?

**Comment by nicholascar** [comment]
> it was my understanding that we need to define new function signatures in order to state that those can act as spatial aggregate functions

Sorry, I clearly didn't follow all the thoughts around this - I was doing other PRs...

I think it's confusing having multiple, similar things so I still think we should de-duplicate.

> Can all defined SPARQL extension functions listed there be used in a SELECT statement, so that we do not need those definitions then or do we need to modify the definitions to state that those may also be used as spatial aggregate functions?

Can you supply an example of `geosaf:Union` use in SPARQL v. `geof:union`?

* this may clear things up - i.e. why we need two
* whether we keep or de-duplicate, the examples will be worth putting in the Spec

**Comment by situx** [comment]
geof:union (geom1: ogc:geomLiteral, geom2: ogc:geomLiteral,): ogc:geomLiteral
takes two geometry literals and returns the union of the two as a new literal.
geosaf:Union takes a geometry variable and returns the union of all of them (unary union)
SELECT (geosaf:Union(?geo) AS  ?union) WHERE {
  ?abc geo:hasGeometry ?geom .
  ?geom geo:asWKT ?geo .
}

**Comment by nicholascar** [comment]
So, to contrast with your SPARQL above, a SPARQL call to `geof:union` would look like this:

```sparql
# gets the union of the geometries of Features f1 & f2
SELECT ?u
WHERE {
    ?f1 geohasGeometry/geo:asWKT ?g_lit1 .
    ?f2 geohasGeometry/geo:asWKT ?g_lit2 .

    BIND (geof:union(?g_lit1, $g_lit2) AS ?u)
}
```

Then `geosaf:Union` operates pairwise on each pair of geometry literals discovered by the `WHERE` clause in the SPARQL query. So geosaf:Union` could be seen to operate using `geof:union` under-the-hood!

**Comment by situx** [comment]
Correct, your query would substitute the union function. You could say that the Spatial Aggregate Union Function would be syntactic sugar for the BIND statement you just wrote.

For the geof:envelope and the geof:convexHull function the parameters would be the same, so probably we could just declare the envelope function as a spatial aggregate function as you proposed?
