### ISSUE TITLE
rename SpatialMeasure?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#103]
[PR 72](https://github.com/opengeospatial/ogc-geosparql/pull/72) introduced the term `SpatialMeasure`. I wonder if that is the best name for the concept. Firstly, the adjective "Spatial" should generally not be needed because the ontology is about spatial things. Secondly, we can not be certain that GeoSPARQL will never include semantics for Linear Referencing (LR). In LR, "measure" is an important term with an established meaning. So having two different kinds of measures could be confusing.
The overarching intent of the concept is to get an idea of the size of something, right? So how about "size" as a new name? Or perhaps "magnitude"?

**Comment by dr-shorthair** [comment]
@FransKnibbe I was responsible for introducing it in the GEOX extensions we have been experimenting with at CSIRO. 
Yes, it is primarily just a scaled quantity (i.e. number with a unit of measurement). 
The 'spatial' part was to allow for the fact that some quantities are affected by the CRS in use. 
I don't understand your argument about linear referencing - that is still a spatial reference system after all. 

Nevertheless, I'd be comfortable with simplifying this concept. In fact - as I noted over in https://github.com/opengeospatial/ogc-geosparql/issues/83#issuecomment-780944827 it would probably be better implemented as a datatype. The `cdt:ucum` datatype implemented by Antoine Zimmerman and Maxime Lefrancois is nicely specified, though I'd like to see it moved into a more standard namespace.

**Comment by FransKnibbe** [comment]
> @FransKnibbe I was responsible for introducing it in the GEOX extensions we have been experimenting with at CSIRO.
> Yes, it is primarily just a scaled quantity (i.e. number with a unit of measurement).
> The 'spatial' part was to allow for the fact that some quantities are affected by the CRS in use.
How do you mean that exactly? In the sense that distance can be measured in a plane or on a spherical surface?
If some quantities are differently affected by the CRS, perhaps it would be good to elaborate on that in the descriptions.

I hope there is a chance we can do without a unit of measurement altogether (and always use the unit of the CRS), but I raised that point already in [issue 98](98).

> I don't understand your argument about linear referencing - that is still a spatial reference system after all.

Well, in most linear referencing systems (at least ESRI, Oracle and PostGIS; I cannot access the OGC LRS document because it is behind a paywall). measure is an important term, and I think it is used there with a different meaning.  Measures can be used to model mile markers on a road for instance. At the moment GeoSPARQL does not include capabilities for linear referencing, but such an addition can not be ruled out. In that case, a naming conflict would arise. 
I am not a native English speaker, but to me a name like "size" would make the intended meaning of the term more clear. For verification: `hasRadius` could also be  a subproperty of `SpatialMeasure` to indicate the size of circular or spherical things, right?

> Nevertheless, I'd be comfortable with simplifying this concept. In fact - as I noted over in [#83 (comment)](https://github.com/opengeospatial/ogc-geosparql/issues/83#issuecomment-780944827) it would probably be better implemented as a datatype. The `cdt:ucum` datatype implemented by Antoine Zimmerman and Maxime Lefrancois is nicely specified, though I'd like to see it moved into a more standard namespace.

(Hey, it's possible to link to a GitHub comment! That's nice.)

At the risk of crossing discussion beams — yes, I think it would be better for `SpatialMeasure` to be a datatype property. I haven't read the paper on cdt:ucum yet, but I will. Still, wouldn't it be even simpler if we can omit the unit altogether ([also see this comment](https://github.com/opengeospatial/ogc-geosparql/issues/99#issuecomment-793030777))?

**Comment by nicholascar** [comment]
@FransKnibbe prefers `SpatialSize`

**Comment by nicholascar** [comment]
@FransKnibbe please put in a PR to change this.
