### ISSUE TITLE
Should transformations between geometry literals (serialisations) be supported?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#111]
A question that arose at the 2021-03-10 teleconference: Should GeoSPARQL include functions to enable transformations between geometry literals? For example: transform a WKT literal to a GML literal.

See also [pull request 108](https://github.com/opengeospatial/ogc-geosparql/pull/108).

**Comment by situx** [comment]
This has already been added to GeoSPARQL 1.1 so I will close this issue
