### ISSUE TITLE
Min/Max functions need to be added to list in parent (8.10)

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#115]
The functions are defined in the spec, see e.g. [8.10.13. Function: geof:maxZ](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofmaxz) but they are not listed in the parent section, see [8.10. Non-topological Query Functions](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_non_topological_query_functions) and **Requirement 31**.

**Comment by situx** [comment]
Thanks, nick, it was on my todo list anyway for my pull request #109 
I added them now

**Comment by dr-shorthair** [comment]
Note that #117 adds `sf:Envelope` which has properties `sf:minimum` and `sf:maximum` which might be related? Not sure, but did want to ensure that we keep our terminology aligned.

**Comment by situx** [comment]
@dr-shorthair This issue is about adding functions that return the minimum and maximum X, Y, Z coordinates of geometries, so we are not talking about properties here. There should not be any issues I think.

**Comment by dr-shorthair** [comment]
Yes, understood. I just wanted all to keep track of the parallel work on properties.
