### ISSUE TITLE
1.1. New Feature implementations

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#116]
This issue will soon list a schedule of the _New Features_ present in GeoSPARQL 1.1 compared with GeoSPARQL 1.0 and will list implementations of them.

This table will be established in line with the _NEw Features_ schedule listing about to be added to the specification document as per Issue #114.

**New Feature** | **Reference** | **Implementations**
--- | --- | --- 
_New Profile Elements_ | [the profile](https://opengeospatial.github.io/ogc-geosparql/geosparql11/profile.html) | 
Profile | [the profile](https://opengeospatial.github.io/ogc-geosparql/geosparql11/profile.html) | - 
GeoSPARQL Rules in RIF | [RIF doc](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/rules.rifps) | -
Validation Resource | [SHACL doc](https://github.com/opengeospatial/ogc-geosparql/master/1.1/validation.ttl) | -
Spatial Measure class | [Spec 6.2.2](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geospatialmeasure) | -
_Feature Properties_ | [Spec 8.3](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_standard_properties_for_geofeature) | 
`hasBoundingBox` | [Spec 8.3.3](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geohasboundingbox) | -
`hasCentroid` | [Spec 8.3.4](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geohascentroid) | -
`hasLength` | [Spec 8.3.5](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geohaslength) | -
`hasArea` | [Spec 8.3.6](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geohasarea) | -
`hasVolume` | [Spec 8.3.7](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geohasvolume) | -
_Geometry Properties_ | [Spec 8.4](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_standard_properties_for_geogeometry) | 
`inSRS` | [Spec 8.4.8](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geoinsrs) | -
_Geometry Serializations_ | [Spec 8.5](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_geometry_extension_serialization_version) | 
`asWKT` function | Spec 8.5.x.x | -
`asGML` function | Spec 8.5.x.x | -
`geoJSONLiteral` | [Spec 8.7.1](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_rdfs_datatype_geogeojsonliteral) | -
`asGeoJSON` | [Spec 8.7.2](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geoasgeojson) | -
`asGeoJSON` function | Spec 8.5.x.x | -
`kmlLiteral` | [Spec 8.8.1](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_rdfs_datatype_geokmlliteral) | - 
`asKML` | [Spec 8.8.2](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geoaskml) | - 
`asKML` function | Spec 8.5.x.x | -
`dggsWktLiteral` | [Spec 8.9.1](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_rdfs_datatype_geodggswktliteral) | -
`asDggsWkt` | [Spec 8.9.2](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geoasdggswkt) | - 
`asDggsWkt` function | Spec 8.5.x.x | -
_Non-topological Query Functions_ | [Spec 8.10](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_non_topological_query_functions) | 
`maxX` | [Spec 8.10.11](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofmaxx) | - 
`maxY` | [Spec 8.10.12](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofmaxy) | - 
`maxZ` | [Spec 8.10.13](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofmaxz) | - 
`minX` | [Spec 8.10.14](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofminx) | - 
`minY` | [Spec 8.10.15](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofminy) | - 
`minZ` | [Spec 8.10.16](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofminz) | - 
_Spatial Aggregate Functions_ | [Spec 8.11](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_spatial_aggregate_functions) | 
`BBOX` | [Spec 8.11.1](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geosafbbox) | - 
`BoundingCircle` | [Spec 8.11.2](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geosafboundingcircle) | - 
`Centroid` | [Spec 8.11.3](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geosafcentroid) | - 
`ConcatLines` | [Spec 8.11.4](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geosafconcatlines) | - 
`ConcaveHull` | [Spec 8.11.5](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geosafconcavehull) | - 
`ConvexHull` | [Spec 8.11.6](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geosafunion) | - 
`Union` | [Spec 8.11.7]() | -

**Comment by mathib** [comment]
SRS stuff (terminology and functions) should be added, or is this still pending?

**Comment by nicholascar** [comment]
> SRS stuff (terminology and functions) should be added, or is this still pending?

Just havn't got to adding it yet. Will try now!

**Comment by nicholascar** [comment]
New Feature lists long since in the Specification so closing
