### ISSUE TITLE
Add geometry representation for BoundingBox or Envelope

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#118]
A simple representation for a bounding-box or envelope is required to support the `hasBoundingBox` property. 
Two mandatory properties `lowerLeft` and `upperRight`, or `minimum` and `maximum` each of which has range `Point`. 

Suggest adding this to the SF Geometries.

**Comment by dr-shorthair** [comment]
However, is BoundingBox in the Simple Features specification?

**Comment by dr-shorthair** [comment]
Yes it is, though it is called 'Envelope' and the corners are referred to as 'minimums' and 'maximums'. Is that clearer than 'lowerLeft' and 'upperRight'?

**Comment by FransKnibbe** [comment]
Yes, minimum and maximum are clearer. What is up or down is not always clear, for instance in 3D geometry and non-earth SRSs.

**Comment by dr-shorthair** [comment]
It is also a little unclear whether the Envelope is considered to strictly be a Geometry in its own right. It does not fit into the usual hierarchy of geometries which is organized by topological dimension, while Envelope has arbitrary dimensionality.

**Comment by dr-shorthair** [comment]
Added in #117

**Comment by nicholascar** [comment]
Closing since proponent - @dr-shorthair - has had his PR for this - #117 - merged.
