### ISSUE TITLE
Capitalisation of abbreviations in ontology terms

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#119]
There are inconsistencies in capitalisation of abbreviations, in both GeoSPARQL 1.0 and 1.1. Examples:
1.0: `asWKT`, `asGML` vs. `rcc8dc`, `sfEquals`
1.1:  `asGeoJSON`   vs. `asDggsWkt`

Do we want to establish a guideline? If so, what should it be?

Considerations:

1. IRIs are case sensitive (see **_IRI equality_** in https://www.w3.org/TR/rdf11-concepts/#section-IRIs), so changing the case of letters in 1.0 IRIs could break things.
2. I could not find a general guideline on capitalisation of abbreviations in RDF IRIs.

**Comment by nicholascar** [comment]
I don't think we can change any of the 1.0 IRIs - we've promised not to break anything - so they stay.

For 1.1: I've changed my addition of `asDggsWkt` to `asDGGSWKT` (in PR #106) as this seems to better align with the capitalised acronyms.

I think our guidance should be something like:

_use CamelCase for concatenated words, except for acronyms which should be capitalized. Upper CamelCase (starting capital) for class names, and lower camelCase (starting lowercase) for properties & functions. Properties & functions starting with an acronym should have the starting acronym in lower case_

So, ` asGeoJSON` fits that, as does the changed `asDGGSWKT`. `dggsWktLiteral` is ok IFF we buy the final sentence...

Clearly I've made up that guidance to retrofit the spec as it is now (after my change mentioned above).

Are there any alternate suggestions to the guidance?

**Comment by nicholascar** [comment]
Several of the DGGS properties have been removed, so now we only have `asDGGS` and `dggsLiteral`.

We still have inconsistencies from 1.0 but we still can't change those. I think this issue is solved, as best it can be, for 1.1 so I'm bumping it over to 1.2.

**Comment by jabhay** [comment]
Closing this as either consistent or a breaking change given the comments above.
