### ISSUE TITLE
Modularisation

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#120]
With each new version of GeoSPARQL, some thought must be given to modularisation. Modularisation is used in GeoSPARQL 1.0. An excerpt from the introduction:

> The GeoSPARQL standard follows a modular design; it comprises several different components.
> 􀀀 A core component [...]
> 􀀀 A topology vocabulary component [...]
> 􀀀 A geometry component [...]
> 􀀀 A geometry topology component [...]
> 􀀀 An RDFS entailment component [...]
> 􀀀 A query rewrite component [...]
> Each of the components described above forms a requirements class for GeoSPARQL. Implementations can provide various levels of functionality by choosing which requirements classes to support.

So the main purpose of modularisation is to allow implementers to state that they support e.g. modules A, C and D.

There are dependencies between modules:

- Geometry and Topology Vocabulary extension require Core
- Geometry Topology Extension requires Geometry and Topology Vocabulary extension
- Query Rewrite Extension and RDFS Entailement Extension require Geometry Topology Extension 

Three questions:
1) It seems sensible to make the modules explicit in the ontology or in the profile. What is the best way to do that?
2) For all additions in the next version (1.1 at this moment), is it clear to which module they belong? 
3) Is there a reason to create new modules in the next version (1.1 at this moment)?

**Comment by FransKnibbe** [comment]
Some further questions . . . 

GeoSPARQL modules are defined by requirements classes and corresponding conformance classes (as per the 1.0 spec). As far as I can tell, _requirements class_ is another word for module: a set of functionalities that software has to support in order to be able to claim support of a certain module. And _conformance class_ is, well, another word for module too (as far as I can tell). So my first question is: can anyone explain the difference between _requirements class_ and _conformance class_? I think we need to explain it to the readers too. Both terms are used in the specification.

Secondly, requirements classes and conformance classes each have IRIs. That is nice, because dereferencing them could shed some light on the difference between the two. For example, the IRI of the Core conformance class is http://www.opengis.net/spec/geosparql/1.0/conf/core and the IRI of the Core requirements class is http://www.opengis.net/spec/geosparql/1.0/req/core. Both IRI's lead me to an OGC portal login prompt. I cannot access the portal because I am not a member. Probably that needs to change, because I don't think we want data describing modules kept secret. Meanwhile, could someone check to what the IRIs resolve at the moment?

**Comment by situx** [comment]
Hi @FransKnibbe I can give you my take on this.

1. URIs of conformance classes and requirements are not dereferenceable. That is correct. Recently a pull request of mine was merged with the RDF vocabulary for requirements and conformance classes, so we can expect the OGC Naming Authority to make these resolvable in the submission process.
2. As to the differences between modules, requirements, and conformance classes:
- Requirement: A statement of functionality that is required in order to fulfill a part of the standard
- Conformance class: A statement on how to test a requirement's conformance to the standard description. For example We based our GeoSPARQL compliance benchmark queries on the description in the abstract test suite in GeoSPARQL 1.0 annex A to test requirements
- Modules: A collection of requirements (which are linked to conformance classes) that group requirements of a similar nature. For example: Requirements grouped in the RDFS Extension deal with issues concerning RDFS support in GeoSPARQL

**Comment by FransKnibbe** [comment]
As for any changes to modularisation in 1.1, I would like to offer a few proposals, based on the following assumptions:

(by the way, I am using ''requirements class" to refer to conformance classes too because at the moment I can't tell them apart)

1. The general idea of 1.1 is to extend 1.0 and not break existing implementations.
2. Assumption:  requirements classes have IRIs that resolve to data that specify which individual requirements they consist of.
3. Assumption: Individual requirements have IRIs.
4. IRIs of requirements and requirements classes can have a 1.0 or 1.1 base (i.e. http://www.opengis.net/spec/geosparql/1.0/ or http://www.opengis.net/spec/geosparql/1.0/). 

With the assumptions above, here are some proposals:

1. GeoSPARQL 1.1 should keep 1.0 modularisation intact as much as possible.
2. Requirements classes that are extended with extra requirements in 1.1 should get 1.1 IRIs, to tell them apart from their 1.0 counterparts. That means that implementations can indicate support of a 1.0 module, a 1.1 module, or both.
3. Assuming [PR 136](https://github.com/opengeospatial/ogc-geosparql/pull/136) will get through, there should be a new requirements class for DGGS.
4. Other extensions that have been made in 1.1 are not so groundbreaking to warrant additional modules. For example, adding support for GeoJSON is considered feasible for implementations that already support the Geometry extension. 

Please share your thoughts!

**Comment by situx** [comment]
For now, what you describe follows what I have modeled here (which also already includes the DGGS class)
https://opengeospatial.github.io/ogc-geosparql/geosparql11/reqs.html
- Each GeoSPARQL 1.0 requirement and conformance class gets a URI in the respective namespace
- Equivalent requirements (i.e. that do not change between 1.0 and 1.1) are connected by an owl:sameAs relation
- Requirements that have changed are connected with a prov:wasDerivedFrom relation
- Requirements that have been created in GeoSPARQL 1.1 are only present in the GeoSPARQL 1.1 namespace
Modules have not yet been modeled in this vocabulary and not for all relations the vocabulary is clear, but the OGC Naming authority might have some recommendations here.

**Comment by FransKnibbe** [comment]
Thanks @situx. You have not (explicitly) explained the difference between _conformance class_ and _requirements class_. But based on what you wrote and what I see in Annex A, I can come up with these definitions:

- requirements class: a set of requirements that must be met to claim support of a part of a specification (i.e. a module)
- conformance class: a set of requirements that must be met to claim support of a part of a specification (i.e. a module) and instructions on how to test each requirement

Would that be about right?

**Comment by FransKnibbe** [comment]
> For now, what you describe follows what I have modeled here (which also already includes the DGGS class)
> https://opengeospatial.github.io/ogc-geosparql/geosparql11/reqs.html
> 
> * Each GeoSPARQL 1.0 and each GeoSPARQL 1.1 requirement and conformance class gets a URI in the respective namespace
> * Equivalent requirements (i.e. that do not change between 1.0 and 1.1) are connected by an owl:sameAs relation

This is slightly different from my proposal. I proposed no 1.1 IRIs for requirements that haven't changed. But that is proposed under the assumption that it is possible to group 1.0 and 1.1 IRIs in a requirements class (which has its own resolvable IRI).
I presume some sort of mereologic relationship is needed for requirements and requirements classes.

By the way, I see no IRIs for conformance classes (e.g. http://www.opengis.net/spec/geosparql/1.0/conf/core) or requirements classes (e.g. http://www.opengis.net/spec/geosparql/1.0/req/core) in https://opengeospatial.github.io/ogc-geosparql/geosparql11/reqs.html

> * Requirements that have changed are connected with a prov:wasDerivedFrom relation
> * Requirements that have been created in GeoSPARQL 1.1 are only present in the GeoSPARQL 1.1 namespace
>   Modules have not yet been modeled in this vocabulary and not for all relations the vocabulary is clear, but the OGC Naming authority might have some recommendations here.

In my current understanding, adding requirements classes would model modules.

**Comment by situx** [comment]
> By the way, I see no IRIs for conformance classes (e.g., http://www.opengis.net/spec/geosparql/1.0/conf/core) or requirements classes (e.g., http://www.opengis.net/spec/geosparql/1.0/req/core) in https://opengeospatial.github.io/ogc-geosparql/geosparql11/reqs.html
Sorry, I cannot follow. There are only URIs of requirements and conformance classes in this vocabulary.
For example, for the feature class requirement:
1.0 URI: http://www.opengis.net/spec/geosparql/1.0/req/core/feature-class
1.1 URI: http://www.opengis.net/spec/geosparql/1.1/req/core/feature-class
Conformance class for the feature class requirement:
1.0 URI: http://www.opengis.net/spec/geosparql/1.0/conf/core/feature-class
1.1 URI: http://www.opengis.net/spec/geosparql/1.1/conf/core/feature-class

Modules could be modeled from my understanding by adding requirement classes to collections that we call modules.


The definition of requirements seems correct from my view.
The conformance class would, from my understanding, be only the definition of how to test the requirement.

**Comment by FransKnibbe** [comment]
> > By the way, I see no IRIs for conformance classes (e.g., http://www.opengis.net/spec/geosparql/1.0/conf/core) or requirements classes (e.g., http://www.opengis.net/spec/geosparql/1.0/req/core) in https://opengeospatial.github.io/ogc-geosparql/geosparql11/reqs.html
> 
> Sorry, I cannot follow. There are only URIs of requirements and conformance classes in this vocabulary.

I see IRIs of _conformance tests_ and _requirements_  in the vocabulary. So no IRIs of conformance classes (sets of conformance tests) and no IRIs of requirements classes (sets of requirements). The GeoSPARQL specfication does mention those IRIs. For example http://www.opengis.net/spec/geosparql/1.0/req/topology-vocab-extension is the IRI of the Topology Vocabulary Extension requirements class and http://www.opengis.net/spec/geosparql/1.0/conf/topology-vocab-extension is the IRI of the Topology Vocabulary Extension conformance class.

It looks like we are dealing with another cases of confusion caused by a lack of clear definitions. [Issue 175](https://github.com/opengeospatial/ogc-geosparql/issues/175) should remedy that.

**Comment by situx** [comment]
Yes, you are correct. These URIs are missing. I could create another pull request to amend those

**Comment by FransKnibbe** [comment]
> Yes, you are correct. These URIs are missing. I could create another pull request to amend those

OK. Since it is is a SKOS conceptscheme, I guess broader/narrower is the way to indicate group membership?
Also some way of indicating dependencies between requirements classes would be good, right?
And what about the idea of removing 1.1 IRIs of requirements and conformance tests that have not changed since 1.0? I think it would make things simpler.

**Comment by situx** [comment]
I agree with you regarding thinking about indicating dependencies between requirements classes.
I would add that we as the authors of the standard may also give priority to certain requirements classes,
Certainly, some requirements are more crucial than others to implement? Or maybe not?

As for the group membership, I am not sure why you would use broader/narrower relations there? I would just associate them to a collection.

As for removing the 1.1 IRIs, I am not sure if that is appropriate:
From my understanding, these IRIs are defined on a per spec level, so they are used relative to the URI used for hosting the spec. In the case of GeoSPARQL 1.1 this would be http://www.opengis.net/spec/geosparql/1.1/.....
Would it be appropriate to omit certain requirements which are actually defined in the GeoSPARQL 1.1 spec from this URI scheme?
I, as a user, would expect to find every requirement defined in GeoSPARQL 1.1 under http://www.opengis.net/spec/geosparql/1.1/req/.... for example
If it is common practice to not define new URIs for requirements that have not changed since the last spec version, I am ok. I just lack some guidance here.

**Comment by FransKnibbe** [comment]
> I agree with you regarding thinking about indicating dependencies between requirements classes.
> I would add that we as the authors of the standard may also give priority to certain requirements classes,
> Certainly, some requirements are more crucial than others to implement? Or maybe not?

To be clear, with dependencies I mean that in order to claim support of conformance class Geometry, conformance class Core must also be supported.

Yes, some requirements classes can be viewed as more important than others. But isn't it up to implementers to decide which modules they want to support? I think it is our job to group requirements into meaningful/workable modules (requirements classes). 

> As for the group membership, I am not sure why you would use broader/narrower relations there? I would just associate them to a collection.

That's OK.
 
> As for removing the 1.1 IRIs, I am not sure if that is appropriate:
> From my understanding, these IRIs are defined on a per spec level, so they are used relative to the URI used for hosting the spec. In the case of GeoSPARQL 1.1 this would be http://www.opengis.net/spec/geosparql/1.1/.....
> Would it be appropriate to omit certain requirements which are actually defined in the GeoSPARQL 1.1 spec from this URI scheme?
> I, as a user, would expect to find every requirement defined in GeoSPARQL 1.1 under http://www.opengis.net/spec/geosparql/1.1/req/.... for example
> If it is common practice to not define new URIs for requirements that have not changed since the last spec version, I am ok. I just lack some guidance here.

In my thinking, we do not need to copy resources that remain identical. It complicates matters. But if a requirements class has changed in 1.1 (for example because a requirement was added, deleted or changed) that requirements class would get a new 1.1 IRI. Its members could have 1.0 IRIs (if the requirement has not changed) or 1.1 IRIs (if the requirement is new) or both (if the requirement was changed). I don't think that amounts to omitting requirements. One could still look up all 1.1 requirements even if some have 1.0 IRIs.

**Comment by situx** [comment]
I created pull request #176 to model the conformance classes.
I have still kept the 1.1 URIs so that we can decide in the GeoSPARQL meeting call how to proceed there

**Comment by situx** [comment]
Conformance class definitions have been settled, closing here
