### ISSUE TITLE
Add examples of all New Features to Annex B

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#121]
For all New Features, as listed in #116, add examples of them to Annex B

Link to the the relevant Annex B addition from the New Features' defining section in the spec too.

**Comment by FransKnibbe** [comment]
I suggest to additionally create `skos:example` links in the ontology referring to the examples in Annex B (the HTML version), by giving the example an `id` attribute in the HTML code, and by using a fragment identifier in the object IRI of the `skos:example` triple. See also [issue 63](63).

I could make a PR for linking the 1.0 stuff to examples in Annex B?

**Comment by nicholascar** [comment]
> I suggest to additionally create `skos:example` links in the ontology referring to...

Good suggestion: a few examples these days have `skos:example` but we haven't put any in yet.

> I could make a PR for linking the 1.0 stuff to examples in Annex B?

Please do, that would be great! I will then follow suite for the 1.1 elements that I've added.

I think I might restructure Annex B from this:

* Annex B (informative) GeoSPARQL Examples
    * B.1 Example Data
    * B.2 Example Queries
    * B.3 Example Rule Application

to this:

* Annex B (informative) GeoSPARQL Examples
    * B.1 RDF examples
    * B.2 Example Queries & Rules
        * B.2.1 Example Data
        * B.2.2 Example Queries
        * B.2.3 Example Rule Application

At the moment, the example data is only there for the query and rule demonstrations, but we clearly need static examples of the ontology in use describing different things. So we add section _B.1 RDF examples_ for that and bundle the data for the queries and rules and the queries & rules themselves into _B.2 Example Queries & Rules_. Also, currently examples are numbered 1 - 5, but we will number all the RDF examples too, so these example numbers will start at some higher number.

**Comment by nicholascar** [comment]
I have made a start adding examples for all ontology elements, see branch [rdf-examples](https://github.com/opengeospatial/ogc-geosparql/tree/rdf-examples). You can see the rendered Spec HTML for that branch ehre:

* <https://raw.githack.com/opengeospatial/ogc-geosparql/rdf-examples/1.1/spec/rdf-egs.html>

**Comment by FransKnibbe** [comment]
@nicholascar: I have started (and verified that an id like `[[example10]]` in adoc results in a usable HTML anchor when converted by asciidoctor), but now that I am ready to add the SKOS examples to the 1.1 ontology I realise I'm not sure what the IRI of the HTML documentation is going to be (or the IRI of appendix B, if it is going to be a separate file). Do you happen to know for certain what is is going to be?
I guess it will be smart to use a `@prefix` for the root IRI of the HTML documentation ...

**Comment by nicholascar** [comment]
> I'm not sure what the IRI of the HTML documentation is going to be (or the IRI of appendix B, if it is going to be a separate file). Do you happen to know for certain what is is going to be?

The spec's IRI will be http://www.opengis.net/doc/IS/geosparql/1.1, as given on the front page of the Spec.

Looking at the way other Specs use their IRIs, it's not possible to yet tell what the IRI for parts within the Spec will be. For example, the persistent IRI of OGC API: Freatures is http://www.opengis.net/doc/IS/ogcapi-features-1/1.0 however, when resolved, the responding IRI is http://docs.opengeospatial.org/is/17-069r3/17-069r3.html, so its Annex B IRI is http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_revision_history. So at a guess, our Annex B IRI will be {RESPONDING_IRI} + "_annex_b_informative_geosparql_examples", so something like http://docs.opengeospatial.org/is/21-0xxry/21-0xxry.html#_annex_b_informative_geosparql_examples.

I think I will tidy up the top-level heading fragment identifiers in the doc so we have something like http://docs.opengeospatial.org/is/21-0xxry/21-0xxry.html#_annex_b but we still don't quite know what the IRIs will be.

> I guess it will be smart to use a @prefix for the root IRI of the HTML documentation ...

Yes do this for now and when we come to releasing the Spec, we can just put in the real IRI when we have it allocated from the Naming Authority.

**Comment by nicholascar** [comment]
See PR #122

**Comment by nicholascar** [comment]
Addressed in PR #122 and others.
