### ISSUE TITLE
Renumbering of requirements for GeoSPARQL 1.1?

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#126]
As discussed in #106 we have several requirements that could be grouped in the current specification:
For example:
There are three requirements for every literal type.
We could group them together as requirements 15.1, 15.2, 15.3 instead of using an ascending numbering scheme like in GeoSPARQL 1.0.
What are the best practices to follow from other OGC standards?
How can we align a new numbering system to be consistent with previous work done in GeoSPARQL 1.0?

**Comment by nicholascar** [comment]
> We could group them together as requirements 15.1, 15.2, 15.3 instead of using an ascending numbering scheme like in GeoSPARQL 1.0.

I agree with this: it would be easier to see repeated patters in the Requirements if they were grouped.

> What are the best practices to follow from other OGC standards?

Unfortunately OGC API: Features uses sequential numbering but it is broken own in parts A, B, C etc per number.

> How can we align a new numbering system to be consistent with previous work done in GeoSPARQL 1.0?

This I don’t know. If we are to be backwards-comparable we can’t change everything however the current system of sequential numbers prevents us from adding any new Requirements anywhere other than at the end!

We might just have to implement a new number system and then reference the old numbers in old/new number lookup table in an Annex.

**Comment by situx** [comment]
I think we can discuss this in the next meeting where we in any case wanted to go into a feature freeze, so that we are able to find out about a possible new future-proof numbering theme

**Comment by mperry455** [comment]
I definitely think the a new numbering system with grouped requirements is a good idea. The backwards compatibility part is tricky, but I like the idea of just having a table with the mapping to old requirement numbers somewhere.

**Comment by FransKnibbe** [comment]
I placed a [comment](https://github.com/opengeospatial/ogc-geosparql/pull/106#issuecomment-812913611) on this issue, probably in the wrong place. Long story short: Could putting the requirements in a SKOS concept scheme (and using IRIs to identify them) be a good idea?
