### ISSUE TITLE
hasDefaultGeometry exists as defaultGeometry

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#128]
[Issue 123](123) was about property `hasDefaultGeometry`, which is described in the documentation, being absent from the ontology. It was fixed with [PR 125](https://github.com/opengeospatial/ogc-geosparql/pull/125). But now I notice that the property was already in the ontology, albeit with another name: `defaultGeometry`. That means the 1.1 ontology now includes duplicates `defaultGeometry` and `hasDefaultGeometry`. Which one should remain?
For the sake of not breaking the 1.0 ontology it is probably best to remove `hasDefaultGeometry` from the ontology and change `hasDefaultGeometry` to `defaultGeometry` in the documentation.

Or we could leave both properties in the ontology and declare them equivalent (`owl:sameAs`) and include a `skos:note` explaining why there are two different URIs.

**Comment by FransKnibbe** [comment]
Actually, the problem was already made clear in [issue 30](https://github.com/opengeospatial/ogc-geosparql/issues/30).

**Comment by p1d1d1** [comment]
Will defaultGeometry still be available in 1.1? Just not to break existing implementations

**Comment by FransKnibbe** [comment]
> Will defaultGeometry still be available in 1.1? Just not to break existing implementations

I can imagne implementations being based on the ontology (using `defaultGeometry)` and other implementations being based on the documentation (using `hasDefaultGeometry`). So the safest would be to keep them both,
