### ISSUE TITLE
References to other ontology terms in annotation

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#133]
In the current ontology I see different ways of referring to other terms. Examples:
- `skos:definition """Exists if the subject SpatialObject spatially crosses the object SpatialObject. DE-9IM: T*T******"""@en ;` (the last part of the IRI ("SpatialObject") is used)
- `skos:definition """The default geometry to be used in spatial calculations, usually the most detailed geometry."""@en ;` (class name ("geometry") is not capitalised)

- `skos:definition """The spatial resolution of a Geometry."""@en ;` (skos:prefLabel ("Geometry") is used)

Adopting a guideline will improve clarity.  I suggest always using the `skos:prefLabel` (e.g. ¨Geometry¨, ¨Spatial Object¨). Any objections?
I haven´t checked the documention, but I think the same rule should apply there.

**Comment by situx** [comment]
In the documentation, I updated hopefully all references to ontology terms to be hyperlinked. In that way, it points to the original definition that is defined in the ontology.

**Comment by nicholascar** [comment]
This work is complete int he Spec, update the ontology
