### ISSUE TITLE
DGG versus DGGS

### ISSUE THREAD

**Issue by kjano** [opengeospatial/ogc-geosparql#137]
This is a tiny issue, but shouldn't this be either DGG or "A textual serialization of a Discrete Global Grid **System** (DGGS) geometry object."? IMHO, I would go with DGG in general.
Jano

dggsWktLiteral
	a rdfs:Datatype ;
	rdfs:isDefinedBy geosparql: , geosparql-spec: ;
	skos:definition """A textual serialization of a Discrete Global Grid (DGGS) geometry object."""@en ;
	skos:example """ "<https://w3id.org/dggs/auspix> OrdinateList (R3234)"^^<http://www.opengis.net/ont/geosparql#dggsWktLiteral>""" ;
	skos:prefLabel "DGGS Well-Known Text Literal"@en ;

**Comment by FransKnibbe** [comment]
@kjano: well spotted. Something needs to change.

The latest definitions I could find:

_DGG: set of cells at the same refinement level that uniquely and completely cover a globe.
DGGS: integrated system comprising a hierarchy  of discrete global grids , spatio-temporal referencing by zonal identifiers and functions for quantization  zonal query, and interoperability._

I take this to mean that a DGG geometry object would be limited to one refinement level.  From the discussion in [issue 112](https://github.com/opengeospatial/ogc-geosparql/issues/112#issuecomment-808856577) I have understood that refinement levels can be mixed for a single DGG(S) geometry. So if I have understood everything well enough, we should keep it at DGGS and insert "System" (I will do so now in [PR 136](https://github.com/opengeospatial/ogc-geosparql/pull/136)).

**Comment by jabhay** [comment]
This comment pertains to a property we've already changed.
