### ISSUE TITLE
Reword 'Exists if the subject SpatialObject [...]'

### ISSUE THREAD

**Issue by kjano** [opengeospatial/ogc-geosparql#138]
Another tiny suggestion. I would propose to rewrite sentences such as 'Exists if the subject SpatialObject' (as in "Exists if the subject SpatialObject spatially contains the object SpatialObject. DE-9IM: T*TFF*FF*") to 'Describes that the subject SpatialObject...] where 'describes' can also be 'states', 'specifies', or 'indicates'.  We can have S containing O without ever having a 'contains' relation between them in the graph.

**Comment by FransKnibbe** [comment]
A good clarification, I think. It seems an appropriate modification for [PR 134](https://github.com/opengeospatial/ogc-geosparql/pull/134), so I will make the change there.
