### ISSUE TITLE
Proposal: use metre for distance-based properties

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#142]
Distance-based properties are difficult because of the need to indicate units. This leads to complex expressions of simple numeric data. Moreover, there still are multiple competing ways of expressing units, and there are multiple competing ontologies for units and quantities. 
The problem could be solved by deferring to the distance unit specified in the CRS.  But that poses other difficulties: it requires a lookup, and at this moment we don't have a separate CRS property, nor an agreed-upon ontology or register for CRSs.

A very simple solution is to mimic [hasSpatialResolutionInMeters](https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_spatial_resolution)  as used in DCAT and keep the unit fixed to metre. After all, it is a widely used distance unit and part of the SI. Effectively, only two countries in the world don't use the metre as an official distance unit (source: [wikipedia](https://en.wikipedia.org/wiki/Metric_system#International_System_of_Units)).

This could lead to a set of simple, comparable and interoperable set of properties:

- hasMetricResolution 
- hasMetricAccuracy _(not in GeoSPARQL yet)_
- hasMetricLength
- hasMetricArea _(square metres)_
- hasMetricVolume _(cubic metres)_

 The datatype for metric properties could be `xsd:decimal` (no scientific notation allowed!)
 
 Among the benefits would be:

- Simpler and leaner data publication
- Simpler SPARQL queries
- Better interoperability between properties (e.g. combine resolution, size and accuracy in a single SPARQL query) within a dataset
- Better interoperability between different datasets
- Future proof: no dependencies on external ontologies and developments
- No need for external lookups when processing data
- Less need for numeric conversions in SPARQL queries
- Easier alignment with dataset metadata
- The principle is easy to extend to new properties

 This issue is related to [issue 23](https://github.com/opengeospatial/ogc-geosparql/issues/23
) (spatial accuracy and resolution), [issue 98](https://github.com/opengeospatial/ogc-geosparql/issues/98) (spatial resolution) and [issue 83](https://github.com/opengeospatial/ogc-geosparql/issues/83) (spatial measure).

**Comment by situx** [comment]
I currently wonder how to deal with historical GIS data. What if there is a distance unit we do not yet know how to convert into meters that is mentioned in a historic document?
What if we want to express an ancient unit in our graph because this is the only unit relevant for our target audience?
Is according to this proposal the data curator mandated to convert these measurements to meter for comparison or would we maybe provide options to also state measurements in other units?

**Comment by dr-shorthair** [comment]
The property `spatialResolutionInMeters` is defined in DCATv2 - 
https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_spatial_resolution i.e. it is from the core DCAT vocabulary, not just GeoDCAT-AP.

**Comment by FransKnibbe** [comment]
> The property `spatialResolutionInMeters` is defined in DCATv2 -
> https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_spatial_resolution i.e. it is from the core DCAT vocabulary, not just GeoDCAT-AP.

Thank you, @dr-shorthair. I have corrected the issue text.

**Comment by FransKnibbe** [comment]
> I currently wonder how to deal with historical GIS data. What if there is a distance unit we do not yet know how to convert into meters that is mentioned in a historic document?
> What if we want to express an ancient unit in our graph because this is the only unit relevant for our target audience?
> Is according to this proposal the data curator mandated to convert these measurements to meter for comparison or would we maybe provide options to also state measurements in other units?

It is good to keep the case of historical data in mind. If one does want to publish historical geographic data with an unknown distance (that could happen if georeferencing is not possible, I prresume), the first place to make clear that the distance unit is not known would be the CRS specification.
In all cases: if metric units do not suffice for expressing resolution and accuracy, it is always possible to use the more extensive methods for indicating  of the [Data Quality Vocabulary](https://www.w3.org/TR/vocab-dqv/#ExpressDatasetAccuracyPrecision).
That still leaves expressions of size (spatial measure) in ancient distance units of unknown length ([Yojana,](https://en.wikipedia.org/wiki/Yojana) for example). I think in such cases another vocabulary has to be used, because such units do not seem to be supported by current vocabularies for units anyway.

**Comment by nicholascar** [comment]
If the proposal is to add the metric units to the ontology while keeping the generic ones that require UoM and perhaps also indicating equivalence entailment then I support this. Then people can have the choice to use either but there's a way to convert. This will need a new conformance class for implementers supporting metric/non-metric conversions.

Please put in a PR @Frans!

**Comment by FransKnibbe** [comment]
@nicholascar, I have just put in that PR.

Although the PR does not replace the existing properties for spatial measure and resolution, I do wonder if there are irrefutable arguments against doing so. After all, the metre is an international standard unit for distance, and fixing the unit does away with a lot of complexity.

**Comment by FransKnibbe** [comment]
closed by P[R 155](https://github.com/opengeospatial/ogc-geosparql/pull/155).
