### ISSUE TITLE
crystal clear def of the "just geometry" part of geometry serialisations

### ISSUE THREAD

**Issue by mathib** [opengeospatial/ogc-geosparql#144]
Hi all, 

This is a new issue to track for the GeoSPARQL v1.1. release, considering that the content of geometry literals of the current geometry formats are a subpart ("just geometry") of what would be in a regular valid (non-RDF) file of that geometry format (KML, GML, WKT, DGGS, GeoJSON) containing a "just geometry" part and non-geometry content.

See the discussion in https://github.com/opengeospatial/ogc-geosparql/pull/122:
e.g. https://github.com/opengeospatial/ogc-geosparql/pull/122#issuecomment-830614792 and following

GeoSPARQL text specification: the examples and the accompanying text are clear for me in 8.4 per geometry literal

GeoSPARQL ontology (I looked at [this version](https://opengeospatial.github.io/ogc-geosparql/geosparql11/geo.ttl): 
- the `skos:definition` could still be extended a bit to indicate what a valid geometry literal is per geometry format (e.g. for `geo:gmlLiteral` the following line (copied from the GeoSPARQL text spec) should be added: "Valid geo:gmlLiteral instances are formed by encoding geometry information as a valid element from the GML schema that implements a subtype of GM_Object."
- of course the accompanying `skos:example` should also reflect this (I can't quickly check as these are not dereferenceable, probably still in process)

**Comment by situx** [comment]
Hi @mathib I think the examples for the literals should be in the #122  pull request of @nicholascar 
If you have suggestions on how to extend it you could create a pull request?

**Comment by jabhay** [comment]
Hi @mathib , we think this is adequately covered. Could you see if this is still relevant with respect to the 1.1 latest documents?
