### ISSUE TITLE
Base IRI declaration

### ISSUE THREAD

**Issue by neilotte** [opengeospatial/ogc-geosparql#147]
This is a request for a base IRI declaration in all OWL/RDF files. In turtle, this would appear as an @base declaration at the top of the files.

See also: https://www.w3.org/TR/turtle/#relative-iri

**Comment by nicholascar** [comment]
What advantage do you perceive with an `@base` declaration?

I know what they are but only tend to use them in Turtle files if I have multi-segments URIs in the file e.g.

```turtle
@base <https://example.com/>

<one-seg> a owl:Thing .

<two/segs> a owl:Thing .

<three/segs> a owl:Thing .
```

In GeoSPARQL as it is now, we don't have such URIs: the ontology uses hash URIs and there are no extended segments in it, so what's the advantage over just normal prefixing?

**Comment by neilotte** [comment]
@nicholascar  @paulc-dstl  Thanks for responding. The request to provide base URIs comes from the recommendation: "It is recommended that the base URI be defined using an xml:base attribute in the <rdf:RDF> element at the beginning of the document." https://www.w3.org/TR/owl-ref/#Header Although this is a recommendation for RDF/XML, I am assuming the same recommendation applies for Turtle. It is, of course, not required. 

Regarding my use case in particular: Unlike the editor Protege (which creates a catalog.xml file for managing local imports), the ontology editor TopBraid Composer uses the base URI not only for resolving relative URIs, but also for resolving file imports within a workspace (e.g. users will not be allowed to open two files with the same base URI within a workspace). Now, in the absence of a base URI, it will use the default namespace. However, using a declared base URI will allow imported ontologies to retain their namespace prefix declarations defined against this Base URI in the active ontology. ( see also https://www.topquadrant.com/docs/TBC_FeaturesOverview.pdf )

A related issue (which I can raise in a separate thread if easier to track) is that profile.ttl doesn't have a declared default namespace. In the turtles in this repository, there is a prefix declaration for the default namespace, but not for profile.ttl. 
Using either Protege or TopBraid, if one goes to create a file that imports all of GeoSPARQL's turtles, both editors default to using the local file path for profile.ttl (e.g. <file:///Users/yourcomputer/TBCFEWorkspace/gsfont/ogc-geosparql/1.0/profile.ttl>) as the default URI in the import statement. (To their credit, Protege does this with a little 'warning'. TopBraid, however, does not.) This issue could be fixed by just declaring a prefixed namespace for profile.ttl.

**Comment by paulc-dstl** [comment]
Sounds like a reasonable justification and use case. I have added base uri to all ttl files in #171 so if that pull request can be reviewed and merged back in, i think this can be closed. Thanks @neilotte @nicholascar :-)
