### ISSUE TITLE
Add geo:FeatureCollection

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#148]
to support OGC API  - as discussed with @nicholascar

**Comment by dr-shorthair** [comment]
Maybe also `SpatialObjectCollection` and `GeometryCollection` to match.

**Comment by dr-shorthair** [comment]
Is `rdfs:member` the best predicate?

**Comment by dr-shorthair** [comment]
What is relationship of `:GeometryCollection` and `sf:GeometryCollection`

**Comment by pvretano** [comment]
OGC API has the general concept of a collection and OGC API Features deals with feature collections.  As far as I know, however, there is nothing like a GeometryCollection.  I suppose, when the property selection extension is added to the OGC API Features set of specifications one could request just the geometry of the features and thus get a "geometry collection".  Just wanted to point that out ... generally though, I think this is a good addition to GeoSPARQL.  Might want to rename "SpatialObjectCollection" to "Geodata" or "GeodataCollection" to match OGC API Common ... hate that name but that is what common settled on.

**Comment by dr-shorthair** [comment]
I'd be OK changing "SpatialObjectCollection" to "GeodataCollection"

**Comment by situx** [comment]
I think SpatialObjectCollection would be better. A GeodataCollection restricts its contents to geospatial data, correct? A SpatialObjectCollection leaves the option to also include nongeo spatial objects

**Comment by nicholascar** [comment]
Agree with @situx. SO Collection matches the current classes and feedback seems to be that we should be more spatial and less geo, so let’s not add more geo that we one day have to unwind.

Surely there are some use cases for GeometryCollection? I use only multiple geometries linked to Features and have no Geometries with independent lives but Simon might have. So I only really care about FeatureCollection but am happy to support collections for all the current GeoSPARQL classes. SpatialMeasureCollection?

**Comment by situx** [comment]
By the way: How to we identify instances of these collections? Will there be a property ispartof collection or is a collection supposed to be an rdf list? Any thoughts?

**Comment by dr-shorthair** [comment]
`isPartOf` would be the inverse property to `rdfs:member`. 
However, it is generally recommended to avoid inverse properties, since the assertion can always be made the other way and still be part of the graph. 
This simplifies query patterns, and reduces risk of inconsistencies. 

Nevertheless, I did ask [the question as to whether using `rdfs:member` as the membership predicate for GeoSPARQL collections](https://github.com/opengeospatial/ogc-geosparql/issues/148#issuecomment-853386121) is the best option. No-one has yet commented on that.

**Comment by nicholascar** [comment]
> whether to use `rdfs:member`

Well what other options do we have? It's either that or something common line `dcterms:hasPart` which I use a lot. 

I think `rdfs:member` is best as it's the most fundamental membership property and doesn't lead to any tricky entailments, so minimal ontological commitment.

Since I have a lot of `dcterms:hasPart` instances, I suppose I'd better convert them to `rdfs:member` (I don't need an inverse)

**Comment by dr-shorthair** [comment]
I asked: 
> What is relationship of `geosparql:GeometryCollection` and `sf:GeometryCollection` 

I went back and checked and found 

`sf:Geometry rdfs:subClassOf geosparql:Geometry .`  

So I have proposed adding the same pattern for sf:GeometryCollection. 

`sf:GeometryCollection rdfs:subClassOf geosparql:GeometryCollection .`  

However, there is also this 

`sf:GeometryCollection rdfs:subClassOf sf:Geometry .`  

because ISO 19107 says that a geometry aggregate is itself still a geometry. 
So if we add the subclass axiom into sf_geometries, do we also need to reflect that sub-classing relationship at the abstract level in GeoSPARQL - i.e. 

`geosparql:GeometryCollection rdfs:subClassOf geosparql:Geometry .`  

??

**Comment by FransKnibbe** [comment]
I am not clear on why these collection need to be part of GeoSPARQL. Isn't it confusing to have these collection structures next to  more general (current and future) RDF collection structures?

Which particular use cases are helped?

**Comment by nicholascar** [comment]
> I am not clear on why these collections need to be part of GeoSPARQL.

It's certainly helpful to have easily identifiable collections of `Feature` instances as this greatly simplifies the organisation of data for things like OGC APIs that are reading from triplestore/RDF back-ends. OGC APIs and similar have `FeatureCollection` objects and this update basically matches that. Those APIs, and this update, allow for arbitrary collections of features, as opposed to ones linked by spatial logic.

However, I agree that it's entirely possible to use an `rdf:Bag`, `rdf:Sequence` or similar, generic, RDF collection object containing `Feature` instances to do this too.

In SSN/SOSA extension, there is [the `ObservationCollection` object](https://www.w3.org/TR/vocab-ssn-ext/#sosa:ObservationCollection) but we perhaps don't have that criteria it has of "...whose members share a common value for one or more property".

So, this one goes out to the group as a whole:

* do we recommend using standard RDF collection mechanics or do we define specialised classes like `geo:FeatureCollection`?

(I in part motivated these specailised collection additions but perhaps they really are unneeded? I see much appeal in re-using existing ontology elements)

**Comment by dr-shorthair** [comment]
> I am not clear on why these collections need to be part of GeoSPARQL. Isn't it confusing to have these collection structures next to more general (current and future) RDF collection structures?

You could ask the same question about the base classes, `geo:SpatialObject` `geo:Feature`. Why not just `owl:Thing`? 

I think we want specific collection classes because we want the type of the member items to be restricted.

**Comment by nicholascar** [comment]
> I think we want specific collection classes because we want the type of the member items to be restricted.

This does seem to be our only requirement of the *Collection classes. 

While a `rdf:Bag` with only `geo:Feature` instances in it is pretty similar to a `geo:FeatureCollection`, SHACL validation and SPARQL queries are harder to write against the generic versions.

`SpatialObjectCollection` is already linked to (subclass of) `rdfs:Container`.

@FransKnibbe are you happy with the justification here or do you recommend not including *Collection classes at all?

**Comment by dr-shorthair** [comment]
Useful classes are always defined in terms of the properties. 

The corollary is that I'm always suspicious of class hierarchies where some intermediate classes do not have any distinctive properties.

**Comment by FransKnibbe** [comment]
> @FransKnibbe are you happy with the justification here or do you recommend not including *Collection classes at all?

In general I see the benefits of being able to make statements about collections of geometries, features, etc. See also [issue 104](https://github.com/opengeospatial/ogc-geosparql/issues/104).
But with regard to using existing grouping features in RDF, couldn´t the same thing be achieved with void:classPartition (see https://www.w3.org/TR/void/#class-property-partitions)?

I see that in the case of GeometryCollection a unique restriction is mentioned in the current PR: all geometries are expected to have the same CRS. But something similar does not exist for collections of Features. And a collection of DGGS Objects is not defined at all. And why is it necessary to be able to group Geometries by CRS and not by e.g. dimesnionality? It feels a bit random now, so I would like to know more about the reasoning behind the design.

I think it would be good to add some documentation explaining the purpose of the collections, together with examples that show their usefulness.

**Comment by dvaranka** [comment]
We encountered the need for collection classes when we attempted to use GeoSPARQL with environmental data. In our case, these were mostly a single broad feature with discontinuous expressions. For example:

  *   outcroppings of soil polygons over a given area that were essentially the same soil profile, but disturbed/undisturbed, or had other discontinuity
  *   wetlands emerging from the same water table

I don't know if that is consistent with what's being modeled in v. 1.1, but we would take a look at it.
Dalia
________________________________
From: Frans Knibbe ***@***.***>
Sent: Tuesday, June 15, 2021 7:27 AM
To: opengeospatial/ogc-geosparql ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [opengeospatial/ogc-geosparql] Add geo:FeatureCollection (#148)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@FransKnibbe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFransKnibbe&data=04%7C01%7Cdvaranka%40usgs.gov%7Ca7d63fdf4dc64cab8a2c08d92ff90187%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637593568787135782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XgZUSvKMnbQy9nqH4cFVgne%2BZndEYhfpMq9Ers9zZfA%3D&reserved=0> are you happy with the justification here or do you recommend not including *Collection classes at all?

In general I see the benefits of being able to make statements about collections of geometries, features, etc. See also issue 104<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopengeospatial%2Fogc-geosparql%2Fissues%2F104&data=04%7C01%7Cdvaranka%40usgs.gov%7Ca7d63fdf4dc64cab8a2c08d92ff90187%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637593568787135782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fv2KzUcfmu1Yq0SyifIfVeIQq150wlHgEtmk24j9lqA%3D&reserved=0>.
But with regard to using existing grouping features in RDF, couldn´t the same thing be achieved with void:classPartition (see https://www.w3.org/TR/void/#class-property-partitions<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.w3.org%2FTR%2Fvoid%2F%23class-property-partitions&data=04%7C01%7Cdvaranka%40usgs.gov%7Ca7d63fdf4dc64cab8a2c08d92ff90187%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637593568787145737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PZU0I8mqGMiz4YnOT7%2Bjpl8Q0Qcfu8ppF98Xf4K21Ro%3D&reserved=0>)?

I see that in the case of GeometryCollection a unique restriction is mentioned in the current PR: all geometries are expected to have the same CRS. But something similar does not exist for collections of Features. And a collection of DGGS Objects is not defined at all. And why is it necessary to be able to group Geometries by CRS and not by e.g. dimesnionality? It feels a bit random now, so I would like to know more about the reasoning behind the design.

I think it would be good to add some documentation explaining the purpose of the collections, together with examples that show their usefulness.

**Comment by dr-shorthair** [comment]
> couldn´t the same thing be achieved with void:classPartition

Possibly. But introducing additional namespaces/vocabularies might confuse things. 
And VoID does not have the status of rdf, rdfs, owl, or skos. 
In fact it went offline for a couple of years and no-one noticed. 
So I'd be cautious about introducing a dependency on it. 

Overall, I think it is helpful to have the key functionality in the GeoSPARQL namespace. 
You might axiomatize the alignment with VoID, but not create an actual dependency.

**Comment by FransKnibbe** [comment]
I am all for having a way to define groups of instances of the same class (Features, Geometries, ...) and making statements about that such a group that carry over to individuals.  Hence [issue 104](https://github.com/opengeospatial/ogc-geosparql/issues/104). 

Probably it is useful to make a distinction between attaching metadata to a subset (e.g. versioning or authoring metadata) and stating that all individuals in the subset have the same value for certain properties. And probably GeoSPARQL does not have to provide for mechanisms to define subsets for metadata, because it is a very general task. (But for spatial data we do have to make sure that the GeoSPARQL ontology is aligned with metadata ontologies for spatial data that people are likely to use (e.g. GeoDCAT-AP)).

As for fixing property values for a set of individuals, I can't help thinking that the desire  to have this sort of data efficiency is not unique to spatial data. Surely there must be a more general way of doing this? Otherwise, wouldn't many other ontologies on different topics have similar constructs? On the other hand, [sosa:ObservationCollection](https://www.w3.org/TR/vocab-ssn-ext/#sosa:ObservationCollection), mentioned by Nick, seems to demonstrate that in the case of SOSA/SSN a more general approach could not be found. So why not mimic `sosa:ObservationCollection`?

In the case of  `sosa:ObservationCollection` I do wonder if the domain of the properties that can be set at the collection level shouldn't be extended to include the collection class. For instance, `sosa:ObservationCollection` can be used to set the property  [sosa:hasFeatureOfInterest](https://www.w3.org/TR/vocab-ssn/#SOSAhasFeatureOfInterest) for all members. But `sosa:ObservationCollection` is not in the domain of `sosa:hasFeatureOfInterest`.

Also, there could be a need to specify properties to groups of individuals where those properties do not come from GeoSPARQL itself, see the examples mentioned by @dvaranka. Can something that provides for those cases be thought of?

Another thing: RDF(S) distinguishes containers and collections. Shouldn't we make clear which kind we mean, and make it clear in the names (So use e.g. FeatureContainer instead of FeatureCollection)?

**Comment by nicholascar** [comment]
> probably GeoSPARQL does not have to provide for mechanisms to define subsets for metadata

Agree, defer this to VoID/DCAT etc. My Extended Example [demo dataset](https://github.com/opengeospatial/ogc-geosparql/blob/extended-examples/1.1/examples/demo-dataset.ttl) uses DCAT for packaging and metadata. Others could use VoID for other forms of summary stats/metadata.

> for spatial data we do have to make sure that the GeoSPARQL ontology is aligned with metadata ontologies for spatial data that people are likely to use 

Also agreed, hence the DCAT example! We might benefit from a VoID packaging example to communicate more RDF details and perhaps also a GeoDCAT example. Perhaps these could be added to the Extended Examples?

> why not mimic `sosa:ObservationCollection`?

I think we are close to doing this, aren't we? In projects I'm using ObservationCollection instances to group Observations and then entailing that any property associated with the collection holds for each Observation. I think that's what the Geometry/Feature Collection objects would do. i.e. whatever properties are assigned to the Collection hold for the members. So not just CRS buy anything, e.g. resolution, etc.

> I do wonder if the domain of the properties that can be set at the collection level shouldn't be extended to include the collection class

I think so.

> But `sosa:ObservationCollection` is not in the domain of `sosa:hasFeatureOfInterest`

Surely this is just because ObservationCollection was an addition to SOSA and this hasFeatureOfInterest was already locked down? I am using ObservationCollection instances for lots of Observation instances exactly for this case, for one FoI! Seemingly incorrectly...


> Also, there could be a need to specify properties to groups of individuals where those properties do not come from GeoSPARQL itself, see the examples mentioned by @dvaranka. Can something that provides for those cases be thought of?

Do we need to do anything about this in GeoSPARQL or just leave this up to wider RDF/OWL modelling? I.e. if someone want to say something about Geometries in a GeometryCollection, they can do the normal RDF/OWL thing and just attach properties to the GeometryCollection instance with the assumption being that they carry for all members?

Perhaps the above two points - SOSA equivalence and non-GeoSPARQL properties -  boil down to just statements about expectations that any Collection properties apply to all members? Might have to differentiate Collection-only properties (e.g. title) v. those pertaining to all members. The ObservationCollection says "Collection of observations, typically with one or more property shared by all of its members" but provides no axioms for applying the properties or mechanics to differentiate Collection-only properties. RDFS has the class `rdfs:ContainerMembershipProperty` that might play a role here.

> Another thing: RDF(S) distinguishes containers and collections. Shouldn't we make clear which kind we mean, and make it clear in the names (So use e.g. FeatureContainer instead of FeatureCollection)?

We should be clear but RDFS & RDF only have these:

* `rdfs:Container`
    * `rdf:Bag`
    * `rdf:Seq`
    * `rdf:Alt`

There is no mention of "collection" anywhere, so I don't think it's correct to say that "RDF(S) distinguishes containers and collections". DCTERMS has `Collection`, "An aggregation of resources." and that's about as general a grouping as I can find.

I prefer the Collection naming as that uses far more intuitive wording than RDF's Container ("The class of RDF containers.") and Bag etc. which tell you little. There are no entailment concerns with `rdfs:Container`, the 3 x RDF classes or `dcterms:Collection` so we are free to adopt any pattern and do what we want with it, without becoming encumbered.

**Comment by FransKnibbe** [comment]
> > why not mimic `sosa:ObservationCollection`?
> 
> I think we are close to doing this, aren't we?

Close, but not fully there. Part of the definition of `sosa:ObservationCollection` (see http://www.w3.org/ns/sosa/ObservationCollection) is a list of owl:Restrictions on the properties and their cardinality.

> > Also, there could be a need to specify properties to groups of individuals where those properties do not come from GeoSPARQL itself, see the examples mentioned by @dvaranka. Can something that provides for those cases be thought of?
> 
> Do we need to do anything about this in GeoSPARQL or just leave this up to wider RDF/OWL modelling? I.e. if someone want to say something about Geometries in a GeometryCollection, they can do the normal RDF/OWL thing and just attach properties to the GeometryCollection instance with the assumption being that they carry for all members?

I am not sure if that is allowed or intended for `sosa:ObservationCollection`. Its definition says "_An ObservationCollection has at least one member, and may have one of any of the other seven properties mentioned in restrictions_". Does this exclude adding an eighth or ninth property from some other vocabulary to the ObservationCollection?

> Perhaps the above two points - SOSA equivalence and non-GeoSPARQL properties - boil down to just statements about expectations that any Collection properties apply to all members? Might have to differentiate Collection-only properties (e.g. title) v. those pertaining to all members. The ObservationCollection says "Collection of observations, typically with one or more property shared by all of its members" but provides no axioms for applying the properties or mechanics to differentiate Collection-only properties. RDFS has the class `rdfs:ContainerMembershipProperty` that might play a role here.

I think the way  `sosa:ObservationCollection` is meant to work is that **only** the seven explicitly listed properties apply to all members. That would mean that other properties of an `sosa:ObservationCollection` would apply only to the `sosa:ObservationCollection` itself. Which would also mean that is not possible to have other properties besides the selected even apply to all members. Somehow the three different cases (selected properties applicable to members, other properties applicable to members and properties applicable to the collection) need to be regulated. But I am afraid my owl-fu is to weak for this sort of modelling.

> 
> > Another thing: RDF(S) distinguishes containers and collections. Shouldn't we make clear which kind we mean, and make it clear in the names (So use e.g. FeatureContainer instead of FeatureCollection)?
> 
> We should be clear but RDFS & RDF only have these:
> 
> * `rdfs:Container`
>   
>   * `rdf:Bag`
>   * `rdf:Seq`
>   * `rdf:Alt`
> 
> There is no mention of "collection" anywhere, other than in the RDFS Specification section 5.1 Container Classes and Properties which is non-normative which says "RDF containers are resources that are used to represent collections", so I don't think it's correct to say that "RDF(S) distinguishes containers and collections", only different types of containers (orderd/unordered `Seq` & `Bag` etc.). DCTERMS has Collection, "An aggregation of resources." and that's about as general a grouping as I can find.
> I prefer the Collection naming as that uses far more intuitive wording than RDF's Container ("The class of RDF containers.") and Bag etc. which tell you little. There are no entailment concerns with `rdfs:Container`, the 3 x RDF classes or `dcterms:Collection` so we are free to adopt any pattern and do what we want with it, without becoming encumbered.

Well, I was looking at the [RDFS specification](https://www.w3.org/TR/rdf-schema/) which has section 5.1 on containers and section 5.2 on collections (lists). It is true that both sections are non-normative, but I do notice that the terms are widely used in RDF literature. In our case it seems `rdf:Bag` is closest to what we want (and perhaps we should make that explicit), and definitely not `rdf:List`.  Using `rdfs:member` also points in the direction of a Container. For people coming from the GIS  domain the term "collection" will seem appropriate, but for people with an RDF background it could give the wrong idea. Using "container" would be clear for both types of people.

**Comment by dr-shorthair** [comment]
Note that I had 
```
:SpatialObjectCollection
	a owl:Class ;
	rdfs:subClassOf rdfs:Container . 
```
in my initial proposal :-)

**Comment by nicholascar** [comment]
> Does this exclude adding an eighth or ninth property from some other vocabulary to the ObservationCollection?

No of course not! OWL Open World Assumption here!

> I think the way sosa:ObservationCollection is meant to work is that only the seven explicitly listed properties apply to all members. That would mean that other properties of an sosa:ObservationCollection would apply only to the sosa:ObservationCollection itself. Which would also mean that is not possible to have other properties besides the selected even apply to all members. Somehow the three different cases (selected properties applicable to members, other properties applicable to members and properties applicable to the collection) need to be regulated. But I am afraid my owl-fu is to weak for this sort of modelling.

This is jut not fully fleshed out in that work, @dr-shorthair? SOSA has pretty weak semantics generally, e.g. all that `schema:domainIncludes` stuff...

> For people coming from the GIS domain the term "collection" will seem appropriate, but for people with an RDF background it could give the wrong idea. Using "container" would be clear for both types of people.

We might have to do some pref/alt label stuff here then, since "Feature Collection" is the OGC API correlate.

Is this helpful or does the scopeNote introduce too many difficulties, or not enough formality:

```turtle
:SpatialObjectContainer
  rdf:type owl:Class ;
  skos:prefLabel "Spatial Object Container"@en ;
  skos:altLabel "Spatial Object Collection"@en ;
  skos:definition "Un-ordered collection of spatial objects"@en ;
  skos:scopeNote "Use this container to group instances of SpatialObject. The container implied no implicit ordering so content may be ordered based on their individual properties. Datatype and object properties assigned to this container may be inferred to be assigned to each member of the container. Annotation properties are understood to be relevant to the container only."@en ;
  rdfs:subClassOf
      rdf:Bag , 
      [
          rdf:type owl:Restriction ;
          owl:allValuesFrom :SpatialObject ;
          owl:onProperty rdfs:member ;
      ] ;
.

:FeatureContainer
  rdf:type owl:Class ;
  skos:prefLabel "Feature Container"@en ;
  skos:altLabel "Feature Collection"@en ;
  skos:definition "Un-ordered collection of features"@en ;
  rdfs:subClassOf 
     :SpatialObjectCollection ;
     [
         rdf:type owl:Restriction ;
         owl:allValuesFrom :Feature ;
         owl:onProperty rdfs:member ;
    ] ;
.
```

**Comment by dr-shorthair** [comment]
The SOSA graph has very weak semantics, by design - https://github.com/w3c/sdw/blob/gh-pages/ssn/integrated/sosa.ttl 
Just domainIncludes/rangeIncludes hints. No domain/range _axioms_. 

The SSN graph adds a few components, and OWL and RDFS axioms - https://github.com/w3c/sdw/blob/gh-pages/ssn/integrated/ssn.ttl. I don't think any of the axiomatization is inconsistent with the use of the `sosa:Observation` properties such as `sosa:hasFeatureOfInterest` on a `sosa:ObservationCollection`.

**Comment by dr-shorthair** [comment]
Re Collection vs. Container - 
I'm not actually so sure that the RDF containers (Bag, List or Seq) are used much in practice. 
That is actually why [I queried if `rdfs:member` was the best predicate](https://github.com/opengeospatial/ogc-geosparql/issues/148#issuecomment-853386121) ...
OTOH 'Collection' is used right through GIS and Geospatial. 

And from an English language pov, a container does not include its contents, while a collection does ;-)

**Comment by nicholascar** [comment]
> I'm not actually so sure that the RDF containers (Bag, List or Seq) are used much in practice.
I've hardly ever used them. Usually I use more domain-specialised things... like `sosa:ObservationCollection`! I have also used `dcterms:Collection` for a generic collection.

I much prefer *Collection over *Container and I do think that the OGC _Feature Collection_ type terminology means this will be understood just fine by (web) GIS people, so I vote for my example above but with the pref/alt labels reversed, e.g.:

```turtle
:SpatialObjectCollection
  rdf:type owl:Class ;
  skos:prefLabel "Spatial Object Collection"@en ;
  skos:altLabel "Spatial Object Container"@en ;
  skos:definition "Un-ordered collection of spatial objects"@en ;
  skos:scopeNote "Use this container to group instances of SpatialObject. The container implied no implicit 
                 ordering so content may be ordered based on their individual properties. Datatype and object 
                 properties assigned to this container may be inferred to be assigned to each member of the 
                 container. Annotation properties are understood to be relevant to the container only."@en ;
  rdfs:subClassOf
      rdf:Bag , 
      [
          rdf:type owl:Restriction ;
          owl:allValuesFrom :SpatialObject ;
          owl:onProperty rdfs:member ;
      ] ;
.

:FeatureCollection
  rdf:type owl:Class ;
  skos:prefLabel "Feature Collection"@en ;
  skos:altLabel "Feature Container"@en ;
  skos:definition "Un-ordered collection of features"@en ;
  rdfs:subClassOf 
     :SpatialObjectCollection ;
     [
         rdf:type owl:Restriction ;
         owl:allValuesFrom :Feature ;
         owl:onProperty rdfs:member ;
    ] ;
.
```

Any thoughts on the `SpatialObjectCollection` `scopeNote`?

**Comment by FransKnibbe** [comment]
> Any thoughts on the `SpatialObjectCollection` `scopeNote`?

I like the idea of saying that only annotation properties apply to the collection itself. A nice solution!

But one other thing bothers me. Group membership is set in the definition of a collection. For instance, you could have a `FeatureCollection` instance listing a bunch of Feature IRIs. But when a Feature instance is encountered, how are people and machines to know that the Feature instance has some of its properties set at the collection level?
To indicate that a Feature is part of a dataset, a property like `void:inDataset ` can be used. It is a way to find and access metadata that are supplied at a higher hierarchical level. But the base RDF vocabularies do not seem to have something like that to indicate membership of a container.

**Comment by FransKnibbe** [comment]
> And from an English language pov, a container does not include its contents, while a collection does ;-)

True enough. And with explicitely stating that our collections are subclasses of `rdf:Bag`, RDF people will know that the collections are containers in RDF parlance.

**Comment by nicholascar** [comment]
> To indicate that a Feature is part of a dataset, a property like void:inDataset can be used. It is a way to find and access metadata that are supplied at a higher hierarchical level. But the base RDF vocabularies do not seem to have something like that to indicate membership of a container.

So we need an inverse property of `rdfs:member`? I've been using `dcterms:hasPart` / `dcterms:isPartOf` until now with custom collections (i.e. before GeoSPARQL contained collections) usually only declaring one form in the data and entailing the other. Then I have `Feature isPartOf/isPartOf Dataset` too.

Can we perhaps leave this level of packaging up to implementers? We haven't even yet touched on Dataset, only the *Collection classes.

So yes _you_ could use `void:inDataset` with Features within a `void:Dataset` and please please contribute such an example to the [Extended Examples PR](https://github.com/opengeospatial/ogc-geosparql/pull/161) to go alongside my DCAT example!

---

Other than that it sees you're happy with these new definitions, so I'll put an update commit against the branch in PR #150, if @dr-shorthair is ok with that.

**Comment by FransKnibbe** [comment]
> So we need an inverse property of `rdfs:member`? I've been using `dcterms:hasPart` / `dcterms:isPartOf` until now with custom collections (i.e. before GeoSPARQL contained collections) usually only declaring one form in the data and entailing the other. Then I have `Feature isPartOf/isPartOf Dataset` too.
> Can we perhaps leave this level of packaging up to implementers? We haven't even yet touched on Dataset, only the *Collection classes.

I think in this case extra guidance is needed. Yes, it could be left entirely to implementers. In that case, `dcterms:isPartOf` would be a good candidate to indicate inclusion of an object in a collection. But such a general property could be used for other mereological relationships too. For example: stating that an administrative area is (administratively) a part of another area. Just encountering a property that tells the object is part of some other resource doesn't tell that the other resource is a source of extra properties. I think that the extra properties defined higher up are too easy to miss if GeoSPARQL doesn't provide some sort of guidance.

I wonder, if we were to add something like this:

```
:inSpatialObjectCollection
  a owl:ObjectProperty ;
  rdfs:domain :SpatialObject ;
  rdfs:range :SpatialObjectCollection ;
  owl:inverseOf rdfs:member ;
.
```
would that make it possible to have datasets where collection membership is only set at the member level, not at the collection level? I suspect that would be more easy to manage (no updating of large collections needed in dynamic datasets) and to use (assuming Features and Geometries are more frequent points of entry for users).

> 
> So yes _you_ could use `void:inDataset` with Features within a `void:Dataset` and please please contribute such an example to the [Extended Examples PR](https://github.com/opengeospatial/ogc-geosparql/pull/161) to go alongside my DCAT example!

When this topic is finalized it definitely needs a good example. Preferably one with annotation properties for the collection and GeoSPARQL and non-GeoSPARQL properties for all collection members. I'd be happy to make make something up.

**Comment by dr-shorthair** [comment]
> So we need an inverse property of rdfs:member?

Generally that is not necessary in RDF as you can include the reverse relationship in the graph and query and reason over that anyway. There is some benefit in reducing the potential variation, also because it reduces the risk of inconsistency.

**Comment by FransKnibbe** [comment]
> Generally that is not necessary in RDF as you can include the reverse relationship in the graph and query and reason over that anyway. There is some benefit in reducing the potential variation, also because it reduces the risk of inconsistency.

To reduce variation and the risk of incosistency, I like the idea of having the inverse of rdfs:member completely replace the rdfs:member relationship. In other words: recommending that collections of SpatialObjects be defined bottom-up instead of top-down. It would have the following advantages:

- Prevent very large and unwieldy collection instances (having thousands or millions of members).
- Easy updating of collections: deleting a member removes the member from the collection; adding a SpatialObject with an  `:inSpatialObjectCollection` (or some other name) property adds it to the collection.
- Less chance of missing extra properties that are expressed at the collection level, considering that SpatialObject instances like Features or Geometries are likely points of entry for a graph (e.g. as the result of a query, or as the result of selection in a GUI).

**Comment by dr-shorthair** [comment]
The complexity is the same either way. It is exactly the same number of triples. The fact that they appear nested in Turtle is just sugar in the surface syntax.

**Comment by FransKnibbe** [comment]
> The complexity is the same either way. It is exactly the same number of triples. The fact that they appear nested in Turtle is just sugar in the surface syntax.

Yes, the number of triples is the same in both cases. But I think there is a difference in complexity/ease of use/comprehensibility. This is based on the assumption/observation that the common/natural way of presenting individuals in RDF graph is by their direct properties. Now in case collection membership is set at the collection level, requesting or dereferencing a collection will show annotation properties for the collection, properties that are shared among the members of the collection, and a potentially very long list of members. Requesting a Spatial Object, or dereferencing its IRI will show its direct properties, without any indication of membership of a collection that sets extra properties (that is, if common RDF tools are used that do not know about the special meaning GeoSPARQL attaches to SpatialObjectCollections).

On the other hand, in case collection membership is set at the member level, the data describing the collection will be more succint, and data describing individuals will have an explicit link to the collection, where additional properties can be found. I think this way much less prior knowledge of the GeoSPARQL collection scheme is needed for users.

Also, consider updates of collection membership: In case membership is set at the member level, only the SpatialObject that is added, changed or removed needs to be touched, The collection can be left as it is. That seems more efficient to me.

**Comment by dr-shorthair** [comment]
> difference in complexity/ease of use/comprehensibility. This is based on the assumption/observation that the common/natural way of presenting individuals in RDF graphs is by their direct properties

Collection-hasMember->Item is still directly related to the Item, it is just in the inverse direction. I think you are focusing on the presentation view. I'm trying to point out that the presentation view that you want to see can be easily built from the standard hasMember triples. You can display or update those just as easily in one direction or the other, its just a matter of constructing the correct SPARQL query or update operation. Don't confuse the surface syntax of one particular serialization with the underlying semantics. 'direction of knowledge' does not really apply to RDF graphs.

**Comment by FransKnibbe** [comment]
> Collection-hasMember->Item is still directly related to the Item, it is just in the inverse direction. I think you are focusing on the presentation view. I'm trying to point out that the presentation view that you want to see can be easily built from the standard hasMember triples. You can display or update those just as easily in one direction or the other, its just a matter of constructing the correct SPARQL query or update operation. Don't confuse the surface syntax of one particular serialization with the underlying semantics. 'direction of knowledge' does not really apply to RDF graphs.

Yes, I was focusing on presentation. And I was assuming that common presentations in most cases display only outgoing properties of a resource (properties with the the resource IRI as the subject). But some sampling of public LOD-sets showed it is common to show incoming properties (properties with the resource IRI as the object) too. And, at least in the case of Virtuoso, showing incoming properties is the default for SPARQL DESCRIBE. So I seem to have been out of touch with reality.

I still wonder about the relative ease of updating graphs though, especially in scenarios with a very high update frequency.

**Comment by nicholascar** [comment]
@dr-shorthair @FransKnibbe can we please resolve this Issue and thus PR #150 ASAP? If possible, can any further thoughts/proposals be added by the meeting this week when we can then enter a final discussion? I'd like to finalise all standing PRs within a fortnight and hopefully not have to create any new PRs other than urgent bug fixes, so we can finalise the 1.1 Draft for wider circulation at the end of July.

**Comment by dr-shorthair** [comment]
> I still wonder about the relative ease of updating graphs though, especially in scenarios with a very high update frequency.

Not sure I understand this. It is no more difficult to update `C1 rdfs:member F1 .` than `F1 my:isMemberOf C1 .`

**Comment by FransKnibbe** [comment]
> > I still wonder about the relative ease of updating graphs though, especially in scenarios with a very high update frequency.
> 
> Not sure I understand this. It is no more difficult to update `C1 rdfs:member F1 .` than `F1 my:isMemberOf C1 .`

In the case of `F1 my:isMemberOf C1 .`, when membership of F1 changes, only F1 needs to be updated. In the other case, it possible that both individuals need to be updated. From a user's perspective, that can be regarded as minor overhead. For example, use a more elaborate SPARQL UPDATE query. But I can imagine it being more difficult for implementers of data storage systems. In case of large and dynamic datasets, for example with collections that contain millions of members and rapidly changing membership, I can imagine that the part of the data structure that houses the collection could come under stress, effecting overall system performance. It probably also depends on whether the data store has special provisions to handle RDF collections/containers, and whether the GeoSPARQL collections are recognized as such.
It is conjecture on my part, but I think it's worth asking data store implementers about this particular design issue.

**Comment by nicholascar** [comment]
> It is conjecture on my part, but I think it's worth asking data store implementers about this particular design issue.

OK, well then if the next round of discussion here is to benefit from outside review, we can cease discussion here for the moment and approve PR #150 and then put that to implementers for review. @FransKnibbe: when we compile review notes for implementers, please can you be sure to flag this issue as something specific that you want feedback on?

@dr-shorthair can you please move your PR out of draft so we can formally review it?

**Comment by FransKnibbe** [comment]
@FransKnibbe: when we compile review notes for implementers, please can you be sure to flag this issue as something specific that you want feedback on?
Yes. I have made [issue 170](https://github.com/opengeospatial/ogc-geosparql/issues/170) as a reminder.
