### ISSUE TITLE
Availability in JSON-LD format

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogc-geosparql#15]
**Official change request**: [OGC CR 591](http://ogc.standardstracker.org/show_request.cgi?id=591)

The GeoSPARQL ontology is available online in XML and TTL formats. JSON-LD could be added as an additional publication format, supported by content negotiation of course. This will allow easier consumption of the ontology by web pages. This, in turn, allows easier consultation of the ontology by humans. For example, parts of the ontology could be visualized as diagrams, or definitions of terms could be rendered as tooltips on web pages.

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Must)](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Should)](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Could)](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Won%27t)](https://api.gh-polls.com/poll/01EJXAYS6ADTA59KQEMAYMFR7J/Won%27t/vote)

**Comment by FransKnibbe** [comment]
This is relatively easy to do, it could be an automated step in the publication process.

**Comment by jabhay** [comment]
This is linked it #10 . I'd like to follow @rob-metalinkage 's suggestion above, and submit the PR to the OGC Naming Authority to accomplish this via content negotiation once #10 is complete.

Any issues @ghobona ?

**Comment by nicholascar** [comment]
See https://github.com/opengeospatial/ogc-geosparql/issues/40#issuecomment-729624898: JSON-LD will be able to be auto-generated by the NA, as will Turtle.

**Comment by rob-metalinkage** [comment]
Note also the issue of JSON-LD encodings for features (as opposed to of the vocabulary itself) - see https://github.com/opengeospatial/ogc-feat-geo-json/issues/26

**Comment by nicholascar** [comment]
@rob-metalinkage not really relevant for GeoSPARQL 1.1 deliverables. 

@situx yes please: please add to the GH Action to auto-generate from the Turtle and spit out another entry in the profile.ttl that is for the JSON-LD, perhaps like this:

```turtle
<http://www.opengis.net/ont/geosparql.jsonld>
    a prof:ResourceDescriptor ;
    dcterms:title "GeoSPARQL Ontology in JSON-LD"@en ;
    dcterms:description "The GeoSPARQL 1.1 ontology in RDF (JSON-LD)"@en ;
    dcterms:format "application/ld+json" ;
    prof:hasArtifact "https://github.com/opengeospatial/ogc-geosparql/master/1.1/geo.jsonld"^^xsd:anyURI ;
    prof:hasRole role:schema ;
.
```

**Comment by nicholascar** [comment]
All RDF assets are now available in Turtle & JSON-LD. There is also an entry in the Profile Declaration as above.

This issue should still be left open through until the NA delivers all GeoSPARQL 1.1 RDF assets in all formats, including JSON-LD.

**Comment by jabhay** [comment]
The work required for this in the group has been complete. This ticket will be completed upon publication, but we're closing the ticket now.
