### ISSUE TITLE
Ontology versions and query support

### ISSUE THREAD

**Issue by johnbeve** [opengeospatial/ogc-geosparql#154]
As I understand, GeoSPARQL has two parts: the ontology and the query capability, and two versions: GeoSPARQL 1.0 and 1.1. Which version(s) of the query capability are compatible with which versions of the ontology? Put another way, how shall I fill out the following table where Y indicates that the two are compatible and N indicates that they are not:

&nbsp; | GeoSPARQL Ontology 1.0 | GeoSPARQL Ontology 1.1
-- | -- | --
GeoSPARQL Query support 1.0 | &nbsp; | &nbsp;
GeoSPARQL Query support 1.1 | &nbsp; | &nbsp;

**Comment by FransKnibbe** [comment]
Hi @johnbeve, GeoSPARQL 1.1 comprises an update of both the ontology and the SPARQL query capability. In both cases, 1.1 mainly adds to the 1.0 versions. Nothing that is in 1.0 should be broken by 1.1.

**Comment by situx** [comment]
I think this issue is also resolved. Closing...
