### ISSUE TITLE
Align Requirement numbering in Annex A & Spec body

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#157]
In the Annex, numbering is like A.3.6.1 `/req/geometry-extension/dggs-literal`. 

In the body, we have small tables like *Req 28*... `/req/geometry-extension/dggs-literal`.

We need to align these.

**Comment by jabhay** [comment]
Done as it's own task, but this is a work in progress as the numbering continuously changes.
