### ISSUE TITLE
IRI Requirements for NA

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#163]
Here is a table of existing and another of new IRIs (URIs) needed from the Naming Authority:

### Existing

**Thing** | **IRI pattern** | **Notes**
--- | --- | ---
Specification Doc | <http://www.opengis.net/doc/IS/geosparql/1.0> | Single IRI, not a pattern
Ontology | <http://www.opengis.net/ont/geosparql> | Will soon point to 1.1 thus version IRI needed for 1.0
SF Vocab | <http://www.opengis.net/ont/sf> | redirecting to <http://schemas.opengis.net/sf/1.0/simple_features_geometries.rdf>, should be Defs server

### Needed

**Thing** | **IRI pattern** | **Notes**
--- | --- | ---
Ontology (versioned) <http://www.opengis.net/ont/geosparql/1.0> | Single IRI, not a pattern

### Existing

**Thing** | **IRI pattern** | **Notes**
--- | --- | ---
Ontology | <http://www.opengis.net/ont/geosparql> | Will soon be the "head" version and will use this IRI

### Needed

**Thing** | **IRI pattern** | **Notes**
--- | --- | ---
Profile | <http://www.opengis.net/def/geosparql> | If registered as a pattern, this IRI covers many below
Functions & Rules vocab | <http://www.opengis.net/def/geosparql/funcsrules*> | covered above
Spatial Aggregate Funcs Vocab | <http://www.opengis.net/def/geosparql/safuncs*>  | covered above
SHACL validator | <http://www.opengis.net/def/geosparql/validator> | covered above
Terms & Defns Vocab | <http://www.opengis.net/def/geosparql/td*> | covered above
Requirement Classes | <http://www.opengis.net/def/geosparql/req*> | covered above
Conformance Classes | <http://www.opengis.net/def/geosparql/conf*> | covered above
Functions Namespace | <http://www.opengis.net/def/function/geosparql*> |
Rules Namespace | <http://www.opengis.net/def/rule/geosparql*> |
Specification Doc | <http://www.opengis.net/doc/IS/geosparql/1.1> | Single IRI, not a pattern
Ontology (versioned) | <http://www.opengis.net/ont/geosparql/1.1> | Single IRI, not a pattern

_INCOMPLETE_

**Comment by jabhay** [comment]
- [ ] Run a link checker on the specification document and ensure all IRIs resolve.
- [ ] Extract unique IRIs from all rdf assets and ensure they resolve.
- [ ] Reduce non-resolving URIs into patterns and submit them to the Naming Authority for publication.

**Comment by nicholascar** [comment]
This Issue has been superseded by Issues raised on the NA's Issue tracker:

* [NA \#241](https://github.com/opengeospatial/NamingAuthority/issues/241)
* [NA \#240](https://github.com/opengeospatial/NamingAuthority/issues/240)
* [NA \#238](https://github.com/opengeospatial/NamingAuthority/issues/238)
