### ISSUE TITLE
Add a full glossary of terms

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#164]
The GeoSPARQL specification has a section on terms and definitions ([07-Part-04.adoc](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/spec/07-Part-04.adoc)), but currently it only says readers can find definitions in one of the nine normative documents. Most (all?) OGC standards have their own glossaries of terms though. Especially for GeoSPARQL, with its cross-domain audience, it would be useful for readers to have direct access to explanations of terms that are used in the specification but not defined in the ontology. Those terms can come from the Semantic Web domain and the geoinformatics domain.

Definitions should be hyperlinked to authoritative sources where possible.

**Comment by nicholascar** [comment]
> Definitions should be hyperlinked to authoritative sources where possible.

Can we please present the terms as a SKOS vocab, which we can then convert to ASCIIDOC for use in the Spec using pyLODE? I’ve committed to the Naming Authority that we will define all our terms in this way and format convert them so that then can be easily absorbed into a collected pool of OGC NA Terms & Conditions.

I’ll provide an example SKOS concept shortly - we need additional properties like `rdfs:isDefinedBy` to ensure the NA vocab tools can show both where the term is used (via `skos:inScheme`) and where it is originally defined. I’ll also extend pyLODE to make a Spec’s T&D section in ASCIIDOC this week.

We can start here with just the list of terms to be defined and then add in the SKOS later.

**Comment by FransKnibbe** [comment]
Yes, using SKOS seems a good idea. Do you think pyLODE can handle broader/narrower relationships? For example between SRS and CRS?

**Comment by nicholascar** [comment]
Oh, absolutely! Just throw in any SKOS you like and assume it'll be handled. So far, pyLODE does everything I've ever encountered with SKOS, including the really fancy example format you see [here in the PR](https://github.com/opengeospatial/ogc-geosparql/pull/165/files#diff-d6ea3b158ee302edab2a707e28d0608c3cb26c5dec2f318018ec4cb67ab79cfcR152). I just have to make a "headless" version of the ADOC output, i.e. just the Clause 4 section heading, not a complete document's heading

**Comment by dr-shorthair** [comment]
The [ISO/IEC directives](https://www.iso.org/sites/directives/current/part2/index.xhtml) has guidance about what constitutes a good definition - see [clause 16.5](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor218) in particular 16.5.6: 
- The definition shall be written in such a form that it can replace the term in its context. It shall not start with an article (“the”, “a”) nor end with a full stop. A definition shall not take the form of, or contain, a requirement.
- Only one definition per terminological entry is allowed. If a term is used to define more than one concept, a separate terminological entry shall be created for each concept and the domain shall be included in angle brackets before the definition.
- Circular definitions, which repeat the term being defined, are not allowed.

`skos:definition` should hold a single precise definition. `skos:scopeNote` should hold a gloss. If you want to provide an alternative phrasing of the definition, probably best to use a generic `skos:note`. 

Also note that the ISO/IEC directives encourage examples - use `skos:example` of course.

**Comment by FransKnibbe** [comment]
A simple glossary was added by [PR 193](https://github.com/opengeospatial/ogc-geosparql/pull/193). It can be added to when necessary. Perhaps a later version of GeoSPARQL will have a full SKOS vocabulary.
