### ISSUE TITLE
Best place for specifications of DGGS literals?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#167]
In the current master branch of GeoSPARQL 1.1 there is a property `:auspixDggsLiteral`:

```
:auspixDggsLiteral
	a rdfs:Datatype ;
	rdfs:subClassOf :dggsLiteral ;
	rdfs:isDefinedBy geosparql: , geosparql-spec: ;
	rdfs:seeAlso "https://github.com/GeoscienceAustralia/AusPIX_DGGS"^^xsd:anyURI ;
	skos:definition """A textual serialization of an AusPix Discrete Global Grid System (DGGS) geometry object."""@en ;
	skos:example """ "OrdinateList (R3234)"^^geo:auspixDggsLiteral""" ;
	skos:scopeNote "This datatype is to be used only for a specific DGGS implementation - AusPix. Other DGGS implementations should declare their own datatypes." ;
	skos:prefLabel "AusPIX DGGS Literal"@en ;
.
```

Is the main GeoSPARQL ontology the best place for definitions of DGGS literals? Or is there a better way?

**Comment by FransKnibbe** [comment]
To me the specification of individual DGGS literals seems akin to the specification of individual Coordinate Reference Systems. The best way to handle CRS, in my mind, is to have a dedicated CRS ontology (a few already exist) and a registry of CRSs based on such an ontology. In the GeoSPARQL ontology then, the only thing that is needed is the ability to reference a CRS by URI. My feeling is that for DGGSs it should work the same way: ideally have a single DGGS ontology that defines all possible parameters, and base a registry on such an ontology.

Some pointwise arguments why` :auspixDggsLiteral` looks out of place in the GeoSPARQL ontology:

- Not all developers of DGGS encodings are at liberty to add their specifications to GeoSPARQL.
- The data encoded are more in the realm of instance data than ontological in nature.
- The github link seems to indicate that this particular DGGS is still in development (GeoSPARQL should be as stable as possible).
- I've got the impression that AusPIX has a regional (not global) focus.

**Comment by nicholascar** [comment]
AusPIX details have been made non-normative. They exist in examples only.
