### ISSUE TITLE
Small Readme Grammar Fix

### ISSUE THREAD

**Issue by PR0CK0** [opengeospatial/ogc-geosparql#169]
This isn't a code issue but something I notice all the time and it bothers me. The section of the readme titled [Methodology](https://github.com/opengeospatial/ogc-geosparql#methodology)...

As you should know from the definition of ontology (roughly, "the study of being"), the suffix -logy/-ology implies "the study of". So, when you use the term "methodology", you are saying "the study of methods". The appropriate term here is probably just _method_. I think some definitions will say methodology is like a body of techniques, and therefore more or less equivalent to method; but in a basic sense, I think the two are very different.

I see this at least once in every scientific paper I read. It is probably incorrect grammar and I hope more people realize it. I don't have much reach as an individual but maybe you fine folks can send the word along to colleagues.

**Comment by FransKnibbe** [comment]
@PR0CK0: When I look up the meaning of ¨methodology¨ in online dictionaries, the only or primary meaning is a body of techniques. This is probably another case of colloquial language gaining the upper hand over logic and knowledge of etymology. I too find these occurrences lamentable (in my country food producers are calling products that have production methods that are not overly harmful to the environment ¨biological¨), but a fact of life is that language reforms are ruled by majorities.
Anyway, for the good cause I have changed ¨methodolgy¨ to ¨process¨ in the readme.

**Comment by jabhay** [comment]
This change was made.
