### ISSUE TITLE
clearly define 'requirements class' and 'conformance class'

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#175]
The GeoSPARQL specification uses the terms  'requirements class' and 'conformance class' and says they correspond, but clear definitions of those terms are lacking. Explanations could be added in the text when those terms are used for the first time.

See [issue 120](https://github.com/opengeospatial/ogc-geosparql/issues/120) for discussion on the meaning of the terms.

**Comment by dr-shorthair** [comment]
Those terms are defined in the OGC Policy document - 
"The Specification Model — A Standard for Modular specifications" available from https://www.ogc.org/ogc/policies/directives

**Comment by FransKnibbe** [comment]
Thank you @dr-shorthair. 

_The Specification Model — A Standard for Modular specifications_ provides the following definitions of "conformance class" and "requirements class" (other definitions need to be included because they are referred to):

1. **requirements class**: aggregate of all **requirement modules** that must all be satisfied to satisfy a **conformance test class**.
2. **requirements module**: aggregate of requirements and recommendations of a specification against a single **standardization target type**.
3. **standardization target type**: type of entity or set of entities to which the requirements of a standard apply.
4. **conformance test class**: set of **conformance test modules** that must be applied to receive a single **certificate of conformance**.
Notes: 
    - When no ambiguity is possible, the word "test" may be left out, so **conformance test class** maybe called a **conformance class**.
    - In this standard, the set of requirements tested by the conformance tests within a **conformance class** is a **requirements class** and its dependencies. Each optional requirement will be in a separate requirements class with other requirements that are part of the same option. Each requirements class corresponds to a separate conformance class. In other words, the only options in a specification conformant to this standard will be if a particular requirements class is tested. Each requirements class will be in a 1 to 1 correspondence to a similarly named conformance class that tests all of the requirements class’s requirements.
 5. **conformance test**: test, abstract or real, of one or more requirements contained within a standard, or set of standards.
 6. **certificate of conformance**: evidence of conformance to all or part of a standard, awarded for passing one or more of the conformance test classes specified in that standard.
 Notes:
    - "Certificates" do not have to be instantiated documents; having proof of passing the conformance test class is sufficient. For example, the OGC currently keeps an online list of conformant applications at http://www.opengeospatial.org/resource/products.
 7. **conformance test module**: set of related tests, all within a single conformance test class.

I assume that "requirement module" and "requirement**s** module" are synonyms. 

All these definitions are not so easy to digest for a reader of the GeoSPARQL specification (I left a few out too) so I wonder how the terms can be explained as simple as possible.

One simplification would be to ignore the concept **requirement module**. The definitions above say that a requirements module is an aggregate of requirements and that a requirements class is an aggregate of requirements modules. Can we say that a requirements class is a set of requirements?

Similarly for "conformance class"; can we just say that a conformance class is a set of conformance tests?

Then we could arrive at the following simplified definitions that can be added to the GeoSPARQL specification:
**requirements class:** set of requirements for a GeoSPARQL module.
**conformance class:** set of tests for each requirement in a requirements class.

Is that acceptable?

**Comment by situx** [comment]
I would agree with this definition.

**Comment by dr-shorthair** [comment]
Yes - ignore the intermediate level ('module') and just focus on requirements/tests and classes (groups) of them.
