### ISSUE TITLE
Change domain of spatial scalar properties from Feature to SpatialObject

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#178]
As decided in teleconference 2012-07-29

**Comment by situx** [comment]
A few questions concerning this:
Do we also need to change the requirements for properties of geo:Geometry to include these?
Besides, in the spec there are two sections:
Standard properties for geo:SpatialObject and
Standard properties for geo:SpatialMeasure

Both sections have the content "To be defined"
What is supposed to be added there?

**Comment by FransKnibbe** [comment]
I kind of forgot about [this earlier comment](https://github.com/opengeospatial/ogc-geosparql/issues/33#issuecomment-825552469). But it still applies, I think. It makes little sense to let measurements of size partake in topological relationships. They are missing a frame of reference that Geometries and Features do have.

**Comment by nicholascar** [comment]
> Do we also need to change the requirements for properties of geo:Geometry to include these?

Yes, and I've done that in the relevant PR.

> Besides, in the spec there are two sections: Standard properties for geo:SpatialObject and Standard properties for geo:SpatialMeasure. Both sections have the content "To be defined" What is supposed to be added there?

I have added notes to the section on `geo:SpatialMeasure` to say that essentially GeoSPARQL 1.1 doesn't make any recommendations about properties for it normatively, however there are a number of examples (informative) that show how it _could_ be used with properties, for example `qudt:numericValue` & `qudt:unit`.

I've added, in PR #186, a couple of sentences for `geo:SpatialObject` that basically say it's abstract and that `Feature` & `Geometry`'s stnadar properties are its standard props.

**Comment by nicholascar** [comment]
> I kind of forgot about this earlier comment. But it still applies, I think. ...

The remaining question there, about relating Spatial Measure to QUDT's  `qudt:Quantity` ,or similar, is picked up in the PR #195, so let's carry on discussion there as PR #184 will likely soon close this Issue.

**Comment by nicholascar** [comment]
The SpatialMeasure class is now gone, so this Issue has no more work to be done.
