### ISSUE TITLE
Define missing vocabulary for requirements and conformance tests

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#181]
The conformance classes and requirement classes have now been defined in RDF, but certain vocabularies would need to be defined and endorsed.

**Comment by FransKnibbe** [comment]
@nicholascar: Do you think the OGC Naming Authority could play a role here? It could be argued that an online vocabulary for requirements and conformance testing would be beneficial for all future OGC products to which conformance testing applies. Even if those products are not (semantic) web based.
Is having us develop such a vocabulary and the NA publish it in general OGC space a reasonable and feasible scenario?

**Comment by ghobona** [comment]
@FransKnibbe The [OGC-NA Name type specification - Specification Elements Policy](https://portal.ogc.org/files/?artifact_id=39194) uses the [OGC Modular Specification (Mod Spec)](https://www.ogc.org/standards/modularspec) as the normative reference for specification elements. If you are proposing an extension to the vocabulary used in the Mod Spec, then the OGC Architecture Board (OAB) is the group to submit the proposal to.

**Comment by situx** [comment]
@ghobona Thank you for the links. I went through the document and tried to create a TTL representation based on the UML model.
https://github.com/situx/ogcmodspecrdf
In case this is useful for you we could contribute this. Apart from that, I will correct our modeled requirements to use classes and properties in the http://www.opengis.net/def/spec-element/ namespace which I think would be the correct one, right?

**Comment by ghobona** [comment]
Thanks @situx.

@rob-metalinkage has been working on something similar, together with @pzaborowski . They are better placed to comment on TTL representation of the Mod Spec.

**Comment by rob-metalinkage** [comment]
hi @situx  - it is under testing now - so great to hear your willingness to use it !  (and any feedback)

we are working on a SHACL supported ontologies and validations for specifications (and all other types of resources we want to support - with automated validation via github actions.  The validation scripts are modular - and I hope to eventually stand-up an online "playground" for it all. In the meantime you could generate a pull request of your RDF against 

https://github.com/opengeospatial/NamingAuthority/tree/master/specification-elements/defs

using the OGC document number as a filename for the TTL file.  

This TTL file augments the information available in the OGC docs register - which can be see here:
https://github.com/opengeospatial/NamingAuthority/tree/master/definitions/conceptschemes/docs.ttl

and is entailed and validated against the modspec, 
https://github.com/opengeospatial/NamingAuthority/tree/master/definitions/models/modspec.ttl

as well as further details around inter-specification relationships and also presentation as a SKOS conceptscheme in the Def server UI.

If really keen could look at the code and/or SHACL here:

https://github.com/opengeospatial/NamingAuthority/tree/master/scripts

and this can be run locally  as per the documentation there

**Comment by situx** [comment]
This one has been cleared up and we have adopted OGC classes wherever possible
