### ISSUE TITLE
Use Fragment IRIs for all Spec obejct refs in Spec

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#183]
Instead of linking a thing defined in the Spec and the ontology, e.g. `Feature` to the ontology, link it to the relevant place in the Spec.

This will change links like this:

```
http://www.opengis.net/ont/geosparql#Feature[`geo:Feature`]
```

to links like this:

```
#_class_geofeature[`geo:Feature`]
```

While I understand the desire to link to a point-of-truth, the links to the ontology "don't work" for humans in the sense that they are fragment IRIs pointing to a single text (turtle) document so always prompt for full document download. Relative hyperlinks back to places in the Spec would be better for human use, as shown in W3C specs, like DCAT, e.g.:

See under the Catalog class section (https://www.w3.org/TR/vocab-dcat/#Class:Catalog), there are links to other things in the ontology & spec, e.g. Catalog Record which is given like this:

```
<a href="#Property:catalog_catalog_record">catalog record</a>
```

**Comment by situx** [comment]
I think it would be good to have at least the ontology link in the definition of the individual requirement.
I also expect that the OGC Naming Authority would create an HTML rendering from the ontology representation so that links to ontology concepts could be resolved in the web browser

**Comment by FransKnibbe** [comment]
> Ah, yes, the Naming Authority will use pyLODE to make an HTML documentation of the ontology, as we are doing now, but we - the SWG and the NA - will still have to do a bit of work to ensure all the IRIs work. Anyhow, I think most IRIs should resolve within the Spec and only some canonical ones, as above, should resolve out to the ontology.

I too assumed that it will be possible to use content negotiation on the ontology, with HTML as one of the supported formats. 

As for including some IRIs that resolve to the ontology, we could agree on a fixed pattern. The spec includes sections that describe ontology terms. All references could be to those paragraphs, with the first IRI mentioned in the section resolving to the ontology. For example, this is how the section on SpatialObject starts:

**Class: geo:SpatialObject**
The class `geo:SpatialObject` is defined by the following:

The text "geo:SpatialObject"  in "he class `geo:SpatialObject` is defined by ..." then could be linked to the ontology, and all other SpatialObject IRIs in the spec could resolve to the section heading anchor.
