### ISSUE TITLE
Which vocabularies for units of measurement does the OGC recommend?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#194]
The documentation of SpatialMeasure says: 

> Properties for Spatial Measure may need to indicate a use a unit of measure. When they do, OGC recommended units of measure vocabularies should be used. See the OGC Definitions Server.

I cannot find a recommendation at the OGC Definitions Server. If there is such a recommendation, can we have a persistent link to it, instead of a general link to the Definitions Server?

**Comment by ghobona** [comment]
On 2021-06-17, the OGC-NA discussed a proposal to deprecate OGC Units of Measure (UOM) URIs and to use QUDT.org URIs in GeoSPARQL.

The background to the discussion is at https://github.com/opengeospatial/NamingAuthority/issues/80#issuecomment-863587536

OGC UOM URIs are those that have a base http://www.opengis.net/def/uom


The OGC-NA decided to delegate the issue of which UOM URIs to use in GeoSPARQL to the GeoSPARQL SWG to decide. 

The GeoSPARQL SWG's decision will not bind other SWGs that are already using OGC UOM URIs.

**Comment by FransKnibbe** [comment]
Thank you for shedding light on the matter, @ghobona. It does leave me confused. So the GeoSPARQL SWG is to pick a single UOM vocabulary? I was not aware of that. But I do think that having too much freedom of choice for UoM can hamper data interoperability.

Since the reason to have liberty of choice in UoM is to be able to use distance units that are not possible to convert to metric, probably the SWG should recommend the vocabulary that is best at expressing historical units of distance.

**Comment by dr-shorthair** [comment]
1. Going back to the last century/millennium, OGC recommended UCUM for unit symbols or codes (in the WMS spec). 

2. If you prefer something that uses URIs, it is hard to go past QUDT. 

AFAIK those are the most widely known and used general-purpose vocabularies or systems for units-of-measurement. 
When OGC (and EPSG) started developing its own URI-based system, QUDT was not available. 
Now that it is, this makes one more thing that OGC does not have to manage itself.

**Comment by ghobona** [comment]
@FransKnibbe The OGC-NA did not place restrictions on the number of UoM vocabularies that the GeoSPARQL SWG may use in the new version of GeoSPARQL. It is for the GeoSPARQL SWG to select one or more that are appropriate for use in GeoSPARQL.

**Comment by FransKnibbe** [comment]
@ghobona: The current situation is that we would like to recommend metre as the standard unit of distance. And if it is somehow not possible to use metres, any UoM vocabulary can be used, see the discussion in [PR 195](https://github.com/opengeospatial/ogc-geosparql/pull/195).
So as it no longer is necessary for the GeoSPARQL SWG to pick a single prefered UoM vocabulary, I will close this issue.
