### ISSUE TITLE
Maintenance for Shapes that are not part of the GeoSPARQL Standard

### ISSUE THREAD

**Issue by jabhay** [opengeospatial/ogc-geosparql#196]
From. GeoSPARQL SWG meeting of July 28

Key question:
How should we manage shapes that are not part of the standard i.e., look at the spatial data rather than just the structure. 

Resolution:
We will create a folder for useful scripts, to enable people to continue working on things that are not part of the specification. This work can be maintained by a community group. The most sensible community group from the SWG's perspective is the Geosemantics DWG.

**Comment by nicholascar** [comment]
Now at https://github.com/opengeospatial/ogc-geosparql-shapes

**Comment by nicholascar** [comment]
To be maintained by GeoSemantics DWG.
