### ISSUE TITLE
geof:boundingCircle is underspecified

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#197]
I have just noticed the aggregate function geof:boundingCircle. It looks like it could use more details about how it should be used and implemented. Its current description:

`The function geof:boundingCircle calculates a minimum bounding circle of the set of given geometries.`

The following would be interesting to know:

1. What happens if there are 3D geometries in the input set?
2. What happens if there are geometries using geodetic coordinates in the input set?
3. GeoSPARQL does not have a native geometry format yet. So at the moment a geometry serialisation should be used. What happens if the speficified serialisation does not support circles?

**Comment by FransKnibbe** [comment]
Hi @situx. looking further at this issue I think more general problems at play. I have opened an issue about limitations on geometry dimension not being clear ([issue 200](https://github.com/opengeospatial/ogc-geosparql/issues/200)) and about treatment of geodetic coordinates not being clear ([issue 201](https://github.com/opengeospatial/ogc-geosparql/issues/201)).

To illustrate the latter problem: what would be the bounding circle of the Earth's North and South poles? But the issue is not limited to `geof:boundingCircle`.

I think only point 3 remains. You seem to say that in case a serialisation does not support circles an approximation should be used. I think we should describe that, an also describe what such an approximation should look like.

**Comment by situx** [comment]
In essence, if we assume that a circle is described by a list of coordinates with the first coordinate being the same as the last coordinate, then any representation that fits these specifications will do.
WKT, GML, KML, GeoJSON define Polygons that would fit here, DGGS would define some equivalent I think?
I would not expect a circle to be described as a diameter and a point for example.

**Comment by FransKnibbe** [comment]
The main point is that it should be clear what the output of the function is. I think it should be a real circle. It does not necessarily need to be serialised. It could also serve as output for another function for example.
As far I can tell, of the current serialisations in GeoSPARQL 1.1 only GML supports circles. I would then expect a GML serialisation to make a GML circle. In other cases, the specification needs to specify what happens. ​

We need not be concerned about DGGS if we make DggsObject a subclass of SpatialObject ([see PR 136)](https://github.com/opengeospatial/ogc-geosparql/pull/136).

Another way of looking at this issue: Should be even think about circles when GeoSPARQL is based on SFA, which does not define circles?

**Comment by situx** [comment]
I believe the issue you are raising could also be applied to other functions defined in GeoSPARQL like intersection and buffer.
What we did in our GeoSPARQL Compliance Benchmark exactly because the serialization type is not specified in GeoSPARQL is to accept a variety of possible answers which are semantically equivalent.
The general question I see should be answered is whether we need to state for every serialization how an appropriate answer should look like

**Comment by FransKnibbe** [comment]
> I believe the issue you are raising could also be applied to other functions defined in GeoSPARQL like intersection and buffer.

Yes, a buffer operation on a point geometry would theoretically produce a circle. But it would not be expected because SFA does not support circles. So it can be expected that some kind of approximation is produced. I think it is up to the GeoSPARQL specification to make clear what that approximation should look like.  

How could the intersection function produce a perfect circle?

> What we did in our GeoSPARQL Compliance Benchmark exactly because the serialization type is not specified in GeoSPARQL is to accept a variety of possible answers which are semantically equivalent.

And is geometric equality also checked? Coordinates and CRS should be exactly the same.

> The general question I see should be answered is whether we need to state for every serialization how an appropriate answer should look like

I don't think so, because I would like to see as little influence of serialisations as possible. But I do think GeoSPARQL should be clear about what the geometries should look like irrespective of serialisation (i.e. coordinates and CRS).

**Comment by situx** [comment]
> > I believe the issue you are raising could also be applied to other functions defined in GeoSPARQL like intersection and buffer.
> 
> Yes, a buffer operation on a point geometry would theoretically produce a circle. But it would not be expected because SFA does not support circles. So it can be expected that some kind of approximation is produced. I think it is up to the GeoSPARQL specification to make clear what that approximation should look like. Spatial resolution, if specified, could play a role. Or otherwise a spatial resolution derived from input precision (e.g. the lesser of the precision of the coordinates and the buffer distance).

That was actually not what I meant. So yes you might interpret a buffer of a point as a circle, but even the type returned to represent a "Polygon" as a result of the buffer functions varies from implementation to implementation.
What I mean is that even if the type to be returned is clear (e.g. a Polygon), there might still be different ways to represent this type "Polygon" in serializations to be considered by a benchmark.
> 
> How could the intersection function produce a perfect circle?
> 
It does not, but it could return different geometry types.

> > What we did in our GeoSPARQL Compliance Benchmark exactly because the serialization type is not specified in GeoSPARQL is to accept a variety of possible answers which are semantically equivalent.
> 
> And is geometric equality also checked? Coordinates and CRS should be exactly the same.
> 
Yes, absolutely, we checked this of course.
> > The general question I see should be answered is whether we need to state for every serialization how an appropriate answer should look like
> 
> I don't think so, because I would like to see as little influence of serialisations as possible. But I do think GeoSPARQL should be clear about what the geometries should look like irrespective of serialisation (i.e. coordinates and CRS).

Ok, so what you are saying is: We should define a geometry type as defined in SFA as a result of every function returning a Geometry and give guidance on equivalent types in serializations not supporting this particular type?

**Comment by FransKnibbe** [comment]
> That was actually not what I meant. So yes you might interpret a buffer of a point as a circle, but even the type returned to represent a "Polygon" as a result of the buffer functions varies from implementation to implementation.

Ah. That was something you learned from your benchmark tests? Do you recall which other geometry types were returned?

> What I mean is that even if the type to be returned is clear (e.g. a Polygon), there might still be different ways to represent this type "Polygon" in serializations to be considered by a benchmark.

Indeed. A buffer operation on a point geometry could return a traingle or the approximation of a circle using 1000 vertices. Both are valid according to the specification. 

> > > The general question I see should be answered is whether we need to state for every serialization how an appropriate answer should look like
> > 
> > 
> > I don't think so, because I would like to see as little influence of serialisations as possible. But I do think GeoSPARQL should be clear about what the geometries should look like irrespective of serialisation (i.e. coordinates and CRS).
> 
> Ok, so what you are saying is: We should define a geometry type as defined in SFA as a result of every function returning a Geometry and give guidance on equivalent types in serializations not supporting this particular type?

In general, SPARQL engines that support GeoSPARQL should be as interoperable as possible. For a user, results of operations should be predictabe, irrespective of implementation. I think the bar should be set higher for GeoSPARQL than for database systems that are more likely to be used in stand-alone systems. How to achieve predictable results is debatable, but inclusion of geometry types in the ontology could certainly play an important role. It allows more precise function definitions. And yes, it would also be possible to make a support matrix of serialisations vs. geometry types.
At the moment, we have a SF types vocabulary: https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/sf_geometries.ttl. It could already be used for those purposes.
Apart from that, to have predictable results from SPARQL engines, GeoSPARQL should also have clear guidance on the spatial resolution of geometries that are generated by functions.
I think I should create new github issues for those general topics.

Getting back `geof:boundingCircle`, perhaps the core issue is that the function says it returns a circle, which is a goemetry type that GeoSPARQL doesn´t know of, because it is based on SFA. If the function would be called geo:boundingCircleApproximation for example, that particular problem would go away. In that case, the output could be specified als always being a Polygon (which is supported by all current serialisations).

**Comment by situx** [comment]
> > That was actually not what I meant. So yes you might interpret a buffer of a point as a circle, but even the type returned to represent a "Polygon" as a result of the buffer functions varies from implementation to implementation.
> 
> Ah. That was something you learned from your benchmark tests? Do you recall which other geometry types were returned?
> 
Just some examples:

For geof:boundary: LineString and LinearRing
For geof:envelope: gml:Envelope, WKT Polygon, EWKT ENVELOPE
For geof:symmetricDifference: gml:MultiSurface, gml:MultiPolygon, WKT MULTIPOLYGON

> > What I mean is that even if the type to be returned is clear (e.g. a Polygon), there might still be different ways to represent this type "Polygon" in serializations to be considered by a benchmark.
> 
> Indeed. A buffer operation on a point geometry could return a traingle or the approximation of a circle using 1000 vertices. Both are valid according to the specification.
> 
Yes exactly. Could also return a TIN representation of the area in question (just because the WKT specification also covers TIN). Even though I think that is highly unlikely, it might be a valid result.

> > > > The general question I see should be answered is whether we need to state for every serialization how an appropriate answer should look like
> > > 
> > > 
> > > I don't think so, because I would like to see as little influence of serialisations as possible. But I do think GeoSPARQL should be clear about what the geometries should look like irrespective of serialisation (i.e. coordinates and CRS).
> > 
> > 
> > Ok, so what you are saying is: We should define a geometry type as defined in SFA as a result of every function returning a Geometry and give guidance on equivalent types in serializations not supporting this particular type?
> 
> In general, SPARQL engines that support GeoSPARQL should be as interoperable as possible. For a user, results of operations should be predictabe, irrespective of implementation. I think the bar should be set higher for GeoSPARQL than for database systems that are more likely to be used in stand-alone systems. How to achieve predictable results is debatable, but inclusion of geometry types in the ontology could certainly play an important role. It allows more precise function definitions. And yes, it would also be possible to make a support matrix of serialisations vs. geometry types.
> At the moment, we have a SF types vocabulary: https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/sf_geometries.ttl. It could already be used for those purposes.
> Apart from that, to have predictable results from SPARQL engines, GeoSPARQL should also have clear guidance on the spatial resolution of geometries that are generated by functions.
> I think I should create new github issues for those general topics.
> 
> Getting back `geof:boundingCircle`, perhaps the core issue is that the function says it returns a circle, which is a goemetry type that GeoSPARQL doesn´t know of, because it is based on SFA. If the function would be called geo:boundingCircleApproximation for example, that particular problem would go away. In that case, the output could be specified as always being a Polygon (which is supported by all current serialisations).

Yes we could require that the Polygon as a result of this functions approximates a circle, i.e. depicts a more special kind of Polygon than e.g. buffer. That might be a solution

**Comment by FransKnibbe** [comment]
> > Ah. That was something you learned from your benchmark tests? Do you recall which other geometry types were returned?
> 
> Just some examples:
> 
> For geof:boundary: LineString and LinearRing
> For geof:envelope : gml:Envelope, gml:Polygon, WKT Polygon, EWKT ENVELOPE
> For geof:symmetricDifference: gml:MultiSurface, gml:MultiPolygon, WKT MULTIPOLYGON
> 
> Fun fact: Even the representation of a boolean is not clear:
> You can represent a boolean result as "true"^^xsd:boolean, "1"^^xsd:boolean, "false"^^xsd:boolean, "0"^^xsd:boolean
> And implementations choose one of the aforementioned solutions (we had all results in our benchmark)

EWKT is not supported by GeoSPARQL, but that is a serialisation error. The different serialisations are not really differences in function output, and those booleans are all valid forms of xsd:boolean. Still, I think guidance on geometry types is needed. So I have raised [issue 206](https://github.com/opengeospatial/ogc-geosparql/issues/206).

**Comment by FransKnibbe** [comment]
> Apart from that, to have predictable results from SPARQL engines, GeoSPARQL should also have clear guidance on the spatial resolution of geometries that are generated by functions.
> I think I should create new github issues for those general topics.


A new issue for the spatial resolution of function output: [issue 207](https://github.com/opengeospatial/ogc-geosparql/issues/207).

**Comment by jabhay** [comment]
- [ ] Create PR for a matrix that further describes the functions, and their inputs and outputs
- [ ] Ensure PR differentiates between functions that are specific to 2d or 3d
