### ISSUE TITLE
Replace references to ISO standards where possible

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#199]
It would be good to have GeoSPARQL reference open standards as much as possible. ISO standards are ~~not~~ less open, because they require payment. Therefore GeoSPARQL could try to replace references to ISO standards with references to equivalent documents as much as possible. 

GeoSPARQL references the following ISO standards:

- ISO 19105 (Geographic information – Conformance and testing)
- ISO 19107 (Geographic information — Spatial schema)
- ISO 19109 (Geographic information — Rules for application schemas)
- **ISO 19125-1** (Geographic information — Simple feature access — Part 1: Common architecture)
- ISO 19156 (Geographic information — Observations and measurements)

Of these, ISO 19125-1 is listed in section 3 (Normative references)

As far as I can tell, only ISO 19125 and ISO 19156 have OGC equivalents:

- https://portal.ogc.org/files/?artifact_id=41579 (OGC 10-004r3, Geographic information — Observations and measurements)
- https://portal.ogc.org/files/?artifact_id=25355 (OGC 06-103r4, OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 1: Common architecture)

Is it possible to replace at least the references to those two standards from ISO to OGC?

**Comment by dr-shorthair** [comment]
I have plenty of criticisms of ISO's business model, but it is incorrect to say that the standards are not _open_ because they are not _free_. Those are distinct concerns. Anyone can access them, therefore they are open. I agree that it is relatively anomalous for information/computing standards to not be free, but it is not unprecedented. 

I've also heard academics object to citing ISO standards for the same reason. That overlooks the fact that most journals are also not free, which academics typically don't notice because they have access to an institutional subscription. So their argument is actually more about culture than cost.

**Comment by FransKnibbe** [comment]
> I have plenty of criticisms of ISO's business model, but it is incorrect to say that the standards are not _open_ because they are not _free_. 

@dr-shorthair: It is a matter of definition. This is from [the wikipedia page on open standards](https://en.wikipedia.org/wiki/Open_standard):

> The definitions of the term open standard used by academics, the European Union, and some of its member governments or parliaments such as Denmark, France, and Spain preclude open standards requiring fees for use, as do the New Zealand, South African and the Venezuelan governments. 

At least we can say that OGC standards are more open than ISO standards.

**Comment by nicholascar** [comment]
I think it's OK to replace ISO with OGC references.

**Comment by dr-shorthair** [comment]
Yes - I agree, though maybe for the ones that are available as both OGC and ISO, list both refs, just put the free one first.

**Comment by nicholascar** [comment]
Agree that dual listing would be best to ensure all cross references between the OGC & ISO canons are shown

**Comment by FransKnibbe** [comment]
I will need to add the OGC documents to [the bibliography](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/spec/19-Bibliography.adoc), but I can't tell how it is ordered. Or if it is ordered. Which ordering rule do we (want to) use?

**Comment by FransKnibbe** [comment]
Another question: Can URIs like https://portal.ogc.org/files/?artifact_id=25355 be considered persistent? Or does the OGC Naming Authority provide persistent URIs?

**Comment by dr-shorthair** [comment]
I understand that the portal artifact URIs are persistent. 
But they are also supposed to be available from better OGC-NA URIs - @ghobona can you confirm?

**Comment by ghobona** [comment]
@dr-shorthair That is correct. The relevant policy is at https://portal.ogc.org/files/?artifact_id=41774

**Comment by jabhay** [comment]
Hi @ghobona , perhaps as an example, could you provide the `better` URI for the relevant policy document?

**Comment by FransKnibbe** [comment]
> @dr-shorthair That is correct. The relevant policy is at https://portal.ogc.org/files/?artifact_id=41774

@ghobona: It is good to see that an OGC policy for minting document URLs exists. But was it really put into practice after its publication in 2011? And should the policy have been applied to documents that were produced before the policy became active? I ask this because some of the example URLs do not resolve; http://www.opengis.net/doc/ER/KML-REQ/1.0 for example.

Also, from reading the document I get the impression that a full registry of named OGC documents (including URL and URN) should be available at http://www.opengis.net/register/ogc-na/name. But I get a 400 Bad Request HTTP error there.

**Comment by ghobona** [comment]
@FransKnibbe The policy is applied every time OGC publishes a document.  

Regarding resolution of URIs, historically the persistent URIs were not configured to resolve by default. However, we have recently started to enable the URIs to resolve. There is a long backlog to go through, so it may be a long time before all of the URIs have been enabled to resolve.

The Documents Policy does need updating and we will update it after the Definitions Policy has been updated.

**Comment by FransKnibbe** [comment]
> @FransKnibbe The policy is applied every time OGC publishes a document.

@ghobona: Great. So the OGC documents that we want to refer to do have URI that comply with the naming policy. The problems remaining are that the URIs are unknown and that there is a chance that they do not resolve at the time the new GeoSPARQL specification is published.

Can the registry of document URIs be made accessible, to allow us to find the URIs needed for GeoSPARQL? And could those URIs, when not resolvable yet, be moved to the top of the stack of URIs that are in need of being resolvable? Or would you recommend just using the OGC portal URIs?

**Comment by ghobona** [comment]
@FransKnibbe Please provide me with the list and I can check the URIs for you. CSV, XLSX, or similar format would be fine.

**Comment by FransKnibbe** [comment]
@ghobona: thank you. The list is short. I could find four OGC documents that GeoSPARQL needs to reference that do not seem to have an official, resolvable URI.  This is that list in CSV format:
```
OGC ID,Title,unofficial URI
20-040r3,Topic 21 - Discrete Global Grid Systems - Part 1 Core Reference system and Operations and Equal Area Earth Reference System,https://docs.ogc.org/as/20-040r3/20-040r3.html
10-004r3,Geographic information — Observations and measurements),https://portal.ogc.org/files/?artifact_id=41579
06-103r4,OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 1: Common architecture,https://portal.ogc.org/files/?artifact_id=25355
07-036,OpenGIS® Geography Markup Language (GML) Encoding Standard,https://portal.ogc.org/files/?artifact_id=20509
```

**Comment by FransKnibbe** [comment]
> I will need to add the OGC documents to [the bibliography](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/spec/19-Bibliography.adoc), but I can't tell how it is ordered. Or if it is ordered. Which ordering rule do we (want to) use?

Ordering is first by author, then by date, see [PR 251](https://github.com/opengeospatial/ogc-geosparql/pull/251).

**Comment by PeterParslow** [comment]
> fees for use

This is about not having to pay patent fees to use (implement) the standard; it is not about the document itself being free of charge. At least, that's the case in the European Union - otherwise, how would they be using CEN standards?

I don't have any problem with citing OGC standards in preference to ISO ones where the document exists in both forms.

**Comment by FransKnibbe** [comment]
@ghobona: Are you able to work with the CSV data from [the previous comment](https://github.com/opengeospatial/ogc-geosparql/issues/199#issuecomment-988975253)?

**Comment by FransKnibbe** [comment]
@ghobona: Thank you! Those are great looking URIs.

**Comment by jabhay** [comment]
I've updated the Bibliography to ensure that:

1. the persistent URI is referenced for all OGC references
2. all co-published ISO/OGC artefacts are also listed as both their ISO and OGC documents

I'm unsure how to dual list them, with the free one first. Is this simply something like [OGCSFACA] [ISO19125-1]? If so, I'll make that change globally in reqs.ttl and the specification.

**Comment by jabhay** [comment]
Through discussion, listing ISO standards after the OGC ones is the goal.
