### ISSUE TITLE
DGGS representation of geometry in GeoSPARQL

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#2]
In the GeoSPARQL extensions ontology we are considering using a list of DGGS identifiers to describe a geometry. 
This is very speculative at present - see 

https://raw.githack.com/CSIRO-enviro-informatics/geosparql-ext-ont/master/geox.html#asDGGS

Note that `geox:dggsLiteral` is an accompanying `rdfs:Datatype` parallel with `geo:wktLiteral` and `geo:gmlLiteral` - see https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/blob/master/geox.ttl#L103

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Must)](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Should)](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Could)](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Won%27t)](https://api.gh-polls.com/poll/01EJXBNDY50ZMG0GW2546FDKWR/Won%27t/vote)
