### ISSUE TITLE
Clarify computations on geodetic coordinates

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#201]
Some Coordinate References Systems are geodetic; they use degrees of latitude and longitude to indicate positions on a sphere-like object (such as Earth). GeoSPARQL is unclear on how computations involving geodetic coordinates should be performed. Take the function `geof:distance` for example. It returns the shortest distance between geometries, using the CRS of the geometry in the first argument. It would be logical to assume that a SPARQL engine supporting GeoSPARQL looks up the CRS IRI to determine if the CRS is geodetic, and use a haversine distance computation if it is. And computing cartesian distance would be wrong. But I would not be surprised if GeoSPARQL implementations always compute cartesian distances.

I think the specification should be more clear on geodetic vs. cartesian CRSs, and be clearer about expected output from functions that can work on geodetic or cartesian CRSs.

**Comment by jabhay** [comment]
Ensure this is covered off by #212
