### ISSUE TITLE
Partial support of Simple Features by KML and GeoJSON

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#202]
GeoSPARQL does is not very clear about the geometry types it supports (also see [issue 42](https://github.com/opengeospatial/ogc-geosparql/issues/42)), but it does say it is based on [Simple Features](https://portal.ogc.org/files/?artifact_id=25355) (SFA). 
As far as I can tell, the GeoSPARQL 1.0 serialisations (WKT and GML) fully support all geometry types specified in SFA. The new 1.1 serialisations, however, do not. 
GeoSPARQL 1.1 should make clear the limitations of GeoJSON and KML to encode GeoSPARQL geometry.

**Comment by nicholascar** [comment]
Perhaps we need a new table at start of the each Functions section, e.g. [Simple Features](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_simple_features_relation_family_relation_familysimple_features_2) listing which of the Geometry formats in [Geometry Serliazations](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_geometry_serializations) are applicable.

I have assigned this to me as I'm happy to work this one.

(and it's ticks for all SF functions for DGGS now too: https://github.com/RDFLib/geosparql-dggs/!)

**Comment by jabhay** [comment]
Ensure this is covered off by #212

**Comment by FransKnibbe** [comment]
> Column Output Datatype Subtypes in #212 covers this.

That could be a place to resolve the issue, but as far as I can tell it has not been done yet. The cells in this column are empty for the different serialisations.

**Comment by nicholascar** [comment]
The table is complete, see https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_b_1_functions_summary_table
