### ISSUE TITLE
GeometryCollections of GeometryCollections?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#203]
[PR 150](https://github.com/opengeospatial/ogc-geosparql/pull/150) has added the class `geo:GeometryCollection` to the ontology. However, the [Simple Features specification](https://portal.ogc.org/files/?artifact_id=25355), on which GeoSPARQL is based, already contains a class GeometryCollection. That means GeoSPARQL implementations would have to deal with two slightly different collections of Geometries. And it means we could have RDF GeometryCollections of SFA GeometryCollections.
Isn't that very complicated?  What is the reason `geo:GeometryCollection` exists if there already is a way to have collections of Geometries?

**Comment by nicholascar** [comment]
`geo:GeometryCollection` was added for consistency with `FeatureCollection` & `SpatialObjectCollection` but I personally haven't ever made one, or an SO Collection, thus I've not included any examples of them either.

Can you think of how the two GeometryCollections might be used differently?

**Comment by FransKnibbe** [comment]
> Can you think of how the two GeometryCollections might be used differently?

Obviously, the GeometryCollection in the ontology lends itself more to operations that are native to the Semantic Web. It provides direct access to members of the set. The SF GeometryCollection is more of a black box at the moment, because GeoSPARQL does not offer tools to construct or deconstruct SF GeometryCollections (like ST_Dump and ST_Collect in PostGIS). If GeoSPARQL were to have such functions, it would be strange if they worked only on collections of geometries, and not on collections of Features and Spatial Objects.

So I guess there is a place for GeometryCollection in the ontology. But it could be tricky to forbid the use of SF GeometryCollections because the type is used in existing datasets. 

At the moment, it seems to me it is best to keep them both. But without guidance and documentation that situation could be confusing. A pragmatic solution could be to mark the existence of both flavours and provide guidance on how to distinguish them and how to use them.

**Comment by situx** [comment]
I think it would make sense to relate the two classes with either an owl:equivalentClass or rdfs:subClassOf relation. Would that not solve our problems or would that be semantically wrong?

**Comment by nicholascar** [comment]
> I think it would make sense to relate the two classes

But we have no OWL representation of the SFA GeometryCollection, so we can't do this. 

Perhaps the best we can do is to put a note into the Spec under the `geo:GeometryCollection` definition to mention that there is a similarly named SFA class, but that we have no ontology representation of it here.

**Comment by situx** [comment]
Why do we not have this representation? What prevents us to link to the sf:GeometryCollection class?

**Comment by nicholascar** [comment]
Eeek, you're right, https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/sf_geometries.ttl#L92. I didn't realise that class was implemented in the Simple Features Vocabulary.

So for consistency, (of the class structure) I think we should keep the `geo:GeometryCollection` class and then link it to `sf:GeometryCollection`. Will have to determine if it's an `owl:equivalentClass` or perhaps `rdfs:subClassOf` in one direction or the other.

**Comment by nicholascar** [comment]
`sf:GeometryCollection`: "A GeometryCollection is a geometric object that is a collection of some number of geometric objects."

`geo:GeometryCollection`: "...represents any collection of Geometry entities."

They are completely different ways of representing something similar, the first within a literal (microformat) and the other in RDF.

So we have no relationship (`owl:equivalentClass` or perhaps `rdfs:subClassOf` in one direction or the other) that can sensibly be made between them thus I propose we do nothing.

**Comment by mperry455** [comment]
Let's add this comment to the spec to help explain the difference

**Comment by mperry455** [comment]
Probably also want to mention other microformats with geometry collections like GML

**Comment by FransKnibbe** [comment]
> So we have no relationship (`owl:equivalentClass` or perhaps `rdfs:subClassOf` in one direction or the other) that can sensibly be made between them thus I propose we do nothing.

But that would still leave a very confusing situation for GeoSPARQL users. I think guidance is needed: In which case does it make sense to use one or the other?

**Comment by situx** [comment]
My perspective is the following:
- I would always recommend to use a geo:GeometryCollection to users because this is the most "RDF"-way
- However, literal formats allow for the definition of GeometryCollections which are not semantically modeled and we need to be able to integrate these GeometryCollections such as sf:GeometryCollection as well
