### ISSUE TITLE
Interpretation of geo:hasLength

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#204]
Currently, the description for `geo:hasLength` reads:

> The property geo:hasLength is used to indicate the length of a geo:SpatialObject which could be either a geo:Feature or a geo:Geometry. In the case of a one-dimensional geo:Feature, it is the simple length. In the case of a two-dimensional geo:Feature, it is interpreted to mean the perimeter length.

Naturally, the same goes for `geo:hasMetricLength`.

What is the reason for this restricted interpretation? Why can't the property be used to indicate the length of a boat or a fence or a crocodile? Or for two-dimensional things, the length of a football pitch?

Also, the way the length of a three-dimensional Geometry should be interpreted is unclear. Is it the length or the perimeter of e.g. a swimming pool?

It is nice to be able to specify a perimeter, but why not have a `geo:hasPerimeter` property then?

**Comment by jabhay** [comment]
PR merged
