### ISSUE TITLE
Missing requirement for properties of SpatialObject

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#211]
There is no requirement for support of the properties of SpatialObject in the spec. A new PR is needed to add the requirement, after [PR 210](https://github.com/opengeospatial/ogc-geosparql/pull/210) (which adds more SpatialObject properties) is merged.

**Comment by nicholascar** [comment]
The Req was there ([Req 7](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_standard_properties_for_geospatialobject)) but the IRI was wrong and it wasn't listed in Annex A. 

PR #236
