### ISSUE TITLE
Propose how authoring metadata should be included

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#22]
Contributed by Mathias Bonduel and Anna Wagner for the white paper "Benefits of Representing Spatial Data using Semantic and Graph Technologies":

In AEC, authoring metadata (e.g. author, date, revision, etc.) is of high relevance for multiple aspects of collaboration, such as coordination and legal issues. Hence, the domains requires authoring metadata to be attached to any kind of information -- and with geometry oftentimes being the core structure for non-geometric information -- this is even more important for geometry descriptions. To avoid inconsistent and varying attachments of authoring metadata, we suggest to formulate a best practice for enhancing GeoSPARQL triples with authoring information, ideally by reusing existing concepts of provenance ontologies, e.g. PROV-O, DCTerms, etc.

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Must)](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Should)](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Could)](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Won%27t)](https://api.gh-polls.com/poll/01EJXASQ6PZC5YSASYMVNXNNQ9/Won%27t/vote)

**Comment by FransKnibbe** [comment]
Would it be wise to include a best practice description in a specification such as GeoSPARQL? One could argue it is out of scope, and more fitting to include in the [Spatial Data on the Web Best Practices document.](https://www.w3.org/TR/sdw-bp/).

**Comment by jabhay** [comment]
The working group would like to defer this to 1.2 or beyond, and liaise with the W3C Spatial Data on the Web working group on recommended best practices for recording provenance and attribution of spatial data.

**Comment by jabhay** [comment]
We've decided to attribute at the specification/document level. There are still some attribute level attributions that need to be removed.

- [ ] Remove attribute-level attributions.

**Comment by jabhay** [comment]
Remaining task was split into #352
