### ISSUE TITLE
Example B 1.2.2 missing Z coordinate

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#228]
I have the following questions/problems with example B1.2.2:

1. In example B1.2.2, the geometry is missing a Z coordinate and is not defined as POLYGON Z in the WKT literal.
It is not necessarily a problem per se, but I find it confusing that the feature defines a volume but does not provide a 3D geometry. This case can occur, but I wonder if it should be illustrated in this example.
2. In addition, it poses the question: What do we do if we have a 3D and a 2D representation of the same geometry?
Would it make sense to define a relation geo:has3DGeometry?
3. Also if two geometries are related to the geo:Feature, e.g. geo:hasDefaultGeometry relates to a 2D representation and geo:hasGeometry relates to a 3D representation, which value do we assign to a geo:hasBoundingBox relation attached to the feature representation? The 2D or the 3D bounding box?
4. The same question for the geo:hasCentroid property
5. Suppose we assign two centroids and two boundingboxes to the feature. Do we need to relate them to the respective geometry somehow?

Clearly, there is also a workaround for some of the points 3-5: Many properties like geo:hasVolume can also be used at a Geometry instance. However, the geo:hasBoundingBox and geo:hasCentroid properties are for now defined in the domain of geo:Feature, so for those the points raised in 3.-5. are still valid.
Do we leave this up to the users to decide?

**Comment by jabhay** [comment]
Moved into GeoSPARQL 1.1 for discussion at next meeting

**Comment by nicholascar** [comment]
I've added a note for point 1. in PR #235 

For 2.: you do whatever you want if you and 2D & 3D data. GeoSPARQL allows you to represent it but doesn't have to tell you how to handle is, just as it doesn't tell you how to handle conflicting 2D geometries.

For 3.: As above, your (user) choice.

For 4.: As above

For 5.: We don't have properties to relate geometries to one another as other spatial ontologies, such as NeoGeo does (http://geovocab.org/geometry#bbox). This should be put up for consideration in 1.2.

**Comment by mathib** [comment]
> 2. In addition, it poses the question: What do we do if we have a 3D and a 2D representation of the same geometry?
Would it make sense to define a relation geo:has3DGeometry?

No, I would limit the creation of new relations (object properties) as much as possible (see https://github.com/opengeospatial/ogc-geosparql/pull/219#issuecomment-973855057 for the reasoning behind it). Why are the properties `geo:coordinateDimension` and/or `geo:dimension` not sufficient for your use case? If they wouldn't be sufficient, we can also consider to add subclasses of `geo:Geometry` (e.g. `geo:3DGeometry`, `geo:2DGeometry`). This is less elegant compared to the existing GeoSPARQL dimension properties (might result in the need to assert multiple classes to an individual), but less impactful compared to adding new relations.

> 3. Also if two geometries are related to the geo:Feature, e.g. geo:hasDefaultGeometry relates to a 2D representation and geo:hasGeometry relates to a 3D representation, which value do we assign to a geo:hasBoundingBox relation attached to the feature representation? The 2D or the 3D bounding box?

I would say that a `geo:Feature` can have multiple geometry serializations, thus including multiple bounding boxes. In your example, you can assert the 2D BB, the 3D BB or both BB (or even multiple 2D BB and multiple 3D BB).

> Suppose we assign two centroids and two boundingboxes to the feature. Do we need to relate them to the respective geometry somehow?

That's a nice proposal. It's also something we provided in the OMG ontology patterns ([omg:isDerivedFromGeometry](https://w3id.org/omg#isDerivedFromGeometry) links between 2 geometries, to describe the dependency). It's optional since a BB or centroid might also exist without knowing the geometry where it was derived from.

**Comment by situx** [comment]
> > 1. In addition, it poses the question: What do we do if we have a 3D and a 2D representation of the same geometry?
> >    Would it make sense to define a relation geo:has3DGeometry?
> 
> No, I would limit the creation of new relations (object properties) as much as possible (see [#219 (comment)](https://github.com/opengeospatial/ogc-geosparql/pull/219#issuecomment-973855057) for the reasoning behind it). Why are the properties `geo:coordinateDimension` and/or `geo:dimension` not sufficient for your use case? If they wouldn't be sufficient, we can also consider to add subclasses of `geo:Geometry` (e.g. `geo:3DGeometry`, `geo:2DGeometry`). This is less elegant compared to the existing GeoSPARQL dimension properties (might result in the need to assert multiple classes to an individual), but less impactful compared to adding new relations.

Good point, I did not think of the dimension properties. Then it is a matter of stating the query easily and a matter of availability of the dimension properties.

> 
> > 1. Also if two geometries are related to the geo:Feature, e.g. geo:hasDefaultGeometry relates to a 2D representation and geo:hasGeometry relates to a 3D representation, which value do we assign to a geo:hasBoundingBox relation attached to the feature representation? The 2D or the 3D bounding box?
> 
> I would say that a `geo:Feature` can have multiple geometry serializations, thus including multiple bounding boxes. In your example, you can assert the 2D BB, the 3D BB or both BB (or even multiple 2D BB and multiple 3D BB).

Agreed
> 
> > Suppose we assign two centroids and two boundingboxes to the feature. Do we need to relate them to the respective geometry somehow?
> 
> That's a nice proposal. It's also something we provided in the OMG ontology patterns ([omg:isDerivedFromGeometry](https://w3id.org/omg#isDerivedFromGeometry) links between 2 geometries, to describe the dependency). It's optional since a BB or centroid might also exist without knowing the geometry where it was derived from.

Seems we pushed that now to the GeoSPARQL 1.2 scope, but it is now on our list.

**Comment by nicholascar** [comment]
> …GeoSPARQL 1.2 scope…

It looks like the main focus of GeoSPARQL 1.2 will be detailed relationships between different Geometries and some Feature/Geometry relationships too, like roles etc.

Good to see a general area of interest emerging, rather than individual, wildly different, interests!
