### ISSUE TITLE
Need to add guidance for how to validate GeoSPARQL Shapes

### ISSUE THREAD

**Issue by jabhay** [opengeospatial/ogc-geosparql#230]
We have lots of instructions on RIF rules, but limited instruction on SHACL Shapes, and how to validate them.

Let's add this guidance.

**Comment by jabhay** [comment]
We need to instruct people on how to perform SHACL validation with and without reasoning, and with custom extensions to GeoSPARQL.

**Comment by nicholascar** [comment]
* add SHACL examples (pass/fail + return message) to examples Annex
* crosref with Shapes listing Annex
