### ISSUE TITLE
Provide examples of 3D Geometries

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#238]
We claim that 3D Geometries are fine but we have no examples!

**Comment by FransKnibbe** [comment]
Where do we make the claim? 

I think limitations on dimensionality are rather unclear at the moment. It is probably all specified in the SFA spec, which is one of the normative references.  This is what is says on dimension of geometry:

> The instantiable subclasses of Geometry defined in this Standard are restricted to 0, 1 and
> 2-dimensional geometric objects that exist in 2, 3 or 4-dimensional coordinate space (ℜ2, ℜ3 or ℜ4). Geometry
> values in R2 have points with coordinate values for x and y. Geometry values in R3 have points with coordinate
> values for x, y and z or for x, y and m. Geometry values in R4 have points with coordinate values for x, y, z and m.

So at most GeoSPARQL supports 2,5 D (only on z coordinate per x,y).

**Comment by nicholascar** [comment]
We make the claim whenever we have functions that calculate something to do with 3D, e.g. [`is3D`](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_function_geofis3d). 

Here is our functions summary table that lists 2D/3D handling: https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_b_1_functions_summary_table
