### ISSUE TITLE
List GML Classes vocabulary in 1.0 and 1.1 profiles

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#246]
A GML Geometry types vocabulary (<http://www.opengis.net/ont/gml>) was defined alongside GeoSPARQL 1.0 and it is referenced in the 1.0 and still also in the 1.1 Specification ([10.4.1. Geometry Class Hierarchy](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_geometry_class_hierarchy_2)) but it is not listed in the 1.0 or the 1.1 profile.

Also, the vocabulary has minimal ontology-level metadata.

**Comment by situx** [comment]
Correct, this is the GML class hierarchy. We also had a JSON-LD context for that until we decided to remove it. Do you propose to add metadata to the file and re-release it with GeoSPARQL 1.1?

**Comment by FransKnibbe** [comment]
Isn´t it a question of separation of concerns? In my mind, GML is just one of the serialisation formats for GeoSPARQL geometry. As such, the specifics of GML can be considered out of scope for GeoSPARQL. How GML is structured should be covered sufficiently by the referenced GML specification.

**Comment by situx** [comment]
I am not sure what lead to the definition of the GML ontology in the course of GeoSPARQL 1.0. @mperry455 maybe you could elaborate on this and whether we need to update it for GeoSPARQL 1.1?
