### ISSUE TITLE
Provide SF RDF examples

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#247]
SF & GML geometry classes are mentioned in the Spec ([10.4.1. Geometry Class Hierarchy](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_geometry_class_hierarchy_2)) and have snippets of definitional RDF but no Examples of SF or GML class uses are provided in Annex C.

This Issue is dependent on Issue #246 being addressed.

**Comment by jabhay** [comment]
As #246 has been moved to Proposed for GeoSPARQL 1.2, this issue now only relates to proving a Simple Features example.
