### ISSUE TITLE
Approval to publish journal article in MDPI

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#248]
Dear SWG,

@situx and I would like to publish the journal article we have drafted for the MDPI _International Journal of Geo-Information_'s [1] special edition entitled "Semantic Spatial Web" [2] which stems from the GeoLD workshop conference paper we published in July [3]. 

We believe we have consulted the SWG on this matter and have incorporated your various comments into the paper but since we have no public record of the SWG agreeing to this, please could you indicate your agreement, or not, with comments on this public Issue that can then be referenced?

Thanks.

[1] https://www.mdpi.com/journal/ijgi  
[2] https://www.mdpi.com/journal/ijgi/special_issues/Semantic_SpatialWeb  
[3] https://doi.org/10.20944/preprints202111.0179.v1

**Comment by jabhay** [comment]
I support publishing the journal article.

**Comment by chris-little** [comment]
I support publishing the journal article too.

**Comment by nicholascar** [comment]
I support my own proposition of course!

**Comment by situx** [comment]
I also support to publish the article I coauthored

**Comment by lvdbrink** [comment]
I support to publish the article!

**Comment by FransKnibbe** [comment]
I support publication.

**Comment by dvaranka** [comment]
I support publishing the journal article

**Comment by dr-shorthair** [comment]
OK from me

**Comment by nicholascar** [comment]
Thanks everyone, the article has passed review and been accepted for publication. I will put links to it here where it is finalised.

**Comment by situx** [comment]
The article has been published here: [doi.org/10.3390/IJGI11020117](https://doi.org/10.3390/IJGI11020117)

**Comment by situx** [comment]
The article has been published, so I am closing this issue here.
