### ISSUE TITLE
Should all DGGS support (functions) be in their own Conformance Classes?

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#256]
Non-topological query functions are split into 4 Conformance Classes:

1. SF Functions
2. Non-SF Functions
3. SF Functions - DGGS
4. Non-SF Functions - DGGS

The SF / non-SF split is not relevant to this discussion.

The traditional geometries/DGGS split is due to:

> The requirements to support non-topological query functions for DGGS geometry literals are separated from the requirements to support them for traditional geometry literals as it is expected that implementing these functions for DGGS literals will be significantly more difficult. This is due to the novelty of DGGS literals and thus the lack of existing software libraries for their manipulation. 

Should all GeoSPARQL functions support be split into traditional/DGGS Conformance Class pairs?

**Comment by situx** [comment]
Two arguments in favor of this proposal:
- It would simplify compliance benchmarking
- It would be straightforward if we assume the inclusion of further grid-based datatypes in the future

**Comment by FransKnibbe** [comment]
> Non-topological query functions are split into 4 Conformance Classes:

Where is that split made? In the specification I only see one conformance class for non-topological geometry functions: the Geometry Extension.
 
> Should all GeoSPARQL functions support be split into traditional/DGGS Conformance Class pairs?

Based on the assumption that DGGS objects can not be viewed as Geometries (see [issue 112](https://github.com/opengeospatial/ogc-geosparql/issues/112)) I think it makes sense to have a DGGS conformance class similar to the Geometry Extension.

**Comment by nicholascar** [comment]
OK, I'll make a PR to do this.

BUT: "Based on the assumption that DGGS objects can not be viewed as Geometries"

@FransKnibbe, we've discussed this and, for the purposes of GeoSPARQL 1.1 and perhaps even theoretically we've decided that they can be! 

For GeoSPARQL we've shown that they can operate as geometries regarding the GeoSPARQL functions, that they can represent the spatial footprints of Features and that we can convert from other geometry representations to and from DGGS 'geometries'. 

We've also made the case that the DGGS Cells unambiguous represent parts of a spatial surface, such as the Earth's, using a reference system - an ordinate one, not a coordinate one - but that all the aspects of a coordinate reference systems needed for spatial calculations and data representation are preserved.

I think it is therefore misleading, to readers of these issues, to say "DGGS objects can not be viewed as Geometries".

I think you keep going back to the fact that, because DGGS Cells represent an area, not a point, they can also be used as a sampling feature and indeed people do use them like this, but this doesn't take away from Cells making a perfectly fine geometries: they simple have more possibilities.

**Comment by FransKnibbe** [comment]
> @FransKnibbe, we've discussed this and, for the purposes of GeoSPARQL 1.1 and perhaps even theoretically we've decided that they can be!

@nicholascar, I am not convinced of that at all. But let's discuss that in [issue 112,](https://github.com/opengeospatial/ogc-geosparql/issues/112), otherwise the conversation gets too scattered.

**Comment by nicholascar** [comment]
> I think it makes sense to have a DGGS conformance class similar to the Geometry Extension.

I agree that this might be sensible to do: a whole DGGS Conformance Class.
