### ISSUE TITLE
No non-aggregate functions for concave hull and bounding circle

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#261]
Two new aggregate functions are meant to be included in GeoSPARQL 1.1, `geof:aggBoundingCircle` and `geof:aggConcaveHull`. These functions do not have non-aggregate counterparts. But wouldn't it make sense to have them too?

**Comment by nicholascar** [comment]
And a non-aggregate BoundingBox function

**Comment by nicholascar** [comment]
And create `BoundingBox` aliases for `envelope` and add explanatory notes
