### ISSUE TITLE
inconsistent naming of object properties

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#263]
Some object properties are named in such a way that they make linguistic sense: A contains B, A covers B. In those cases RDF triples form sentences that help humans to understand a statement. Other object properties don´t have this:

- `geo:ehOverlap` : Why not geo:ehOverlaps (like `geo:sfOverlaps`)?
- `geo:ehMeet`: Why not geo:ehMeets?
- `geo:ehDisjpint` Why not geo:ehDisjointFrom?

**Comment by jabhay** [comment]
These are named according to Simple Features standard. They certainly can't be done until a major release, as they would result in breaking changes.
