### ISSUE TITLE
translating ¨Feature¨ in Dutch and German

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#264]
One of the hardest things to translate in GeoSPARQL is the word ¨Feature¨. It is the type of word you see in models where there is a need for a very broad category, similar to words like _thing_, _object_ or _entity_. I guess the term _feature_ was picked by the OGC because in a certain sense of the word it implies geography, see [this Cambridge dictionary page](https://dictionary.cambridge.org/dictionary/english/feature). Probably the three meanings in English (a part of a face; an aspect of something; a geographic occurence) are related, in all cases it is about something that catches the eye.

The fact that geography is implied in the word _feature_ made it easy to use a broad definition of the class `Feature` in the GeoSPARQL ontology. Not only geographical things can be considered Features, but distinct spatial things too. A spoon or a tennis ball for example. However, the current German translation makes geography explicit:
`skos:prefLabel "Geografisches Merkmal"@de`
Can the German word _Merkmal_ imply geography, like one of the meanings of _feature_ in English? Or does it only mean a characteristic of something? Could _Geografisches_ be removed?

In Dutch I am struggling with finding a good translation. I am contemplating _voorkomen_ and _verschijnsel_, with a preference for the former, because it feels easier to accomodate both natural and artificial occurences.

Chances are that a similar word can be found in both Dutch and German.

**Comment by situx** [comment]
A "Merkmal" in German is more or less the same meaning as in English. Even in English, the word Feature is ambiguous if you think about machine learning features for example.
You may translate it as a characteristic of something.
While in German we use the word Merkmal if the context is clear, e.g. if we are writing about a Merkmal and the context of the text is about maps, the word Merkmal alone can mean many things in different contexts.
Because of this, I chose the term "geografisches Merkmal", i.e. geographic Feature to be more precise in what we mean. In English, I think if you want to be precise you would probably also emphasize a feature as "machine learning feature" if you refer to it in a machine learning context vs. "geographical feature" in a geo context.
Now the challenge here I think is that the context here is implicitly given because it is the GeoSPARQL ontology. Therefore it might make sense to only refer to it as Merkmal, but if you combine different definitions of Features together it may not be what you want as a description.
In any case it might make sense to do it consistently for all translations

**Comment by FransKnibbe** [comment]
@situx, assuming that in English the word _feature_ has five more or less distinct meanings (below), to which ones does _Merkmal_ translate?

1. A part of someone´s face
2. A characteristic or attribute of something
3. A geographical occurence
4. A full-lenght film
5. A newspaper article or broadcast item

In Dutch, _verschijnsel_ would only match the third meaning, _voorkomen_ would match the first and third meaning.

**Comment by situx** [comment]
Merkmal, in general, translates to point 2, but is also used in the context of points 1 and 3, either as a compound word, with a descriptive adjective or if the context of the text is clear then also as the standalone word Merkmal

**Comment by FransKnibbe** [comment]
> Merkmal, in general, translates to point 2, but is also used in the context of points 1 and 3, either as a compound word, with a descriptive adjective or if the context of the text is clear then also as the standalone word Merkmal

Thanks. I was asking because _Merkmal_ seems very similar to the Dutch wordt _kenmerk_, which literally means a mark by which something can be known. So in Dutch only the second translation applies.

So yes, _räumliches Merkmal_ looks good then. Could the skos:note also be changed to remove the limitation to geography?

I think I will start with _voorkomen_ as the Dutch translation, which is probably similar to _Vorkommen_ in German.

**Comment by lvdbrink** [comment]
My 2 cents... 

In the Dutch standard NEN 3610, which defines a base model for geo-information, the term 'geo-object' is used and it is stated that the English translation is 'geographic feature'. 

The definition of 'geo-object': 
> een fenomeen in de werkelijkheid, dat direct of indirect is geassocieerd met een locatie relatief ten opzichte van de aarde
> a phenomena in reality that is directly or indirectly associated with a location relative to the earth

Maybe the term 'geo-object' could be used as the Dutch translation of Feature. It is already a well-known term in Dutch geospatial data models, and standardized.

**Comment by FransKnibbe** [comment]
> Maybe the term 'geo-object' could be used as the Dutch translation of Feature

Here the problem too is the _geo_ part. The current definition of `Feature` is not exclusive to geography. I think that is a good thing. If the geo prefix is removed, then we are left with _object_ or _ruimtelijk object_, which is already the name for Feature´s parent class.

**Comment by lvdbrink** [comment]
I guess, but then we are left with the problem that there is not really a Dutch word that covers the definition of `Feature`. The term _Voorkomen_ is often used to indicate an instance or individual of a class... 

Alternatively, perhaps we could use _Fenomeen_?

**Comment by FransKnibbe** [comment]
> The term _Voorkomen_ is often used to indicate an instance or individual of a class...

Ah, I did not know that. It complicates matters.

> Alternatively, perhaps we could use _Fenomeen_?

Let´s do that, until something better comes along. Anyway, we have to live with the fact that a class name can´t be expected to fully explain the intention of a class. People have to refer to the class definition for that.

**Comment by lvdbrink** [comment]
Agreed!

**Comment by dr-shorthair** [comment]
> Here the problem too is the geo part. The current definition of Feature is not exclusive to geography. 

Indeed. This is a technical debt to the people who originally conceived ISO 19101, 19109 etc. We either have to live with that, else attack the top level of ISO 19109.

**Comment by jabhay** [comment]
Remaining tasks for this issue:
- [ ] Change German translation of Feature from Geographical Feature to Spatial Feature.
