### ISSUE TITLE
geo:ehEquals equals geo:rcc8eq

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#267]
Other than the name (IRI) there seems to be no difference between properties `ehEquals` and `rcc8eq`. Shall we make this official by using `owl:sameAs` to link the two?

**Comment by dr-shorthair** [comment]
Else `owl:equivalentProperty` - more explicit

**Comment by FransKnibbe** [comment]
While translating to Dutch (working from top to bottom) I just came across the simple features topological relationships. It has an equals relation too, And possible other properties can be declared equivalent as well. I will update [PR 268](https://github.com/opengeospatial/ogc-geosparql/pull/268).
