### ISSUE TITLE
geo:spatialDimension confusion: does GeoSPARQL support linear referencing?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#269]
GeoSPARQL has two similar properties for indicating the number of coordinates in Geometry points:
```
:coordinateDimension
	a rdf:Property, owl:DatatypeProperty ;
	rdfs:domain :Geometry ;
	rdfs:range xsd:integer ;
	skos:definition """The number of measurements or axes needed to describe the position of this Geometry in a coordinate system."""@en ;
```

and

```
:spatialDimension
	a rdf:Property, owl:DatatypeProperty ;
	rdfs:domain :Geometry ;
	rdfs:range xsd:integer ;
	skos:definition """The number of measurements or axes needed to describe the spatial position of this Geometry in  a coordinate system."""@en ;
```

Please note that the ontology definitions are very similar. Only the specification document offers a way to distinguish the two:

> The property geo:spatialDimension is defined to link a Geometry object to the dimension of the spatial portion of the direct positions (coordinate tuples) used in its serializations. If the direct positions do not carry a measure coordinate, this will be equal to the coordinate dimension.

This leads to questions that deserve some more clarity in GeoSPARQL:

1. Are linear referencing measures to be viewed as representing an extra (spatial) dimension? 
2. Does GeoSPARQL support linear referencing? And should, by extension, implementations of GeoSPARQL be able to handle Geometries with measure coordinates?
3. If GeoSPARQL does not support linear referencing, then why does the property `geo:spatialDimension` exist?

Also, it seems to me that the ontology definitions should be made better at explaining the difference between the two properties.

**Comment by jabhay** [comment]
Tasks that resolve this issue:
- [x] Determine whether we support linear referencing - Not currently.
- [ ] Record some information information in the standard to explain this.

**Comment by FransKnibbe** [comment]
The explanation needed should be part of the resolution of [issue 278](https://github.com/opengeospatial/ogc-geosparql/issues/278).
