### ISSUE TITLE
Clarification needed for SFA Geometry class

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#270]
While translating the English texts in the [Simple Features Vocabulary](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/sf_geometries.ttl) I came across a bit of text that I do not understand. This is part of the explanation of the `Geometry` class (in both the SFA document and the vocabulary):

> All Geometry classes described in this standard are defined so that instances of Geometry are topologically
> closed, i.e. all represented geometries include their boundary as point sets. This does not affect their
> representation, and open version of the same classes may be used in other circumstances, such as topological
> representations.

It is the second sentence that I do not understand. The part "and open version of the same classes" looks grammatically incorrect to me. Probably it should read "open versions". 

I understand representations to mean encodings like WKT and WKB. So how does Geometry instances being topologically closed not effect their representations? 

And how could an open version of a geometry class be used in topological representations?

**Comment by jabhay** [comment]
- [ ] @jabhay to reach out to a Simple Features guru to condense this sentence in the doc, and then to reach out to @situx to ensure his points are made by the resulting sentence/para.

**Comment by jabhay** [comment]
@pvretano , could you take a look at the quoted text above and provide some guidance for us?

**Comment by jabhay** [comment]
Pull request added.

**Comment by jabhay** [comment]
For this release, I've simply fixed the typo. The underlying issue can now be moved out of the 1.1 release and referred to the authors of Simple Features.
