### ISSUE TITLE
Replace SRS with CRS, where appropriate

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#272]
The GeoSPARQL document seems to regard Spatial Reference System (SRS) as a synonym of Coordinate Reference System (CRS). For example, here is the definition of `geof:buffer`:

> Returns a geometric object that represents all Points whose distance from geom1 is less than or equal to the radius measured in units. Calculations are in the spatial reference system of geom1.

I think it would be good to change this kind of occurrence of "spatial reference system" to "Coordinate Reference System", at least in the cases where it applies to Geometry, because that is the intended meaning.

**Comment by situx** [comment]
I get your point, but I do not see it as something that needs to be changed.
My interpretation is that a spatial reference system is a broader specification than a coordinate reference system.
In the future, we might have GeoCoding Literals as input of buffer which might not have a coordinate reference system but rather a spatial reference system.
So following that definition I see no problem leaving it as spatial reference system

**Comment by FransKnibbe** [comment]
Hi @situx, I have updated the issue a bit, to make clear that SRS can be changed to CRS only in cases where is applies to geometry.
You are right that SRS is broader than CRS. It is strange and misleading to use the broader term when only the narrower term applies. And it is very likely that the original authors intended to indicate CRS rather than SRS. The concepts have historically been confused, also in OGC documents.

**Comment by FransKnibbe** [comment]
Is it OK to change requirement IRIs too? Or does that break backwards compatibility?
For example, in the IRI below "srs" could be changed to "crs"
http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-literal-default-srs

**Comment by situx** [comment]
@FransKnibbe Requirement IRIs have never been resolvable but have been defined in the original spec document. So in my opinion we cannot change them without breaking backward compatibility.
