### ISSUE TITLE
Fix profile and vocabulary HTML documentation software

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#276]
[pyLODE](https://pypi.org/project/pyLODE/) is used to build HTML versions of many GeoSPARQL resources however the recent version of it doesn't support profile and vocabulary resources.

Either we must version lock on v2.5.13 of pyLODE or wait for v 3.x updates for profiles and vocabularies.

**Comment by FransKnibbe** [comment]
Does locking on to 2.5.13 have any negative effects?

**Comment by nicholascar** [comment]
No: that was the version that was running until just the other day - before v3.0.1 was released. I've locked it now and its working fine for most assets (seems I found an unsubscribed bug in 2.x along the way...).

So I'll close this for now as it is locked.
