### ISSUE TITLE
Explain relationship between GeoSPARQL and SFA

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#278]
A paragraph should be added to the specification document, in which the relationship between the GeoSPARQL and SFA specifications are explained. Things that could be mentioned are:

- GeoSPARQL is based on SFA, but there is no complete overlap
- Simple Features is not about Features, but about Geometry
- SFA does not support 3D geometry (only 2,5 D) and neither does GeoSPARQL 1.1
- GeoSPARQL 1.1 does not support Linear Referencing
- support of SF types by the various Geometry serialisations (see[ issue 202](https://github.com/opengeospatial/ogc-geosparql/issues/202))

**Comment by FransKnibbe** [comment]
Resolving this issue should resolve [issue 269](https://github.com/opengeospatial/ogc-geosparql/issues/269).

**Comment by FransKnibbe** [comment]
Resolving this issue should also close [issue 277](https://github.com/opengeospatial/ogc-geosparql/issues/277).

**Comment by FransKnibbe** [comment]
Another linked issue: [issue 238](https://github.com/opengeospatial/ogc-geosparql/issues/238).

**Comment by FransKnibbe** [comment]
I would like [issue 285](https://github.com/opengeospatial/ogc-geosparql/issues/285) to be resolved before continuing with this issue.

**Comment by FransKnibbe** [comment]
Issue 285 is revolved now, but I ran into another problem. I want to explain how Z-coordinates are handled in GeoSPARQL geometry functions. SFA-CA has the following to say about that:

> "Spatial operations work in the "map geometry" of the data and will therefore not reflect z or m values in
> calculations (e.g., Equals, Length) or in generation of new geometry values (e.g., Buffer, ConvexHull, Intersection).
> This is done by projecting the geometric objects onto the horizontal plane to obtain a "footprint" or "shadow" of the
> objects for the purposed of map calculations. In other words, it is possible to store and obtain z (and m)
> coordinate values but they are ignored in all other operations which are based on map geometries."

Does this mean that a Geometry that is the result of a buffer operation (for example) in GeoSPARQL has all its Z-coordinates set to 0?

**Comment by jabhay** [comment]
- [ ] Create a new issue relating to the Z-coordinate question above.
- [ ] Create pull request for the simple features request work already in train.
