### ISSUE TITLE
Axis order requirement for GML?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#280]
GeoSPARQL has a requirement for WKT to use the correct axis order: http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-axis-order
Why isn´t there a similar requirement for GML?

**Comment by situx** [comment]
I reckon that there is a requirement for WKT because WKT Literals use an extended WKT with as CRS specification in GeoSPARQL 1.0.
GML probably does not need that because the format specification already includes a CRS definition and how to treat this definition.

**Comment by FransKnibbe** [comment]
> I reckon that there is a requirement for WKT because WKT Literals use an extended WKT with a CRS specification in GeoSPARQL 1.0.
> GML probably does not need that because the format specification already includes a CRS definition and how to treat this definition.

That might have something to do with it. Both GML and GeoSPARQL WKT use a CRS IRI for Geometry instances, but a reference to the CRS is not part of the original WKT spec. But how does that make a CRS IRI that it is part of a GeoSPARQL WKT literal more suspect? In GML geometries  coordinates could not match CRS axis order just as well. 

And if there is a need to check whether the coordinates match the CRS definition for GeoSPARQL WKT, why only check axis order and not something else like valid coordinate range?

**Comment by jabhay** [comment]
The reason for this is that GML specifies the axis order must match the CRS, but WKT is underspecified in this regard - hence we've stated a requirement for correct axis order in GeoSPARQL. @FransKnibbe , could you please check the GML standard for this requirement, and close this issue if there.

**Comment by lvdbrink** [comment]
@FransKnibbe I found this in the GML 3.2.1 spec paragraph 12.4.3.1:
> The coordinate values in a coordinate tuple shall be recorded in the order in which the coordinate system axes associations are recorded.

**Comment by FransKnibbe** [comment]
Thanks @lvdbrink. That settles it, the case can be closed.
