### ISSUE TITLE
Relationship between GeoSPARQL and ISO-19107

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#285]
I am trying to resolve [issue 278 ](https://github.com/opengeospatial/ogc-geosparql/issues/278) by adding an explanation of the relationship between GeoSPARQL and [SFA-CA](https://portal.ogc.org/files/?artifact_id=25355). Currently, GeoSPARQL states it is based on both SFA-CA and ISO-19107.

I wonder which parts of GeoSPARQL are based exclusively on ISO-19107. I can find a reference to `GM_Object`, which is defined in ISO-19107. But couldn't we just as well say that GeoSPARQL Geometry is based on the class `Geometry` as defined in SFA-CA? And if that is the case, couldn't we simplify things by saying that GeoSPARQL is bases on SFA-CA and leave ISO-19107 out entirely?

As far as I can tell, ISO-1907 is not a freely accessible standard, so that could count as another reason to leave it out.

**Comment by situx** [comment]
I believe only @mperry455 might be able to answer this fully but I believe the reference is about the definitions of this class GM_Object only.  If there is an equivalent in SFA I have no objections to removing the ISO reference unless I overlook something else

**Comment by mperry455** [comment]
Right it is a reference to GM_Object only.

**Comment by FransKnibbe** [comment]
Discussion at the teleconference on 2022-02-23 led to the decision to leave ISO-19107 out of the documentation for GeoSPARQL 1.1

**Comment by dr-shorthair** [comment]
Was Matt in the meeting? His colleague John Herring might have an opinion ...

**Comment by FransKnibbe** [comment]
Yes, Matt was present. John Herring had retired, so he is np longer available for consultation. Which is unfortunate for [issue 270](https://github.com/opengeospatial/ogc-geosparql/issues/270), because John authored SFA-CA. I hope another expert can be found.

**Comment by dr-shorthair** [comment]
I had not heard about that. 
And I just looked in the OGC portal and see that he is no longer listed under the Oracle USA tab. 
That is an epochal change ...
