### ISSUE TITLE
add metric versions of geof:buffer and geof:distance

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#286]
GeoSPARQL has two functions that allow any distance unit (referenced by any IRI) to be used: `geof:buffer` and `geof:distance`. Metric equivalents of those functions can be made to simplify implementation and use. Those variants will have no argument for units, but assume distances in metres.

**Comment by situx** [comment]
I believe we discussed this and all that is missing is a pull request for this from you, correct @FransKnibbe ?

**Comment by FransKnibbe** [comment]
> I believe we discussed this and all that is missing is a pull request for this from you, correct @FransKnibbe ?

Yes. I made this issue to record that this is something that needs to be done.
