### ISSUE TITLE
Corrections of example data and queries

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogc-geosparql#29]
**Official change request**: [OGC CR 173](http://ogc.standardstracker.org/show_request.cgi?id=173)

Errors in example data and queries might lead to wrong implementations. In the given example data in B.1. (page 51) the LineString start with (( and ends with )), although it must be single brackets.

In the third example query in B.2 (page 52) the subject of the fifth triple pattern is a variable called ?my:D although is should be no variable (my:D).

In the fourth example query in B.2 (page 54) the URL given in the prefix definition for geof is wrong. Instead of < 0 > it must be < 1 >

**Comment by jabhay** [comment]
Created MoSCoW poll

[![](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Must)](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Must/vote)
[![](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Should)](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Should/vote)
[![](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Could)](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Could/vote)
[![](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Won%27t)](https://api.gh-polls.com/poll/01EJS906Z7M4GBEEXVM2Y343GV/Won%27t/vote)

**Comment by mathib** [comment]
I believe the transformed query of the example B.3 (p54-55) also contains an error: the final UNION (geometry-geometry) should be:

```
UNION
{ # geometry – geometry
?f geo:asWKT ?fSerial .
my:A geo:asWKT ?aSerial .
FILTER (geof:sfOverlaps(?fSerial, ?aSerial)) }
```
