### ISSUE TITLE
Add explicit support for Bounding-Box in GeoSPARQL

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#3]
See https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/issues/9
and https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/pull/10

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Must)](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Should)](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Could)](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Won%27t)](https://api.gh-polls.com/poll/01EJXBMRP88SGPTQ1ZG39DTKJ8/Won%27t/vote)

**Comment by nicholascar** [comment]
I propose that this will be addressed by a new `Geometry` class property : `role`.

BoundingBox and Centroid and ConvexHull and others are _roles_ that the geometry plays, not geometry types so I suggest this is orthogonal to type/resolution/dimension etc. and that deserve an independent property.

**Comment by FransKnibbe** [comment]
> BoundingBox and Centroid and ConvexHull and others are roles that the geometry plays, not geometry types

I beg to differ. I see a role has a changeable characteristic. For example, a person can have the role of user, system administrator or moderator. If a geometry is a centroid or a convex hull (of another geometry), this is fixed. Moreover, there is alway a direct relationship between a geometry and derived simplifications of that geometry (e.g. its centroid or bounding box). So I feel the best way to model geometries like bounding box and centroid is to let them be specialisations (subclasses) of general geometry. For each of those subclasses we can define what is to be expected (e.g. a centroid is always a point, a bounding box is a rectangle or rectangular cuboid). And a geometry property can be used to link a geometry to its derived shape (e.g. hasCentroid, hasBBox). That way a bounding box geometry can also have a related centroid.

**Comment by nicholascar** [comment]
Now done, see https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geohasboundingbox

**Comment by jabhay** [comment]
This was done as part of the 1.1 update.

Adding roles for geometries has been shifted into #241 and moved to proposed for 1.2.
