### ISSUE TITLE
GeoSPARQL Schema v1.0.1: hasDefaultGeometry

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogc-geosparql#30]
**Official change request**: [OGC CR 548](http://ogc.standardstracker.org/show_request.cgi?id=548)

There is a mismatch between the published GeoSPARQL standard v1.0 (11-052r4) and the schema v1.0.1 ( 0 ).

On 8.3.12, page 13, of the standard is defined the property `hasDefaultGeometry`.
The schema defines the property instead as `defaultGeometry` but with an otherwise equivalent definition. The schema does not contain a `hadDefaultGeometry` property.

This mismatch prevents RDFS and OWL inferencing being performed correctly on a dataset written to comply with the standard.

Please can the schema be updated and new version issued.

**Comment by jabhay** [comment]
Created MoSCoW poll

[![](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Must)](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Must/vote)
[![](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Should)](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Should/vote)
[![](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Could)](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Could/vote)
[![](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Won%27t)](https://api.gh-polls.com/poll/01EJS8ZN7FDD5TFX7SVE5KTMN0/Won%27t/vote)

**Comment by situx** [comment]
I believe we have solved this issue by adding both properties in GeoSPARQL 1.1. I do not think an update of the schema for GeoSPARQL 1.0 is possible. Is that correct @jabhay and we can close this issue here?
