### ISSUE TITLE
Possible inconsistency in the definition of geo:Feature

### ISSUE THREAD

**Issue by andrea-perego** [opengeospatial/ogc-geosparql#314]
In [§6.2. (Classes)](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_classes) of the current version of the GeoSPARQL 1.1 specification, class `geo:Feature` is said to be equivalent to the `Feature` class of ISO 19109:

> Two main classes are defined: [`geo:SpatialObject`](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geospatialobject) and [`geo:Feature`](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geofeature). The class [`geo:Feature`](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geofeature) is equivalent to the UML class `Feature` defined in [[ISO19109]](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#ISO19109).

However, [§6.2.2. (Class: geo:Feature)](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geofeature) states:

> The class [`geo:Feature`](http://www.opengis.net/ont/geosparql#Feature) is equivalent to the class `GFI_Feature` [[ISO19156]](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#ISO19156) [...]

Is this intentional?

BTW, [the bibliographic reference to ISO 19109](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#ISO19109) is about ISO 19109:2005 (withdrawn) instead of ISO 19109:2015.

**Comment by FransKnibbe** [comment]
This issue related to [issue 319](https://github.com/opengeospatial/ogc-geosparql/issues/319). Updating the specification to mirror the ontology would solve the problem.

**Comment by andrea-perego** [comment]
@FransKnibbe , @situx , @jabhay , I may be mistaken, but it doesn't seem that this possible inconsistency has been fixed via PR https://github.com/opengeospatial/ogc-geosparql/pull/345 .

As far as I can see, what was revised is the `skos:definition`, but not the introductory text in [§6.2. (Classes)](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_classes) & [§6.2.2. (Class: geo:Feature)](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geofeature) quoted in my original comment https://github.com/opengeospatial/ogc-geosparql/issues/314#issue-1196511761 .

**Comment by lvdbrink** [comment]
As Andrea pointed out, this seems no to be fixed in the spec chapter 6. This still reads: 

> The class `geo:Feature` is equivalent to the UML class Feature defined in ISO19109.

As well as 

> The class `geo:Feature` is equivalent to the class `GFI_Feature` [ISO19156] and is defined by the following:
