### ISSUE TITLE
Update BFO Mapping to use BFO2020

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#315]
https://github.com/BFO-ontology/BFO-2020/tree/21838-2/21838-2/common-logic

OWL file: https://github.com/BFO-ontology/BFO-2020/blob/21838-2/21838-2/owl/bfo-2020.owl

Other resources:

http://military-ontology.org/basic-formal-ontology

**Comment by situx** [comment]
This one is closed by #320
