### ISSUE TITLE
GeoSPARQL to DCTERMS mapping

### ISSUE THREAD

**Issue by andrea-perego** [opengeospatial/ogc-geosparql#316]
In the current GeoSPARQL 1.1 draft ([§E.9](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_e_9_dcmi_metadata_terms_dcterms)), there is a discussion on how to map [`dcterms:coverage`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/coverage).

I would suggest replacing it with its more relevant subproperty, namely, [`dcterms:spatial`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/spatial), and revise the first sentence as follows:

> The range of `dcterms:spatial` includes a `dcterms:Location`, so it is a property for indicating a `geo:Feature`, not a `geo:Geometry` and for which GeoSPARQL has no equivalent.

About the sentence:

> Often, `dcterms:coverage` is used to indicate a spatial extent such as a bounding box. 

This is not completely correct. What is used for this purpose is usually [`dc:coverage`, i.e., the original term from the Dublin Core Metadata Element Set](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/elements/1.1/coverage), whose value is a literal. Instead, `dcterms:coverage`, as well as its subproperty `dcterms:spatial`, are meant to be used as object properties. 

An example of its use is included in the _Dublin Core Guide on Publishing Metadata_ - quoting from [the relevant section](https://www.dublincore.org/resources/userguide/publishing_metadata/#dcterms:spatial):

> dcterms:spatial has a range of the class dcterms:Location. All values used with dcterms:spatial have to be instances of this class. Therefore the property must only be used with non-literal values.
>
> ````turtle
> ex:myData dcterms:title "Analysis of rocks collected in Perth" ;
>           dcterms:spatial _:thisPlace .
> _:thisPlace ex:east "115.85717" ;
> ex:north "-31.95301" ;
> ex:name "Perth, W. A." .
> ````

**Comment by nicholascar** [comment]
Updated via PR #363 

![image](https://user-images.githubusercontent.com/7321872/180118386-00ccd24a-80e6-474c-a515-c360d1ed6371.png)

**Comment by dr-shorthair** [comment]
OK. A case could be made for `dcterms:Location owl:equivalentClass geo:SpatialObject .` 
But DC is not strongly axiomatized, so probably no harm done either way.
