### ISSUE TITLE
Spec/Ont class definitions are inconsistent

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#319]
`geo:Feature` is [defined in our Specification document](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geofeature) as:

> This class represents the top-level feature type. This class is equivalent to GFI_Feature defined in ISO 19156, and it is superclass of all feature types.

However, [in our ontology it is defined](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl#L953) as:

> A discrete spatial phenomenon in a universe of discourse.

With a `skos:note` property of:

> A Feature represents a uniquely identifiable phenomenon, for example a river or an apple. While such phenomena (and therefore the Features used to represent them) are bounded, their boundaries may be crisp (e.g., the declared boundaries of a state), vague (e.g., the delineation of a valley versus its neighboring mountains), and change with time (e.g., a storm front). While discrete in nature, Features may be created from continuous observations, such as an isochrone that determines the region that can be reached by ambulance within 5 minutes.

There are similar discrepancies for `geo:Geometry`, `geo:FeatureCollection` & `geo:GeometryCollection`, i.e. _all_ of the classes GeosPARQL defines.

We need to resolve these discrepancies with urgency.

I propose the following:

* [ ] itemise and compare all class & property definitions in Ont & Spec in this Issue
* [ ] vote on the appropriate ones to keep in both
* [ ] move statements of definitional source, like "This class is equivalent to GFI_Feature defined in ISO 19156..." to a property other than `skos:definition`, e.g. `skos:note` or `dcterms:provenance` (but not `rdfs:comment` or `dcterms:description` as some systems will take these to be definitions)

**Comment by nicholascar** [comment]
**Object** | **Specification** | **Ontology**
--- | --- | ---
**Classes** ||
`geo:SpatialObject` | The class Spatial Object represents everything that can have a spatial representation. It is superclass of feature and geometry | Anything spatial (having or being a shape, position or an extent).
`geo:Feature` | This class represents the top-level feature type. This class is equivalent to GFI_Feature defined in ISO 19156, and it is superclass of all feature types. | A discrete spatial phenomenon in a universe of discourse. 
`geo:Geometry` | The class represents the top-level geometry type. This class is equivalent to the UML class GM_Object defined in ISO 19107, and it is superclass of all geometry types. | A coherent set of direct positions in Euclidian space. A direct position holds the coordinates for a position within a Coordinate Reference System (CRS).
`geo:SpatialObjectCollection` | The class Spatial Object Collection represents any collection of individual Spatial Objects. It is superclass of Feature Collection and Geometry Collection. | Any collection of individual Spatial Objects. It is superclass of Feature Collection and Geometry Collection.
`geo:FeatureCollection` | The class Feature Collection represents any collection of individual Features. | Any collection of individual Features.
`geo:GeometryCollection` | The class Geometry Collection represents any collection of individual Geometries. | Any collection of individual Geometries.
**Properties** ||
|||
|||

_incomplete_

**Comment by FransKnibbe** [comment]
The ontology definitions have been updated during work on version 1.1 (see [PR 134](https://github.com/opengeospatial/ogc-geosparql/pull/134)) It seems the improved definitions have not been replicated to the documentation yet. As far as I can tell, that is the thing left to do.

**Comment by nicholascar** [comment]
Our original definitions, still in the Specification, reference ISO19156 and, for _feature_, 19156 says:

> abstraction of real-world phenomena

and cites ISO 19101:2002 as the source. 

19101 says:

> abstraction of real world phenomena

(same except for the hyphen!)

So I suggest using that definition. There is a NOTE in 19156 & 19101: "A feature may occur as a type or an instance. In this International Standard, feature instance is meant unless otherwise specified.". GeoSPARQL never mentiones feature types, so I suggest that we include an altered version of that NOTE in our Feature definition too.

For Geometry, 19107 which we reference says:

> **geometric object** <geometry> spatial object representing a geometric set

> (for geometric set) set of points

So 

> **geometric object** spatial object representing a set of points

No definition is given directly for points, just the note that "The vertices in a line string are data points"

> **geometric primitive** <geometry> geometric object representing a single, connected, homogeneous (isotropic) element of space

So 19107 thinks that geometries, when realised as primitives, like WKT or DGGS, are "geometric object[s] representing ...[an] element of space"

So why are we narrowing our Geometry definition with phrases such as "direct positions in Euclidian space"? What causes us to specify such restrictions on geometry when the standard from which we derive doesn't?

I see that @situx and I [approved the PR that set this definition](https://github.com/opengeospatial/ogc-geosparql/pull/134/files#diff-f24eb6f741d5bb68946ed89bbcda26fd62cfa1105cc46158df7b1d4e8953042bR581) but, on reflection, I don't think I agree with it. I understand the desire to be as specific as possible with our definitions to assist people in getting to work easily but this definition prevents non-Euclidian geometries, if people wanted to use them, and many other things, I think needlessly.

**Comment by situx** [comment]
If we contradict the spec with the definitions we have chosen in the ontology files, we should definitely revert to the spec. I was under the impression that we just making more precise but equivalent statements in the ontology files.
Concerning the Euclidian space statement, I think the reasoning is as follows:
- GeoSPARQL only provides functions to deal with 2D and 3D geometries in Euclidean space, hence the definition was put there for clarification

But I would agree with Nick, that we do not have to narrow down the definition of Geometry just because we do not provide functions to handle other geometry types yet

**Comment by FransKnibbe** [comment]
> So why are we narrowing our Geometry definition with phrases such as "direct positions in Euclidian space"? What causes us to specify such restrictions on geometry when the standard from which we derive doesn't?
> 
> I see that @situx and I [approved the PR that set this definition](https://github.com/opengeospatial/ogc-geosparql/pull/134/files#diff-f24eb6f741d5bb68946ed89bbcda26fd62cfa1105cc46158df7b1d4e8953042bR581) but, on reflection, I don't think I agree with it. I understand the desire to be as specific as possible with our definitions to assist people in getting to work easily but this definition prevents non-Euclidian geometries, if people wanted to use them, and many other things, I think needlessly.

A major problem with the old definitions was that they were not clear and referenced ISO standards. The concepts were probably clear to people with a GIS background, who are  already familiar with the concepts. But a major audience for GeoSPARQL are people with a (semantic) web background. Especially for them definitions were improved. 

That geometry is considered Euclidean reflects the fact that all OGC standards assume geometry to be Euclidean (as far as I can tell). For a broader audience, and for the ability to apply reasoning to data, it is good to be as specific as possible.

**Comment by jabhay** [comment]
Once complete, check https://github.com/opengeospatial/ogc-geosparql/issues/314 - as it raises the geoFeature inconsistency.
