### ISSUE TITLE
Extend expressive power of ontology for encountered use cases

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogc-geosparql#32]
**Official change request**: [OGC CR 590](http://ogc.standardstracker.org/show_request.cgi?id=590)

We   request an extension to the GeoSPARQL OWL ontology that includes details it   doesn't cater for such as indicating spatial resolution, areas, proportional   relations (e.g. area overlaps) and roles for multiple Geometry objects   relating to a single Feature.

This   extension is mostly built on GeoSPARQL but it also uses elements from QUDT   and the some supporting datatype vocabularies.

The   extensions to GeoSPARQL that we have found necessary have been crystallised   in an ontology which it presented online [here](https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/).

**Comment by jabhay** [comment]
Created MoSCoW poll

/polls Must Should Could "Won't"

**Comment by jabhay** [comment]
Created MoSCoW poll

/polls "Must" "Should" "Could" "Won't"

**Comment by jabhay** [comment]
Duplicate of #9
