### ISSUE TITLE
Additional GeoSPARQL requirements from Loc-I project

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#33]
We have been adding features to a 'GeoSPARQL Extensions' ontology that are required for a significant deployment in Australia. See https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont 

This includes 
- predicates for length, area, volume
- predicate for centroid
- inverse property for `geo:hasGeometry`
- explicit link to CRS description
- predicates for spatial resolution

**Comment by jabhay** [comment]
Created MoSCoW poll

[![](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Must)](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Must/vote)
[![](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Should)](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Should/vote)
[![](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Could)](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Could/vote)
[![](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Won%27t)](https://api.gh-polls.com/poll/01EJS8YG9DVJPWYW450KV3X8T6/Won%27t/vote)

**Comment by dr-shorthair** [comment]
Yikes - never saw a moscow poll before. Accidently voted. Didn't understand what I was clicking.

**Comment by FransKnibbe** [comment]
@dr-shorthair: I hope you didn't torpedo your own proposal. Anyway, I voted M. I do wonder if anyone can see who voted for what.

**Comment by nicholascar** [comment]
The proper location for the GeoSPARQL extensions ontology is <https://linked.data.gov.au/def/geox>

**Comment by nicholascar** [comment]
GEOX defines the following:

- Classes
    - _Bounding box_  - a `subClassOf` `geo:Geometry`
    - _Spatial measure_ - a `subClassOf` a _Qualitative Measure_ class which defines a data value, units and uncertainty properties

- Object Properties
    - has area
    - has area in m2
    - has bounding box - specialization of `geo:hasGeometry`
    - has centroid - specialization of `geo:hasGeometry`
    - has length
    - has length in m
    - has spatial resolution
    - has spatial resolution in metres
    - has volume
    - has volume in m3
    - In Coordinate Reference System
    - is geometry of
    - transitiveSfOverlap

- Datatype Properties
    - asDGGS 
    - lower-left 
    - upper-right 

Following the agreed procedure of non-controversial changes for GeoSPARQL 1.1 and more complex changes for 1.2, truly radical changes for 2.0, I propose the following additions to GeoSPARQL from GEOX for 1.1:

- Object Properties
    - In Coordinate Reference System

This property is much requested and stand-alone, i.e. inclusion of it in GeoSPARQL won't necessitate the inclusion of any other classes or properties. Unlike in GEOX, I think this property is needed for the indication of a Geometry's CRS, not just for the indication of the CRS used when making a measurement (e.g. area) therefore the domain should be either `geo:Geometry` , with the possibility of extension as needed in 1.2+, or empty.

For the following:

- Object Properties
    - has area
    - has length
    - has volume

I recommend that we include these properties or equivalents in GeoSPARQL and the necessary supporting class for them which is `SpatialMeasure` (their range value type). 

In GOEX, examples of the use of `SpatialMeasure` look like this:

```
my:swimmingPool99
  :hasVolume [
    data:unit <http://qudt.org/vocab/unit/M3> ;
    data:value 3050.0 ;
  ] ;
.
``` 
I propose we include all necessary ontology elements within GeoSPARQL for use of `SpatialMeasure` too, so this will necessitate equivalents of `data:unit` & `data:unit`. We might consider QUDT `unit` & `value` also.

_more to come..._

**Comment by dr-shorthair** [comment]
Yikes - I had missed this discussion. The subsumption hierarchy is clearly wrong, and the domain/range axioms questionable. 

- `inCRS` is clearly needed on geometry
- some spatial measures (length, area, volume) are sensitive to CRS. But spatial-measure is a scaled number, so associating it with a CRS is a bit more tricky.

**Comment by nicholascar** [comment]
The class hierarchy as focussed above is not implemented in the Ont or Spec now: SpatialMeasure is not subclass of anything currently and, as per GeoSPARQL 1.0, Feature and Geometry remain subclasses of SpatialObject.

**Comment by FransKnibbe** [comment]
> The class hierarchy as focussed above is not implemented in the Ont or Spec now: SpatialMeasure is not subclass of anything currently and, as per GeoSPARQL 1.0, Feature and Geometry remain subclasses of SpatialObject.

@nicholascar: Shouldn't `SpatialMeasure` be a subclass of `SpatialObject`?

**Comment by FransKnibbe** [comment]
> @nicholascar: Shouldn't `SpatialMeasure` be a subclass of `SpatialObject`?

On second thought, I think that does not make sense. GeoSPARQL defines topologic relationships between `SpatialObject`s. I don't think topologic relationships can be applied to sizes of things.

Would it help to relate `SpatialMeasure` terms like [qudt:Quantity](http://qudt.org/schema/qudt/Quantity), [schema:Quantity](https://schema.org/Quantity) or [uom:Quantity](http://www.ontology-of-units-of-measure.org/resource/om-2/Quantity)?

**Comment by dr-shorthair** [comment]
All sensible requirements have been included.
