### ISSUE TITLE
Definition of GeoSPARQL subparts

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#342]
In the GeoLD workshop, people mentioned that supporting GeoSPARQL as a whole is not necessarily something all software companies will consider implementing.
Common practice is the implementation of part of the GeoSPARQL standard.
This, however, can be a problem from a business perspective, as you cannot buy a fully GeoSPARQL-compliant software package.
Does it make sense to define a "GeoSPARQL Light" subpart of the standard to make life easier for people to choose from?
I am thinking of supporting CORE, TOP and parts of GEOEXT

**Comment by FransKnibbe** [comment]
What exactly is the problem from a business perspective? Is there a certain demand that is not met with what is on offer?
GeoSparql already is modular, it already had subparts. What would different in a "GeoSPARQL Light"?
