### ISSUE TITLE
geof:aggConcatLines is undefined

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#343]
`geof:aggConcatLines` appears in our Major Changes table and the Annex B but it's undefined in the main text and the functions RDF.

I have put a placeholder in: @situx please complete this function definition in the ADOC & RDF.

**Comment by situx** [comment]
Hi @nicholascar it was removed as part of my large pull request because it seemed to be a duplicate of aggUnion.
What I would do is remove the definitions in Annex B instead.

**Comment by nicholascar** [comment]
OK, I'll do that now
