### ISSUE TITLE
Full review of the 1.1 documents and spec

### ISSUE THREAD

**Issue by jabhay** [opengeospatial/ogc-geosparql#358]
Edits are coming to an end. In prep for going through the release process, we need to do a full sweep of the document to ensure there are no typos, etc.,

**Comment by ajnelson-nist** [comment]
Hello!  I discovered what seem to be other editorial-grade issues, in the form of coding typos, when trying to look over the alignments directory.  I've filed [PR 390](https://github.com/opengeospatial/ogc-geosparql/pull/390) to correct them.
