### ISSUE TITLE
Milestones link in README currently broken

### ISSUE THREAD

**Issue by ajnelson-nist** [opengeospatial/ogc-geosparql#372]
Hello,

The link to "milestones" at this anchor in the README is currently broken:

https://github.com/opengeospatial/ogc-geosparql#process

Was that intended to link to the [Github milestones interface feature](https://github.com/opengeospatial/ogc-geosparql/milestones), or to a tracked document?

**Comment by situx** [comment]
Hi, 
thanks for pointing this out. It should link to the Github milestones interface feature. I will correct it

**Comment by ajnelson-nist** [comment]
Thanks for the quick fix!
