### ISSUE TITLE
Usage of owl:versionIRI?

### ISSUE THREAD

**Issue by ajnelson-nist** [opengeospatial/ogc-geosparql#373]
Hello,

I see in the [geo.ttl for GeoSPARQL 1.1](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl) that the concept `owl:versionIRI` was not used.  Was that an intentional decision, or an unexplored matter?

I appreciate there are potential technical issues with usage of `owl:versionIRI`, particularly for systems that do review of transitive `owl:imports` coverage and adhere to the MUST NOTs in [this section of the OWL specifications](https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI).

(A community I'm working with implements a `versionIRI` MUST NOT test in a [SHACL-SPARQL shape](https://github.com/ucoProject/UCO/blob/Feature-Issue-406/ontology/owl/owl.ttl#L250).  That branch will probably disappear next week, but when it does, [this link](https://github.com/ucoProject/UCO/blob/Feature-Issue-406/ontology/owl/owl.ttl#L250) should work, looking for the concept `uco-owl:versionIRI-shape`.)

I wouldn't request a `owl:versionIRI` be inserted in what is apparently so close to a release, because it is a potentially significant interoperability point.  May this be considered for 1.2, though?

Also, as an aside, I am interested in knowing what the expected "Version's stamped" date of 1.1 is.  It looks like you all are in an any-day-now state, but do you have a planned day?

--Alex

**Comment by situx** [comment]
Hi Alex,

I think the missing owl:versionIRI is either an oversight, or it is us waiting for confirmation by the OGC Naming Authority to get the IRI registered. @nicholascar Do you have any thoughts here?

Concerning the 1.1 release, I can list you the outstanding TODOs:
- Registering Namespaces at OGC
- Finishing the Release Notes and Editorial Work of the specification (error corrections etc.)
- Public Review also at OGC
- Voting about the publication of the standard at the OGC Technical Committee Meeting to accept it
@jabhay please correct me if I missed anything

As the next OGC TC Meeting is in autumn this year, this might be the earliest date the standard can be released.

While the public review and voting process is going on, we anticipate to start work on the next revision of GeoSPARQL 1.2

**Comment by ajnelson-nist** [comment]
Thanks for the outline of remaining tasks.

In your opinion, is it at all likely any backwards-incompatible changes in knowledge modeling would be made w.r.t. the classes and properties in `geo.ttl` *today* versus, the version to be released in or after fall?

**Comment by situx** [comment]
This will likely not happen:
- GeoSPARQL 1.1 aims to be a backward compatible release to GeoSPARQL 1.0, so all things included in GeoSPARQL 1.0 have to stay consistent in GeoSPARQL 1.1
- The class structure and properties in geo.ttl that have not been part of GeoSPARQL 1.0 have been added in GeoSPARQL 1.1, and as of now, there is no discussion of removing any of the classes or properties or any requests of adding new ones we would see a need to address for GeoSPARQL 1.1
- At this stage of the GeoSPARQL 1.1 release cycle, we would only accept minor changes unless there are major issues found in the public review to be addressed. At this point in time, at least in our working group, we see no such issues blocking a release, including the geo.ttl as it is now

**Comment by ajnelson-nist** [comment]
Wonderful to hear, thank you very much.  Thank you for responding to my aside.

I look forward to further discussion on `owl:versionIRI` when @nicholascar has a chance to weigh in.

**Comment by nicholascar** [comment]
Totally an oversight - I actually through it was there! The ontology profile we are informed by (not quite conformant with) is the OntPub profile which recommends its use, from http://rdftools.kurrawong.net/validators:

```
<https://w3id.org/profile/ontpub/req/2.1.10>
    a sh:NodeShape ;
    sh:targetClass owl:Ontology ;
    sh:property [
        a sh:PropertyShape ;
        sh:path owl:versionIRI ;
        sh:nodeKind sh:IRI ;
        sh:minCount 1;
        sh:severity sh:Warning ;
        sh:message "Requirement 2.1.10: OWL ontologies SHOULD indicate a version using the property owl:versionIRI with an IRI object." ;
    ] ;
.
```

So that's a warning if not present, not a violation.

Not, it's not too late to add this in as it's a non-functional change, it should be there, we (I) thought it was and it's present in the [Profile declaration](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/profile.ttl#L15) and the [Validator](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/validator.ttl#L30).

I've put up a PR to ensure that every RDF doc in the standard has a `versionInfo` and a `versionIRI` property with appropriate values: PR #374.

Thanks for the pick-up @ajnelson-nist

**Comment by ajnelson-nist** [comment]
Thank you, @nicholascar !  I'm glad to see this is going in.
