### ISSUE TITLE
area function definition

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#381]
Currently, the area function has the following definition:

> **geof:area (geom: ogc:geomLiteral): xsd:double**
> Returns the area of geom in square meters. Must return zero for all geometry types other than Polygon.

I have my doubts about the second part. Firstly, it seems to assume Simple Features (SF) geometry classes. but that is not indicated. SF is not a mandatory geometry classification (at the moment). Even if  the definition is limited to SF, why not have the function output a non-zero area for e.g. MultiPolygon?

The easiest solution: remove the second sentence of the definition.

**Comment by situx** [comment]
We could change the sentence to closed geometry types? I think that was the intention and would also include more types than polygon

**Comment by FransKnibbe** [comment]
> We could change the sentence to closed geometry types? I think that was the intention and would also include more types than polygon

Yes, that would be good, I think. Probably even better to make that "geometrically closed".
