### ISSUE TITLE
Increase SWG exposure: update GeoSPARQL landing page

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#39]
The quality of the SWG's output will benefit from outside contributions and insights, however small. Therefore it would be good provide clear insight into what is going on.  One way to achieve that is to update GeoSPARQL's home page (https://www.ogc.org/standards/geosparql) to make clear that this SWG is working on an update,  and doing so in an open manner.

**Comment by FransKnibbe** [comment]
This was discussed in the teleconference on 2020-12-02. The OGC has issued press releases about GeoSPARQL. For instance one about the revival of the SWG and its charter, and one about the recent whitepaper. Those press release could be listed in the "Related News" section of the main GeoSPARQL web page.

**Comment by jabhay** [comment]
Ok, let's publish links to the Github repository in both GeoSPARQL standard landing page and the GeoSPARQL SWG landing page.

**Comment by jabhay** [comment]
This has been done.

![standard_landing_page](https://user-images.githubusercontent.com/11606384/115616712-dceb4d80-a333-11eb-8e9d-11a9e0f43463.png)
<img width="837" alt="Screen Shot 2021-04-22 at 6 27 21 am" src="https://user-images.githubusercontent.com/11606384/115616765-ed032d00-a333-11eb-8e95-d40363c1fb68.png">

**Comment by jabhay** [comment]
Done
