### ISSUE TITLE
XML style markup after the TOC and before the title page

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogc-geosparql#393]
A comment from the OGC-NA SubCommittee.

![Screenshot 2022-11-25 at 16 49 32](https://user-images.githubusercontent.com/18121038/204028487-d7d6eaf7-34ac-493e-bb58-f376572708b7.png)

Thanks @chris-little for spotting this.

**Comment by situx** [comment]
@jabhay I have removed this in the master branch for a test, and I could not see any difference in the appearance of the spec PDF or the HTML. I guess it is okay this way?
