### ISSUE TITLE
Repetition of content by the skos:note

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogc-geosparql#395]
A comment from the OGC-NA SubCommittee.

Clause 6.2.3. Class: geo:SpatialObjectCollection (p. 28)

```
skos:definition "A collection of individual Spatial Objects. This is the
superclass of Feature Collection and Geometry Collection."@en ;
skos:note "This is the superclass of Feature Collection and Geometry”
```

Ideally, the `skos:note` should not repeat information that is already in the `skos:definition`.

Thanks @estubkjaer for spotting this.

**Comment by jabhay** [comment]
- [ ] Ensure repeated content appears only in skos:note
