### ISSUE TITLE
Incorrect hyperlink to 8.8.2.2 should be 8.8.3.1

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogc-geosparql#396]
A comment from the OGC-NA SubCommittee. 

A.3.4.1 /req/geometry-extension/geojson-literal (p. 91)

"
..
c. Reference: Section 8.8.2.2"

!! links to 8.8.2.2. Property: geo:asGML - Should be 8.8.3.1. RDFS Datatype: geo:geoJSONLiteral !!

Thanks @estubkjaer for spotting this.

**Comment by jabhay** [comment]
- [ ] Review hyperlinks and correct as necessary
