### ISSUE TITLE
Question about line length

### ISSUE THREAD

**Issue by SimonBin** [opengeospatial/ogc-geosparql#397]
In wake of the upcoming GeoSPARQL 1.1, I want to take the chance to clarify some things (maybe the answer is already clearly in the standard and I just missed it, in which case my apologies)

8.9.25. Function: geof:length (and metricLength)

> The longest length from any one dimension is returned

the wording is a bit unclear to me, does this give me the length of a (Multi)LineString, as in JTS's Length.ofLine, or only the linear distance between its start and end? If the latter, how can I get the length of a line?

**Comment by situx** [comment]
I did not define the function, but I think it should be Length.ofLine, not the distance between start and end.
I will clarify that in the next meeting though because I also find the wording could be improved here.

**Comment by jabhay** [comment]
Confirming, it should be Length.ofLine. We will add this to the standard.
