### ISSUE TITLE
Add inverse of `hasGeometry`

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#4]
Pointer from a geometry to the feature(s) that it is the geometry for - e.g. from GEOX

- [isGeometryOf](https://raw.githack.com/CSIRO-enviro-informatics/geosparql-ext-ont/master/geox.html#isgeometryof) 

Detail from opengeospatial/geosemantics-dwg#73

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Must)](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Should)](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Could)](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Won%27t)](https://api.gh-polls.com/poll/01EJXBJHMCY7KJXGPBBTJBYKK6/Won%27t/vote)

**Comment by nicholascar** [comment]
Closing this issue due to discussions with @dr-shorthair as he and I see this property as superfluous.
