### ISSUE TITLE
Use Turtle for editing the GeoSPARQL ontology?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#40]
The current ontology officially is only available in XML format. Turtle seems a nicer format for collaborative editing of the ontology. So I propose to place the GeoSPARQL ontology in the repository in turtle format. I happen to have that ready...

**Comment by situx** [comment]
I think this is a good idea. 
I also wonder if we want to set up something like a Continuous Integration process to document the current progress in extending the ontology.
Not everyone who is interested in GeoSPARQL will make the effort to examine the TTL file.
In many of our projects, using Gitlab CI we employ [Widoco](https://situx.github.io/widoco_classtree/) for documentation which would look something like this: https://situx.github.io/widoco_classtree/ (Minus the classtree/property tree which is a pull request of mine for the next version of Widoco)
So if you think this is a good idea we could set up a Github Actions process to set up a Github Page with the current ontologoy documentation. (even though I would need to find out how to do this)

**Comment by FransKnibbe** [comment]
Providing an easy to understand view of (versions of) the ontology is a very good idea. It's definitely something to do once we have the ontology in GitHub.

**Comment by FransKnibbe** [comment]
Now that there is TTL file in the repository it is possible to use external visualisation tools. For example: http://www.visualdataweb.de/webvowl/#iri=https://raw.githubusercontent.com/opengeospatial/ogc-geosparql/master/1.0/geo.ttl

Which is nice.

**Comment by dr-shorthair** [comment]
pyLODE is another documentation option - https://github.com/RDFLib/pyLODE 
I use it regularly. Currently it does require that the diagrams are generated separately and then edited in to the HTML. But otherwise fairly clean - e.g. 

http://linked.data.gov.au/def/asgs
http://linked.data.gov.au/def/placenames 

Encourages maintenance of a lot of inline documentation and examples (i.e. in the RDF file).

**Comment by nicholascar** [comment]
The OGC Naming Authority will do all of this for us. 

I have discussed a publication workflow with them whereby we just hand them data artefacts and they publish them in the various human- and machine-readable forms. This will include turtle for the ontology RDF. The workflow may look like this:

![image](https://user-images.githubusercontent.com/7321872/99525999-5a5a0d00-29e6-11eb-9c96-43949d7c77e1.png)

Note that this workflow is dependent on us presenting the ontology within a _profile_ to link it to non-ontology related elements, such as the specification PDF and, in the future, related vocabularies, perhaps for things like datatype literals.

**Comment by FransKnibbe** [comment]
Hurray for the OGC Naming Authority!

**Comment by jabhay** [comment]
@FransKnibbe , now that the TTL file is part of the repo, and where we are editing the ontology, would you like to close this ticket?
