### ISSUE TITLE
geof:centroid missing and not documented

### ISSUE THREAD

**Issue by SimonBin** [opengeospatial/ogc-geosparql#403]
in the upcoming GeoSPARQL 1.1 document as far as I can tell.

it is referred to in A.3.DGGS.1.7 and the tables in F.3

but it is missing from Req 40 and section 8.9

it surely should not be missing from GeoSPARQL 1.1!

**Comment by situx** [comment]
Thank you for noticing. This is indeed something we need to correct before publishing
