### ISSUE TITLE
How to find examples linked within geo.ttl?

### ISSUE THREAD

**Issue by ajnelson-nist** [opengeospatial/ogc-geosparql#424]
Hello,

In trying to understand properties in `geo.ttl`, I tried to look at the examples cited inline.  E.g. using this copy-pasted excerpt from [today's `geo.ttl`](https://github.com/opengeospatial/ogc-geosparql/blob/68065c768b9c41c17ed62594b5a18b623b792f99/1.1/geo.ttl):

```turtle
PREFIX : <http://www.opengis.net/ont/geosparql#>
PREFIX spec11: <http://www.opengis.net/spec/geosparql/1.1/specification.html#> # TODO: use PID IRI
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

:gmlLiteral
	skos:example spec11:B.1.2.4 ;
.
```

From the above, I'd like to take a peek at `http://www.opengis.net/spec/geosparql/1.1/specification.html#B.1.2.4`.  However, that URL is currently not resolving.  Ascending up to the domain, it looks like a PURL service is currently down and/or in throes.

Is this a service-currently-down issue, or a the-links-are-incorrect issue?

Is there a spot in the source tree where I should be able to find this example?  `grep -R B.1.2.4 *` in the top source directory didn't give me any leads outside of `1.1/geo.ttl`.

**Comment by situx** [comment]
Hi, the examples are in the specification document which you can access for example on the GitHub page of this Repository. The URIs references need to be created by the OGC Naming Authority and will become active once the standard is formally approved by OGC.
In your case the URI refers to specification annex b 1.2.4 which you should find the the spec on the GitHub page of this repo

**Comment by ajnelson-nist** [comment]
Thank you, @situx , I think I've found the example. Though, checking alignment: It appears this is the in-page anchor.

https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_c_1_2_4_geometry_serializations

Should the `B.1.2.4` in the Turtle lead with `C` instead?

**Comment by VladimirAlexiev** [comment]
https://github.com/opengeospatial/ogc-geosparql/issues/473 is a duplicate of this and @situx just said he fixed it.

**Comment by ajnelson-nist** [comment]
@VladimirAlexiev , @situx , thank you for letting me know and for the fix.  Apologies, I just stumbled across the notice from when I was away from keyboard.
