### ISSUE TITLE
Re-present document in Metanorma format

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#425]
* Try to process existing ADOC using the Metanorma processor
    * use https://github.com/metanorma/metanorma-ogc
    * see what we get
* Re-format current ASCIIDOC according to OGC ASCIIDOC requirements
    * as per https://www.metanorma.org/author/ogc/

**Comment by situx** [comment]
The representation of the spec in Metanorma has been done for GeoSPARQL 1.1 and further revisions of the standard.
This issue can therefore be closed.
