### ISSUE TITLE
Support WKB literals in GeoSPARQL

### ISSUE THREAD

**Issue by jabhay** [opengeospatial/ogc-geosparql#427]
As per Official change request: [OGC CR 585](http://ogc.standardstracker.org/show_request.cgi?id=585)

We'd like to extend the set of standard serializations of geometry data to include WKB. This further supports the Simple Features Access standard.

We have asked the Apache JENA community what encoding of WKB would work best, and they have replied stating that base64 is preferred owing to common use and compactness.

**Comment by situx** [comment]
Pull Request #407 introduced the WKB Literal using EWKB. What is missing is the OGC community standard for EWKB. But I think this issue can be closed.
