### ISSUE TITLE
Add annotation in other languages next to English

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#43]
This issue corresponds with [OGC Standards tracker request 660](http://ogc.standardstracker.org/show_request.cgi?id=660).

For greater worldwide adoption of the GeoSPARQL standard, it would be good if the annotation (comments, definitions, descriptions) in the ontology is in more languages than English. Adding translations could be done on the basis of available linguistic knowledge within the SWG. This enhancement could work particularly well with publication of the ontology in JSON-LD format, allowing definitions to be easily incorporated in web pages.

**Comment by nicholascar** [comment]
See the DCAT2 ontology RDF file which has multiple languages in it for title & description properties: <https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat2.ttl>

**Comment by mathib** [comment]
Some experience from the W3C Linked Building Data group regarding the translation of the Building Topology Ontology (BOT):

Easiest workflow is to work in English until the main content is ready for a milestone. From then on, we worked in a Google Spreadsheet for collaborative preparation of translations. During the preparation of translations, issues tend to arise regarding certain (original English) definitions of concepts and these have to be corrected while previous translations need to be kept in sync or marked as "outdated". Whenever translations were outdated, they got marked in a color so that the translator responsible for it knows that the definition has changed and he/she needs to update it.

We used a script to transform the final CSV data to RDF, after performing a quick check with an automatic translation service for filtering out hijacked descriptions

**Comment by nicholascar** [comment]
We could do this: perhaps then we just need to link to a Google Spreadsheet from one of the README files in the repo?

**Comment by nicholascar** [comment]
Can people please nominate here for other language translations so we know who's keen? From today's meeting minutes, we have:

**Nominee** | **Language(s)**
--- | ---
@kjano | Polish<br />German
@FransKnibbe | Dutch
Gabriela Wiersma |  Portuguese

Any others? If you comment below, I will update this talbe.

**Comment by dr-shorthair** [comment]
@nicholascar Tongan ;-)

**Comment by mathib** [comment]
We might need to ask people from other communities (DCAT, LBD, etc.) for translations in other languages?

**Comment by nicholascar** [comment]
> people from other communities

As long as we get 2+  translations done by us, the precedent will have been set, so others can be pointed at those and know how to contribute more.

**Comment by FransKnibbe** [comment]
It is probably best to do the translations just before publication of a new version, i.e. when the annotation in English is stable. Before that time, we could test scripts for exporting annotation to CSV and back again, to avoid delays later on.

**Comment by mathib** [comment]
I can ask for the script we used in the LBD group

**Comment by mathib** [comment]
I've just shared an adjusted spreadsheet and prepared a conversion script to generate triples through the internal mailing list.

**Comment by FransKnibbe** [comment]
> I've just shared an adjusted spreadsheet and prepared a conversion script to generate triples through the internal mailing list.

Which mailing list is that? I have not seen it yet.
We could make a new folder in the code tree for utilities.

**Comment by mathib** [comment]
> Which mailing list is that? I have not seen it yet.
geosparql.swg@lists.opengeospatial.org

> We could make a new folder in the code tree for utilities.
It's a Google Spreadsheet and a Google App Script for convenience. I can publish it as a .xls file and .gs (well javascript) respectively on the repo.

**Comment by FransKnibbe** [comment]
@mathib: geosparql.swg@lists.opengeospatial.org is not a public list, so I can not use it. For me and others without OGC membership it would be good to use this repository.

**Comment by mathib** [comment]
okay, that's a bummer. I had the idea that everyone was in that mailing list. I'll share the editable link with your gmail. If others are not in the mailing list, please let me know so I can give you the link directly

**Comment by FransKnibbe** [comment]
@mathib: Thank you, I have access to the spreadsheet now. Assuming that it is possible for all contributors to access and edit the same spreadsheet, how does getting the data out work? Can we export to TTL and merge that with the ontology?

By the way: geosemweb@lists.ogc.org is a public list. It could be used as an alternative to  geosparql.swg@lists.opengeospatial.org.

**Comment by FransKnibbe** [comment]
@mathib: I like the plan.
As a test, I made a small change. But generating altered triples failed because the function WriteTurtle could not be found. Perhaps the script needs to be shared too?

**Comment by jabhay** [comment]
**Nominee** | **Language(s)**
--- | ---
@kjano | Polish<br />German
@situx | German (https://github.com/opengeospatial/ogc-geosparql/pull/240)
@lvdbrink | Dutch
Gabriela Wiersma |  Portuguese

**Comment by oldskeptic** [comment]
> Can people please nominate here for other language translations so we know who's keen?

@nicholascar If you don't mind lurker contributions, put me down for french.

**Comment by nicholascar** [comment]
@oldskeptic we'll take what's on offer! 

We have a translation precedence now - the German version at https://github.com/opengeospatial/ogc-geosparql/pull/240 - so please follow that labels-only form. 

You're probably free to translate now since the ontology is extremely unlikely to change much before release, but there is no rush here: you could also wait until close to release (some time in Jan/Feb).

**Comment by dr-shorthair** [comment]
@nicholascar Tongan ?

**Comment by oldskeptic** [comment]
> @oldskeptic we'll take what's on offer!
> 
> We have a translation precedence now - the German version at #240 - so please follow that labels-only form.
> 
> You're probably free to translate now since the ontology is extremely unlikely to change much before release, but there is no rush here: you could also wait until close to release (some time in Jan/Feb).

@nicholascar Please confirm replacing rdfs:label with skos:prefLabel and rdfs:comment with skos:definition ?

**Comment by nicholascar** [comment]
@oldskeptic yes, that is correct. We have adopted the more specific SKOS properties.

**Comment by dr-shorthair** [comment]
I've also transitioned to SKOS-first in a number of vocabs that I'm managing.

**Comment by nicholascar** [comment]
@oldskeptic why don't you add an `owl:Ontology` element to each file that you've made and add yourself in as the creator there, just like this:

https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl#L24

I note that @situx hasn't added himself to the German files at https://github.com/opengeospatial/ogc-geosparql/tree/master/1.1/translations in this manner, but perhaps he should.
