### ISSUE TITLE
Some links in spec don't work

### ISSUE THREAD

**Issue by alanruttenberg** [opengeospatial/ogc-geosparql#439]
Links like http://www.opengis.net/def/geosparql yield a page with an input error
The message is
```
Status
    400
Message
    The object with URI http://www.opengis.net/def/geosparql is not of type skos:ConceptScheme, 
    skos:Collection or skos:Concept and only these classes of object are understood by VocPrez 
```

**Comment by ghobona** [comment]
The links will work once the registration is complete.

The relevant GitHub issue is https://github.com/opengeospatial/NamingAuthority/issues/238

**Comment by ghobona** [comment]
The link mentioned on this GitHub Issue now resolves.

I am closing this GitHub Issue. Please create a new GitHub Issue with any broken links you find.
