### ISSUE TITLE
GeoSPARQL and Common Query language CQL

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#44]
The common query language (CQL) (http://docs.opengeospatial.org/DRAFTS/19-079.html#simple-cql_filter-expression) is used in many geospatial web services (WFS) and in the currently in OGC API features to filter geospatial featurecollections.

In one of our research projects we developed a "semanticwfs" (https://github.com/i3mainz/semanticwfs), i.e. a WFS/OGC API Features compatible webservice with triple store backends which has to convert CQL filter expressions to (Geo)SPARQL internally.
Test Instance here: https://www.i3mainz.de/projekte/bkg/semanticwfs/

For this usecase (using a GeoSPARQL compliant triple store as a backend of an OGC API Features compatible web service) mappings from CQL to GeoSPARQL have to be defined.

If this is a usecase which is interesting to follow up we could define the new GeoSPARQL version keeping CQL compatibility in mind, as OGC API Features and WFS are still the main form of accessing geospatial data for the GIS community.

I am just putting this out there for discussion as I am not sure if it is something we should consider or if this is the right place.

**Comment by nicholascar** [comment]
Hi @situx, I've just implemented a series of what I call _OGC LD APIs_, which are OGC API instances implemented using a Linked Data API framework - [pyLDAPI](https://github.com/rdflib/pyLDAPI). The back end for 2 of them is a triplestore with GeoSPARQL data in it:

1. http://asgs.surroundaustralia.com/
2. http://geofabric.surroundaustralia.com/

Another one has a WFS back-end:

3. http://provinces.surroundaustralia.com/

I guess I've taken a related approach to your semanticwfs but my implementations are both OGC APIs and Linked Data APIs in the same place!

These are all test systems and one of the things they need to move to more solid implementations is better filtering- currently they only have BBOX filters in place.

So I'm interested in CQL-like filters or CQL-to-(Geo)SPARQL.

Happy to keep chatting about this whether or not it actually goes into GeoSPARQL 1.1.

_(nice cuneiform GitHub image by the way)_

**Comment by situx** [comment]
Hi @nicholascar,

great to see there are similar approaches in this direction.
We did not consider a Linked Data API implementation for our project, but it seems like the next logical step and should also not be hard to implement. I will discuss it.

As for the CQL compatibility we have similar experiences. We currently rewrite CQL BBOX Queries to GeoSPARQL FILTER expressions internally (which only works for GeoSPARQL compatible triple stores of course) but for example lack temporal filter capabilities. Therefore we found that if we were to extend GeoSPARQL, we should do it with the capabilities OGC API Features standards in mind.

We are due to finish this project in August 2021 and by then we hope to have implemented more OGC API Features proposals (OGC API Records for metadata, OGC API Styles for style management, etc.).
The goal is to base every component of a traditional SDI on LD technologies and find out possible benefits of that for a geospatial authority like the Federal Agency for Cartography of Germany. (Data correction, data enrichment, interlinkage of data to other state authorities and LOD sources etc.)

If there are any ways of cooperation, we are certainly open for it.

**Comment by nicholascar** [comment]
> If there are any ways of cooperation, we are certainly open for it.

I think there are avenues for cooperation here! I'll be in touch via this SWG and also once the Testbed 16 activities taht have caused all this work are completed.

**Comment by rob-metalinkage** [comment]
Of interest for any semantic approach is how the binding of value ranges to object models is handled - XSD and JSON has no capacity for this (noting enumerations only handle small sets of data model specific options - not descriptions of the data range at all ) - WFS GetDomain was intended to cover some of this - and AFAICT its an open issue for OGC API https://github.com/opengeospatial/ogcapi-features/issues/79 

personally I lean towards the ability to semantically annotate in a flexible way - then would use RDF-Datacube since it includes the important semantics of sampling space vs measurement.

**Comment by situx** [comment]
To view the linked data instances in our local triple store we also developed GeoPubby (a fork of the Pubby Linked Data Viewer)
https://github.com/i3mainz/geopubby
Test instance here:
https://www.i3mainz.de/projekte/bkg/geopubby/page/Mainz
So in some sense we also have a linked data frontend with several geospatial downlift options.
But I would also suggest that a standardization of such tools by the OGC or at least some guidelines on how to use linked data would be a good idea.

**Comment by nicholascar** [comment]
We have @situx's CQL to SPARQL BP here: https://github.com/opengeospatial/ogc-geosparql/blob/master/bestpractice/CQLAnnex.adoc

Should that not just be an Annex in the Specification?

If not then it needs its own slot in the GeoSPARQL 1.1 profile declaration.

I'll create a PR to add this to the Spec to prompt discussion of this issue.
