### ISSUE TITLE
Missing definition: http://www.opengis.net/def/function/geosparql/asGML

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogc-geosparql#445]
This URI `http://www.opengis.net/def/function/geosparql/asGML` is in the asciidoc files ([1.1 spec 11-Part-08.adoc](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/spec/11-Part-08.adoc) and [1.1 spec 18-Annex-C.adoc](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/spec/18-Annex-C.adoc)) but its definition could not be found in any of the TTL files.

Please add the definition to the relevant TTL files.

**Comment by situx** [comment]
I think it would be this function definition.
https://github.com/opengeospatial/ogc-geosparql/blob/489bc6338970e389355fccdf542d5bf77bde00af/1.1/funcsrules.ttl#L602

**Comment by ghobona** [comment]
That's the one.

Thanks @situx .
