### ISSUE TITLE
Missing ontology in import closure

### ISSUE THREAD

**Issue by neilotte** [opengeospatial/ogc-geosparql#446]
It appears that: 

•	./1.0/funcsrules.ttl
•	./1.1/funcsrules.ttl

Both import <http://www.opengis.net/def/ogc-na>

However, it doesn’t appear there is an instance of owl:Ontology with this IRI in this repository, and I’m unable to find this content elsewhere. 

Can you confirm that this content is, indeed, unavailable, and if you believe this is an error? I believe the standard practice for ontology releases is to include all content, or pointers to all content, contained in the import closure graph for artifacts in the release.

**Comment by situx** [comment]
Hi @neilotte 
Indeed, we use this namespace, the namespace of the OGC Naming Authority, to define functions.
In particular, we use this namespace for exactly one property, which signals the validity of a function or rule according to the definitions of the OGC Naming Authority.
https://defs.opengis.net/vocprez/object?uri=http%3A%2F%2Fwww.opengis.net%2Fdef%2Ffunction%2Fgeosparql%2FconvexHull&_profile=skos
I am unaware where this particular vocabulary is hosted or why it cannot be resolved at the OGC Naming authority.
@ghobona Do you know where the ogc-na vocabulary is hosted? I have failed to find it in the OGC Functions register right now.

**Comment by ghobona** [comment]
@situx The ontology is [here](https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/ogc-na.ttl#L139).

It should be accessible from RAINBOW. So I have created a NamingAuthority GitHub [issue](https://github.com/opengeospatial/NamingAuthority/issues/261) to look into why it is not accessible.

**Comment by neilotte** [comment]
@ghobona @situx  -- Thank you both!
