### ISSUE TITLE
Abstract Test Suite GeoJSON mentions SRS's that cannot be specified

### ISSUE THREAD

**Issue by redmer** [opengeospatial/ogc-geosparql#452]
The abstract test suite says in § [A.3.4.2]:

> The IRI \<http://www.opengis.net/def/crs/OGC/1.3/CRS84\> shall be assumed as the SRS for `geo:geoJSONLiteral` instances that do not specify an explicit SRS IRI.

Yet an explicit SRS IRI cannot be specified in a GeoJSON literal, per [Req 26], which says:

> RDFS Literals of type `geo:geoJSONLiteral` do not contain a SRS definition. All literals of this type shall, according to the GeoJSON specification, be encoded only in, and be assumed to use, the WGS84 geodetic longitude-latitude spatial reference system (`http://www.opengis.net/def/crs/OGC/1.3/CRS84`).

I had hoped that this could refer to [JSON-FG] but alas that does not extend the `"geometry": {}` JSON object, but rather specifies a new co-ordinate `"place": {}` object. 

[A.3.4.2]: https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#conf_geometry_extension_geojson_literal_srs
[Req 26]: https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#req_geometry_extension_geojson_literal_srs
[JSON-FG]: https://github.com/opengeospatial/ogc-feat-geo-json

**Comment by situx** [comment]
Hi @redmer thanks for picking this up. To clarify:
- Yes GeoJSON literals may only have one CRS, namely CRS84 as per the definition of GeoJSON as a format.
- And yes, I think the wording in the abstract test suite is very poor there, as you cannot define another SRS
I think we will correct that shortly. In fact it might be a copy/paste mistake from other literals which indeed contain an SRS URI. I will create a pull request to change it.

As for JSON-FG: That would require a JSON-FG literal which we did not define in GeoSPARQL 1.1.
If there is demand for that we could think about adding it for next revisions.

**Comment by situx** [comment]
We changed the wording for the better, so that issue can be closed now
