### ISSUE TITLE
Inconsistency in minx/minX, miny/minY, minz/minZ, maxx/maxX, maxy/maxY, and maxz/maxZ

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogc-geosparql#454]
[This turtle file](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/servicedescription/servicedescription_all_functions.ttl#L69) declares a triple with an object named `<http://www.opengis.net/def/function/geosparql/minX>`. 

However, [this turtle file](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/funcsrules.ttl#L1444C11-L1444C11) declares a triple with a subject named `<http://www.opengis.net/def/function/geosparql/minx>`.

Please fix the issue and let me know when the source files in this `ogc-geosparql` repository have been fixed.

Screenshots attached for quick reference.

![Screenshot 2023-11-22 at 19 11 11](https://github.com/opengeospatial/ogc-geosparql/assets/18121038/7acf7608-8fd4-4f73-b606-0720f02cf7fb)

![Screenshot 2023-11-22 at 19 10 59](https://github.com/opengeospatial/ogc-geosparql/assets/18121038/2277fabf-6ef5-4b33-ad39-9ac0cc51c80c)

**Comment by ghobona** [comment]
Note that in the Standard document the convention used is minX, minY, minZ, maxX, maxY, and maxZ. So it may be safer to change all to this convention.

![Screenshot 2023-11-23 at 16 23 17](https://github.com/opengeospatial/ogc-geosparql/assets/18121038/0a046722-09ec-4408-9251-5263320558a9)

**Comment by nicholascar** [comment]
I will do this

**Comment by nicholascar** [comment]
This issue has been addressed directly by PR #464 so I will close this. Note that the files fixed here will be split in a subsequent PR (#461)
