### ISSUE TITLE
broken links "Recommendation for specification of units of measurement"

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/ogc-geosparql#471]
All versions of the spec
- https://opengeospatial.github.io/ogc-geosparql/geosparql13/document.html
- https://opengeospatial.github.io/ogc-geosparql/geosparql12/document.html
- https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html

include 5-7 links "Recommendation for specification of units of measurement" that are broken.
The correct heading is "Recommendation for units of measure"
(eg https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_recommendation_for_units_of_measure)

(slightly related to https://github.com/opengeospatial/ogc-geosparql/issues/468)

**Comment by situx** [comment]
Thanks. For GeoSPARQL 1.1 a fix is waiting for approval here #470

**Comment by situx** [comment]
Closing here, since #470 has been merged
