### ISSUE TITLE
broken skos:example links in ontology

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/ogc-geosparql#473]
The 1.1 ontology (https://opengeospatial.github.io/ogc-geosparql/geosparql11/index.html or https://opengeospatial.github.io/ogc-geosparql/geosparql11/geo.ttl) has skos:example links like this:
http://www.opengis.net/spec/geosparql/1.1/specification.html#B.1.1.2.8

This is broken in two ways:
- The spec lives at https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html (in fairness, `geo.ttl` does say:
```ttl
PREFIX spec11: <http://www.opengis.net/spec/geosparql/1.1/specification.html#> # TODO: use PID IRI
```
- There is no anchor `#B.1.1.2.8`: probably https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#C.1.1.2.8 is meant

**Comment by situx** [comment]
Yes, this is clearly wrong, since we only list examples in Annex C, but not in Annex B. I issued a pull request to fix it. Once approved it will be merged
