### ISSUE TITLE
`(min|max)(X|Y|Z)` definition should mention which SRS

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/ogc-geosparql#477]
The functions `(min|max)(X|Y|Z)`
https://opengeospatial.github.io/ogc-geosparql/geosparql13/document.html#_function_geofmaxx
are defined as "returns the maximum X coordinate for geom" and declared to return `xsd:double`
- I think the definitions should add "using the SRS of `geom`".
- I thought that `GeometryCollection` can have several SRS, but then found this in `sf_geometries.ttl`: "All the elements in a GeometryCollection shall be in the same Spatial Reference System. This is also the Spatial Reference System for the GeometryCollection."
So the definitions could also add "(every geometry, even `GeometryCollection`, has a single SRS)"

**Comment by situx** [comment]
Thanks for the suggestion. I agree. I would improve the definitions.
