### ISSUE TITLE
Why does GeoSPARQL define DC terms?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#49]
I notice the GeoSPARQL ontology (version 1.0) duplicates definitions of annotation properties from the dcterms vocabulary. For  example dc:contributor and dc:creator. Why is that?

**Comment by nicholascar** [comment]
Could be a result of making it work in desktop ontology tools like protege, more than being an ontological requirement.

Yes we should remove things defined elsewhere.

**Comment by nicholascar** [comment]
To be closed by PR #53
