### ISSUE TITLE
bigger questions about reqs.ttl

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/ogc-geosparql#491]
Complementing #490:

https://github.com/opengeospatial/ogc-geosparql/blob/master/spec/ontology/requirements/reqs.ttl

On the conceptual level, there are 2 considerations that are probably too drastic to be accepted, but I'll still raise them:
- Implementations implement **requirements** that are only then checked by **tests**.
Thus tests are secondary (indirectly borne by the parasitic/constant description `spec:testPurpose "check conformance with this requirement"@en`).
So I think it would be better to make collections of requirements in addition to (or instead of) collections of tests.
  - sd:Feature is defined as "feature of a SPARQL service. Specific types of features include functions, aggregates, languages, and entailment regimes and [entailment] profiles. This document defines five instances of sd:Feature: sd:DereferencesURIs, sd:UnionDefaultGraph, sd:RequiresDataset, sd:EmptyGraphs, and sd:BasicFederatedQuery". I think it's fair to say a feature "I have implemented this requirement (or collection of requirements)" but not "I have passed this conformance test (or collection of tests)"
  - But I understand the spec is not structured this way...
  - If you restate ConformanceClasses as collections of requirements, this will make a better basis for using them in SPARQL SD (#481)
- Have you considered the W3C EARL ontology that's used to express conformance tests for a great many W3C specs?
These are specific tests (with manifests of concrete files: eg input, query, expected output) whereas GeoSPARQL tests are abstract...

**Comment by VladimirAlexiev** [comment]
@situx I saw "requirement classes" in the spec. But I don't see them in `reqs.ttl`?

**Comment by situx** [comment]
The requirement classes were indeed missing and you are right. These are the better fits for the service descriptions. 
#496 corrects this
