### ISSUE TITLE
function list discrepancies

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/ogc-geosparql#493]
@situx Continuing the checking of function lists, I found bigger problems than #480.
In addition to lists obtained from the spec in #492, I collected all functions from:
- `servicedescription_all_functions.ttl`:  [func-from-all-functions.txt](https://github.com/opengeospatial/ogc-geosparql/files/13792106/func-from-all-functions.txt)
- `funcsrules.ttl`: [func-from-funcrules.txt](https://github.com/opengeospatial/ogc-geosparql/files/13792105/func-from-funcrules.txt)

Discrepancies:
-  `funcrules.ttl` defines 6 with wrong casing: `maxx, maxy, maxz, minx, miny, minz`
- `funcrules.ttl` lacks 15: `aggBoundingBox, aggBoundingCircle, aggCentroid, aggConcaveHull, aggConvexHull, aggUnion, centroid, coordinateDimension, geometryN, geometryType, is3D, isMeasured, numGeometries, spatialDimension, transform`
- `servicedescription_all_functions.ttl` lacks 5: `aggBoundingBox, metricArea, metricLength, metricPerimeter, perimeter`

I think some checks need to be implemented to check that all these lists conform with each other!

**Comment by situx** [comment]
I corrected the problems you mentioned in #496 
We will consider adding a script to the CI process which would check for consistency between the different files
