### ISSUE TITLE
Add properties for Centroid and Bounding Box

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#5]
e.g. from GEOX

- [hasCentroid](https://raw.githack.com/CSIRO-enviro-informatics/geosparql-ext-ont/master/geox.html#hascentroid)

Detail from opengeospatial/geosemantics-dwg#73

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Must)](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Should)](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Could)](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Won%27t)](https://api.gh-polls.com/poll/01EJXBHWK2ZFDJ87E40892F78R/Won%27t/vote)

**Comment by nicholascar** [comment]
@dr-shorthair can this be closed? GeoX PR merged...

**Comment by dr-shorthair** [comment]
Link to PR please? Then I can check.

**Comment by nicholascar** [comment]
Actually, this is not addressed in the GeoX PR. There is another pending PR that introduced a centroid function, PR #57, but so far, no property. Will need a new PR.

**Comment by dr-shorthair** [comment]
I understand that roles is a more general solution, but a few convenience/utility properties are useful. Centroid is a pretty obvious example IMAO.
