### ISSUE TITLE
newlines in annotation text literals

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#50]
In the original GeoSPARQL ontology some annotation texts have newlines in the middle of a sentence. For example:

    rdfs:comment """
          Exists if the subject SpatialObject spatially contains the
          object SpatialObject. DE-9IM: T*TFF*FF*
        """@en ;

I think this kind of text formatting is better left to the data consumer. Therefore I propose to remove newlines in annotation text, with the exception of intended paragraph breaks.

**Comment by jabhay** [comment]
Addressed in PR. Thanks @FransKnibbe
