### ISSUE TITLE
Improve the GeoSPARQL vocabularies

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#51]
The OGC publishes vocabularies from GeoSPARQL separately, see this dev publication of the _GeoSPARQL Functions Register_ Vocab:

http://defs-dev.opengis.net/vocprez/object?uri=http://www.opengis.net/def/function/geosparql

There are a number of problems with this vocabulary from a _Vocabulary Best Practice_ (my informal assessment of it) point-of-view:

* duplicate prefLabels
    * Functions `sfContains` & `ehContains` have the prefLabel "contains"
* multiple, different objects within a single hierarchy
    * both GeoSPARQL `Rule` and `Function` are listed but not differentiated in the hierarchy - they are in separate Collections
    * the vocabulary is called _GeoSPARQL Functions Register_  but contains more than `Functions`
* lack of vocabulary-level metadata
    * individual Concepts have good metadata but the vocab as a whole doesn't
    * the Collections don't have any metadata to describe the purpose/logic of the Collection

I propose that changes to the vocabs to address these issues be part of the _Best Practice_ publication of GeoSPARQL 1.1

**Comment by dr-shorthair** [comment]
> duplicate prefLabels
> - Functions sfContains & ehContains have the prefLabel "contains"

This is a feature, not a bug. While it might be convenient for UIs, it is not required that labels be unique. Labels are not identifiers. 

Nevertheless, since the functions use a different algorithm, it might be helpful all round if the labels advertised that - e.g. "contains (SF)" vs "contains (EH)".

**Comment by nicholascar** [comment]
> This is a feature, not a bug.

But you agree, even though it's SKOS-legal, it's undesirable in this case!

My thoughts about identical prefLabels are "not in one vocabulary, please". In this case, the things are clearly not the same thing so it's unhelpful, even if legal, to have the same prefLabel. They are _similar_ things so higher-order concepts for the general concept of "contains" could be contemplated, but a simpler option is just to do as you say and differentiate the prefLabels in their wording.

**Comment by FransKnibbe** [comment]
What exactly is the status of the GeoSPARQL Functions Register? Is it an official OGC publication?
It seems to be a derivative of the GeoSPARQL ontology. Wouldn´t it be sufficient to ensure that there is an automatic procedure in place to derive the Functions Register from the GeoSPARQL ontology each time a new version of the ontology is published?

**Comment by nicholascar** [comment]
> Wouldn´t it be sufficient to ensure that there is an automatic procedure...

Not sufficient, no. A good idea, yes, but my point was about the content of the vocabs, so automating it’s generation would be fine but we still need to improve the values.

Once we have an ontology v1.1, I propose we review what vocabs are produced from it and what they should like.

**Comment by nicholascar** [comment]
Most points addressed by PR #71
