### ISSUE TITLE
define more topological relation equivalences

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/ogc-geosparql#510]
https://docs.ogc.org/is/22-047r1/22-047r1.html#_equivalent_rcc8_egenhofer_and_simple_features_topological_relations
9.5.  Equivalent RCC8, Egenhofer and Simple Features Topological Relations
has a rich table of equivalences.

But as far as I can see, `geo.ttl` defines only these:
```ttl
:ehDisjoint owl:equivalentProperty :sfDisjoint .
:ehEquals owl:equivalentProperty :sfEquals .
:ehMeet	owl:equivalentProperty :sfTouches .
```

Please add the following:
- `sfOverlaps equivalentProperty ehOverlap`
- Equivalences of `rcc8` relations 
- `subPropertyOf` for the `+` combinations, eg 
`ehContains subPropertyOf sfContains. ehCovers subPropertyOf sfContains`
- `complementOf` for the negations `¬`, eg
`sfIntersects owl:complementOf ehDisjoint`
and thus 
`sfIntersects owl:complementOf sfDisjoint`

In addition, change the table to use the actual prop names (eg `geo:sfDisjoint` in the **Simple Features** column), and link to their definitions.

**Comment by mperry455** [comment]
As discussed in 03/06/2024 SWG Meeting, this is a good idea and we will look at adding more equivalences in version 1.3 of GeoSPARQL.

**Comment by VladimirAlexiev** [comment]
Thanks @situx ! I looked at #532 for like 2 minutes and it seems ok to me, and quite completely addresses my comment.

However, another set of eyes must check `subPropertyOf` because this is a bit tricky and it's easy to get it wrong.

**Comment by situx** [comment]
#532 has been checked and merged, so this issue can be closed
