### ISSUE TITLE
Geosparql standard documentation links broken

### ISSUE THREAD

**Issue by remiColletGG** [opengeospatial/ogc-geosparql#514]
All the links under sections Geosparql 1.0 and Geosparql 1.1 from page [https://opengeospatial.github.io/ogc-geosparql/](https://opengeospatial.github.io/ogc-geosparql/) seem to be broken (error 404).

Many thanks for all the work ! It's a pleasure working with geosparql.

**Comment by Maximvdw** [comment]
I can also confirm that this is still not fixed

**Comment by nicholascar** [comment]
Should be:

* GeoSPARQL 1.0
    * Function Descriptions: 
        * Replace https://opengeospatial.github.io/ogc-geosparql/geosparql10/servicedescription_allfunctions.html with https://opengeospatial.github.io/ogc-geosparql/geosparql10/servicedescription_all_functions.html  
        * added a "_")
* GeoSPARQL 1.1
    * GeoSPARQL 1.1 Functions: http://www.opengis.net/def/function/geosparql  
    * GeoSPARQL 1.1 Rules: http://www.opengis.net/def/rule/geosparql  
    * GeoSPARQL 1.1 Requirements and Conformance Classes: http://www.opengis.net/def/geosparql/reqs
    * GeoSPARQL 1.1 Service Description
        * Extensions: http://www.opengis.net/def/geosparql/servicedescextensions
        * Function Descriptions: http://www.opengis.net/def/geosparql/servicedescallfunctions
        * Feature Descriptions: http://www.opengis.net/def/geosparql/servicedescconformanceclasses
