### ISSUE TITLE
Cross-conversion of Moreton island example points?

### ISSUE THREAD

**Issue by ajnelson-nist** [opengeospatial/ogc-geosparql#522]
I was looking at the Moreton Island example in the `examples/` folder, and noticed some of the data doesn't seem to be shared between, e.g., the `.wkt` file and the `demo-dataset.ttl`.  For instance, the number-string `27.0621757` appears in the `.wkt` but not in the Turtle.

Were these examples meant to demonstrate cross-coding of the same data, or instead just representations from different sources about the same subject?

**Comment by jabhay** [comment]
Hi @ajnelson-nist,
It's the latter, two separate examples from different sources about the same subject, as described in the README file.
Cheers,
Jo

**Comment by ajnelson-nist** [comment]
Got it.  Thank you!
