### ISSUE TITLE
GeoSPARQL 1.3 presentation; migrate github project

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/ogc-geosparql#528]
@nicholascar @situx gave an excellent presentation at the LBD group!
https://github.com/w3c-lbd-cg/lbd/blob/gh-pages/presentations/geometry/GeoSPARQL%20LB%20Working%20Group_20240617.pdf

- Slide 11 refers to https://github.com/orgs/opengeospatial/projects/11 but there's no such project page
- The actual GeoSPARQL 1.3 project is https://github.com/opengeospatial/ogc-geosparql/projects/4
- But it says: "Projects (classic) will be sunset on August 23, 2024. We encourage you to migrate this project to the new Projects experience" and there's a `Migrate` button

**Comment by jabhay** [comment]
Thanks for bringing this to our attention. I've now migrated the project to here: https://github.com/orgs/opengeospatial/projects/30. The existing links will continue to work until the classic projects are sunset. New links should point to the new project.
