### ISSUE TITLE
Representing geometries as linked resources

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#529]
From a discussion in the W3C Linked Building Working Group:

We would like to point to geometries represented as files from within the GeoSPARQL graph

**Comment by situx** [comment]
Some thoughts on this here:
We could use the following pattern:
`
geo:hasFileSerialization rdfs:subPropertyOf geo:hasSerialization .
ex:mygeom rdf:type geo:Geometry .
ex:mygeom geo:hasFileSerialization ex:mygeomfile .
ex:mygeomfile rdf:type dct:Dataset .
ex:mygeomfile dct:type <https://uri4uri.is4.site/mime.html/model/x3d+xml> .
ex:mygeomfile dct:distribution "http://hereismyfile.net/myfile.x3d"^^xsd:anyURI .
`
Literals which have been used for the provision of WKT, GML etc. will remain unchanged.
The dct:Dataset instances need to link to the distribution of the file and need to provide the type with a given URI.

**Comment by paulc-dstl** [comment]
This is a nice pattern. 

There appears to be a relationship with the [FOG Ontology](https://github.com/mathib/fog-ontology), which also comes out of the Linked Building community. The approach described above looks to be more widely applicable, using a Dublin Core element to specify the type rather than a subproperty, as FOG uses. The maintainer of FOG is @mathib who may be able to comment...?

**Comment by situx** [comment]
I adapted this example from geodcat actually. And yes by all means @mathib feel free to share your opinion. It was the linked building community proposing this idea in the first place

**Comment by nicholascar** [comment]
I propose to use `geo:hasSerilization` directly, like this:

```
ex:mygeom 
    a geo:Geometry ;
    geo:hasSerialization [
        a dcat:Distribution ;
        dcat:accessURL "http://hereismyfile.net/myfile.x3d"^^xsd:anyURI .
        dcterms:conformsTo "https://uri4uri.is4.site/mime.html/model/x3d+xml"^^xsd:anyURI ;
    ] ;
.    
```

So the Geometry indicates its serialization which is then defined by the `Distribution`.

No need for yet another generic `hasSeralization property` - use existing and the basic qualified node pattern here allows for additional predicates for `conformsTo`, etc.

**Comment by situx** [comment]
Makes sense to me. Then we could propose to add that to the standard
