### ISSUE TITLE
GeoSPARQL source code for functions and rules is missing 

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#56]
The GeoSPARQL semantic code consists of three sets of definitions: the core ontology, the functions vocabulary and the RIF rules. These correspond with the following name spaces:
geo: http://www.opengis.net/ont/geosparql#
geof: http://www.opengis.net/def/function/geosparql/
geor: http://www.opengis.net/def/rule/geosparql/

We will want to keep the three files mutually consistent, and there are change requests for GeoSPARQL functions. So I suggest adding the functions and rules files to [this repository](https://github.com/opengeospatial/ogc-geosparql/tree/master/1.1).

A code file for the functions is mentioned in the OGC definition server: http://defs-dev.opengis.net/static/definitions/conceptschemes/functions_geosparql.ttl. I could not find a source file for the RIF rules, but it must exist somewhere.

**Comment by FransKnibbe** [comment]
The functions file has been found: [http://defs-dev.opengis.net/static/definitions/conceptschemes/functions_geosparql.ttl
](http://defs-dev.opengis.net/static/definitions/conceptschemes/functions_geosparql.ttl)

**Comment by jabhay** [comment]
Rules here perhaps: http://defs.opengis.net/elda-common/ogc-def/resource?uri=http://www.opengis.net/def/rule/geosparql/&_format=html

**Comment by dr-shorthair** [comment]
@rob-metalinkage or @ghobona might be able to advise on status and point-of-truth for these

**Comment by nicholascar** [comment]
@dr-shorthair we have copies of the resources and links to their existing RDF locations in a profile declaration for GeoSPARQL 1.0 that is currently a PR: #58 (see profile.ttl: https://github.com/opengeospatial/ogc-geosparql/pull/58/files#diff-8b9fe01200dc518bf97ace4e2a27c8665a486c8b1000f9d2054257b01ec804fc)

**Comment by ghobona** [comment]
The ontology approved with GeoSPARQL 1.0 is at http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf

The functions are listed in there.

**Comment by jabhay** [comment]
Hi @FransKnibbe , could you please review the pull request that I've tagged you in as it should address this issue. Any further questions, please raise comments in the pull request.

**Comment by nicholascar** [comment]
All GeoSPARQL 1.0 and 1.1 resources are listed in this repository at:

* https://github.com/opengeospatial/ogc-geosparql/tree/master/1.0
* https://github.com/opengeospatial/ogc-geosparql/tree/master/1.1

These will all be allocated long-term stable URIs by the OGC Naming Authority when the 1.1 version is released.
