### ISSUE TITLE
Add properties for spatial size

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#6]
Length, area, volume - e.g. see from GEOX

- [hasLength](https://raw.githack.com/CSIRO-enviro-informatics/geosparql-ext-ont/master/geox.html#haslength)
- [hasArea](https://raw.githack.com/CSIRO-enviro-informatics/geosparql-ext-ont/master/geox.html#hasarea)
- [hasVolume](https://raw.githack.com/CSIRO-enviro-informatics/geosparql-ext-ont/master/geox.html#hasvolume) 

Detail from opengeospatial/geosemantics-dwg#73

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Must)](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Should)](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Could)](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Won%27t)](https://api.gh-polls.com/poll/01EJXBH7XM5NRJ4CH45HVR0TEW/Won%27t/vote)

**Comment by nicholascar** [comment]
@dr-shorthair can you confirm this Issue can be closed now that the GeoX PR is merged?

**Comment by dr-shorthair** [comment]
Link to the corresponding PR please?

**Comment by nicholascar** [comment]
Better than a link to the PR, see that these properties are now in the Ont:

* <https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl#L192>
* <https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl#L200>
* * <https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl#L215>
