### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#60]
This issue [was reported in the OGC standards tracker](http://ogc.standardstracker.org/show_request.cgi?id=668). 

When the current GeoSPARQL ontology is [run through DBpedia Archivo](https://archivo.dbpedia.org/info?o=http://www.opengis.net/ont/geosparql), two missing things arise: a lack of a license and non-conformity with LODE. This issue about the missing license (see [issue 63](63) about LODE-conformance).

In general, the purpose of a license is to clarify what people are allowed to do with an ontology. A missing license could lead to either misuse of the ontology, or hesitance in putting the ontology to use.
See also [these remarks on licensing by the Spatial Data on the Web Working Group](https://www.w3.org/2015/spatial/wiki/Ontology_rights_and_licence).

I would like to ask for first discovering an appropriate license for the GeoSPARQL ontology and then adding it to the ontology.

**Comment by nicholascar** [comment]
@rob-metalinkage @gbuehler is there a persistent URI for the OGC license that I can use in a license property for the GeoSPARQL ontology, profile and each vocab? I see the license text (e.g. https://github.com/opengeospatial/ogc-geosparql/blob/master/LICENSE) but unlike GPL & CC licenses, perhaps this isn't registered anywhere??

**Comment by jabhay** [comment]
- [ ] @nicholascar to model OGC license in ODRL
- [ ] @jabhay to reach out to @ogcscotts to get some direction on making a semantically friendly version of the OGC license available in the Madrid Polytechnic University (ODI Europe) RDF Licenses Dataset, to be referenced in the GeoSPARQL ontology.

**Comment by nicholascar** [comment]
@nicholascar please follow up with modelling of the OGC licenses in ODRL for potential publication via OGC NA.

**Comment by nicholascar** [comment]
> an explicit license statement could also be added as a fix to version 1.0

Not really sure about this. We have added new resources to the total set of GeoSPARQL 1.0 resource but a license addition would seek to alter the licensing of something that's been published for ~9 years. I don't know if that's possible.

I'll ask OGC legal.

**Comment by jabhay** [comment]
It would appear that the OGC is currently working on a Persistent URI for document licenses. They expect the link to be available soon. There may be value in using the GitHub link for the time being, and replacing it with the final URI after it becomes available. Thoughts?

**Comment by jabhay** [comment]
I'll take this on. What's required is:

- [ ] @jabhay to chat with @ogcscotts to determine whether OGC would be open to The GeoSPARQL SWG providing a semantic version of the license for publication via content negotiation, using the license URL above. We'll work out what checks and balances are required.
- [ ] @nicholascar to build the version of the license.
- [ ] @jabhay and @nicholascar to organise publication.

**Comment by ogcscotts** [comment]
@jabhay I strongly support a semantic version of the license per the OGC-NA issue.

**Comment by nicholascar** [comment]
> I strongly support a semantic version of the license per the OGC-NA issue

Great, OK, I will try and generate a first version in the next couple of days!

**Comment by nicholascar** [comment]
Here is a first version:

```turtle
@prefix cc: <http://creativecommons.org/ns#> .
@prefix ogc: <https://www.ogc.org/def/licenses/ogc/> .
@prefix odrl: <http://www.w3.org/ns/odrl/2/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://www.ogc.org/def/licenses/ogc>
    a odrl:Policy , cc:License , skos:Concept ;
    rdfs:label "OGC License Agreement" ;
    rdfs:comment "The standard OGC License"@en ;
    rdfs:seeAlso "https://www.ogc.org/license"^^xsd:anyURI ;
    cc:legalcode """Permission is hereby granted ... remedies available to it."""@en ;
    odrl:permission [
        odrl:action 
            odrl:use ,    
            odrl:copy , 
            odrl:modify ,
            odrl:distribute ;
        odrl:duty [
            odrl:action 
                odrl:attribute , 
                odrl:attachPolicy ,
                ogc:attachNoticeOfUnapprovedChanges ;
        ] ;
    ] ;
    odrl:prohibition [ 
        odrl:action
            ogc:licensorNameUseForPromotionRequiresPermission ;
    ] ;
.

ogc:attachNoticeOfUnapprovedChanges
	a odrl:Action, skos:Concept ;
	rdfs:label "Attach notice of unnaproved changes"@en ;
	skos:definition "The act of adding a notice to the asset stating that changed made to the source asset have not been approved or adopted by licensor."@en ;
	skos:closeMatch cc:Notice ;
.

ogc:licensorNameUseForPromotionRequiresPermission
    a odrl:Action , skos:Concept ;
	rdfs:label "Attach notice of unnaproved changes"@en ;
	skos:definition "The name of licensor shall not be used in promotions, without prior written authorization of LICENSOR."@en ;
.    
```
The IRI proposed for the license is `https://www.ogc.org/def/licenses/ogc` which is clearly an item within a Licenses vocabulary. The OGC may use this to host further licenses in time.

There are two actions - a Duty and a Prohibition - that I couldn't characterise using the standard ODRL2 Actions, so I have made custom Actions for them. They will need to be hosted by the OGC, probably just as additional terms in the Licenses vocabulary.

@riannella: could you or another ODRL editor please review? The legal code used is online at https://www.ogc.org/license

**Comment by ghobona** [comment]
The IRI base would have to change to `http://www.opengis.net/def` to comply with [OGC-NA policy](https://docs.opengeospatial.org/pol/09-048r5.html#_naming_rule).

**Comment by nicholascar** [comment]
> The IRI base would have to change to `http://www.opengis.net/def` to comply with OGC-NA policy.

Ooops, silly me, I've updated the RDF above to be compliant

**Comment by riannella** [comment]
A few points:
1 - ODRL Model recommends us of DC elements for policy metadata
2 - odrl:use is the parent to odrl:modify and odrl:distribute (ie will include these actions and a lot more...)
  https://www.w3.org/TR/odrl-vocab/#term-use
3 - odrl:copy is deprecated, use odrl:reproduce
4 - cc:legalCode is defined as "the **URL** of the legal text of a license"
5 - The rdfs:label for ogc:licensorNameUseForPromotionRequiresPermission needs to be updated and the skos:definition needs to be a _positive_ action statement (as it will be prohibited). Perhaps rename is as "publiciseLicensor"?

**Comment by nicholascar** [comment]
Thanks @riannella! Based on your feedback, below is an updated version. I found it easy to address all 4 of your points though:

* I still want to be able to indicate the full Legal Code of the (English version of) the license, so if I shouldn't use `cc:legalCode` for this, what should I use? Or we just live with the hyperlink to the online location that contains that text...
* I've shortened the prohibition to `ogc:promotionWithLicensorName` while doing as you say and making it a positive action.
* I've adopted all your modelling pointers regarding deprecated terms etc.

```turtle
@prefix cc: <http://creativecommons.org/ns#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix ogc: <http://www.opengis.net/def/licenses/ogc/> .
@prefix odrl: <http://www.w3.org/ns/odrl/2/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://www.opengis.net/def/licenses/ogc>
    a odrl:Policy , cc:License , skos:Concept ;
    dcterms:title "OGC License Agreement" ;
    dcterms:description "The standard OGC License"@en ;
    rdfs:seeAlso "https://www.ogc.org/license"^^xsd:anyURI ;
    cc:legalcode "https://www.ogc.org/license"^^xsd:anyURI ;
    skos:definition """Permission is hereby granted ... remedies available to it."""@en ;
    odrl:permission [
        odrl:action 
            odrl:use ,    
            odrl:reproduce ;
        odrl:duty [
            odrl:action 
                odrl:attribute , 
                odrl:attachPolicy ,
                ogc:attachNoticeOfUnapprovedChanges ;
        ] ;
    ] ;
    odrl:prohibition [ 
        odrl:action
            ogc:licensorNameUseForPromotionRequiresPermission ;
    ] ;
.

ogc:attachNoticeOfUnapprovedChanges
	a odrl:Action, skos:Concept ;
	skos:prefLabel "Attach notice of unapproved changes"@en ;
	skos:definition "The act of adding a notice to the asset stating that changed made to the source asset have not been approved or adopted by licensor."@en ;
	skos:closeMatch cc:Notice ;
.

ogc:promotionWithLicensorName
    a odrl:Action , skos:Concept ;
	skos:prefLabel "Promotion With Licensor Name"@en ;
	skos:definition "The name of licensor is used in promotions, without prior written authorization of LICENSOR."@en ;
.    
```

**Comment by riannella** [comment]
Use a skos:scopeNote for the full text of the license?

**Comment by nicholascar** [comment]
> Use a skos:scopeNote for the full text of the license?

An interesting choice, has this been done previously? I've used `skos:definition` above because that legal text, for the moment until machine-redable takes over the world (!) is generally thought to define the license. Do you suggest I change?

**Comment by riannella** [comment]
Maybe `dc:description` is more relevant. (I am not sure what others do)
(Is a license a **concept**?)

**Comment by nicholascar** [comment]
> Is a license a concept

Yes, anything can be a Concept! `skos:definition` _defines_ things, where as `dcterms:description` just _describes_ them. I think the legal text does _define_ the license (in English, not in RDF), just as class definitions or Concept definitions define _them_.

**Comment by vroddon** [comment]
I must confess I had also used cc:legalcode for the whole text (see URI below), which is anyway an old, not up-to-date translation.
https://github.com/w3c/odrl/blob/master/bp/license/rdflicense/OGCDocument1.0.ttl

**Comment by nicholascar** [comment]
OK, my modelling above is essentially inline with @vroddon's but a bit more specialised. Also, I don't see the specific instruction to Share Alike, which is a Duty that @vroddon indicated for the OGC Software & OGC Document license.

Final question for @ghobona:

* I used the license at https://www.ogc.org/license
* @vroddon used the licenses at:
    * https://www.ogc.org/ogc/document
    * https://www.ogc.org/ogc/software/1.0

1. Is there an order of precedence among these?
2. Which should be used in the case of GeoSPARQL which is a collection of document & data artifacts in an online repo?

If you can answer these, I think the license above, or @vroddon's versions, can be selected for use for GeoSPARQL 1.1 and references to them will be updated.

**Comment by ogcscotts** [comment]
@nicholascar @ghobona OGC is in the midst of an update of all of our Intellectual Property Rights documentation. We have completed the policy and will soon start work on the notices. I recommend that for now, we reference https://www.ogc.org/license for any Standard document, regardless of whether its content is in a traditional HTML file or in an ontology. Ultimately, I believe that we need to merge the document notice and license and we can consider the license URI to be persistent.
