### ISSUE TITLE
URIs of requirements and conformance tests can not be dereferenced

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#61]
In section 2 (Conformance) of the GeoSPARQL specification it says: "Requirements and conformance test URIs defined in this document are relative to http://www.opengis.net/spec/geosparql/1.0/."

This leads to URIs like http://www.opengis.net/spec/geosparql/1.0/conf/rdfs-entailment-extension/wkt-geometry-types, which can not be resolved. 

Were these URIs ever dereferenceable? Is it a problem they are not?

**Comment by nicholascar** [comment]
We need to automate the testing of this: check every link in the Spec doc and also in the other profile documents (ontology, vocabularies).

I will list all URIs from the 1.0/1.1 Profile for this purpose

**Comment by FransKnibbe** [comment]
As an experiment, I ran the 1.0 ontology (http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf) through the W3C RDF validator (https://www.w3.org/RDF/Validator/). The results page has a URI that then can be used with the W3C Link Checker (https://validator.w3.org/checklink). Three broken links were found, one generated by the RDF Validator, two of them from the GeoSPARQL ontology. 

The W3C link checker can be used if the specification document is in HTML format. That should be possible to obtain from the current adocs. But the 1.0 specification document contains relative URIs that probably will be hard to check. Perhaps it is better not to have relative URIs in the 1.1 version of the specification.

**Comment by jabhay** [comment]
Resolved by #163
