### ISSUE TITLE
Which conventions to use for ontology annotation and metadata?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#63]
Having a well annotated ontology with a good amount of metadata can help users a lot. That in itself is a good reason to have plenty of clarifications in the ontology. Next to that there are several tools for automatically generating documentation or diagrams  from raw ontology data, and there are services that crawl and index ontologies in order to improve discoverability. These external tools each hope to find certain data in ontologies, based on established conventions. For example there is [LODE](https://essepuntato.it/lode/) (see also: [pyLODE](https://github.com/RDFLib/pyLODE)) and [LOV](https://lov.linkeddata.es/dataset/lov). Can we agree on a set of conventions for the GeoSPARQL ontology (or ontologies)?
The easy way would be to just adopt a set of conventions that is already described somewhere. Maybe [this recent publication](http://dgarijo.com/papers/best_practices2020.pdf) is the way to go?

**Comment by dr-shorthair** [comment]
Yes. I would also recommend including `skos:example` as much as possible. I have used that for inline documentation e.g. https://raw.githack.com/AGLDWG/asgs-ont/master/asgs.html#MeshBlock

**Comment by FransKnibbe** [comment]
It is nice to have examples in the ontology. Would it be smart to use `skos:example` with URIs containing fragment identifiers that point at examples in the HTML documentation?

**Comment by mathib** [comment]
`skos:example` can be used for pointing to both RDF literals, URIs and blank nodes: https://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#secadvanceddocumentation

According to the [SKOS ontology](http://www.w3.org/2004/02/skos/core#), it's defined as an `owl:AnnotationProperty` without `rdfs:range`, leaving all options open.

> It is nice to have examples in the ontology. Would it be smart to use skos:example with URIs containing fragment identifiers that point at examples in the HTML documentation?

So it's possible to add examples as `xsd:string` literals (e.g. set of triples) or to reference external documentation (1) via an URI (with fragment identifier it still remains a valid URI) or (2) as `xsd:anyURI` literals. I believe the latter is most suited when the URI refers to documentation in plain HTML (no content negotation or embedded RDF). However, if we need to add metadata related to the content of the example, a regular URI as a graph node would be better

**Comment by dr-shorthair** [comment]
We have adopted a pattern of including RDF fragments (in TTL) as _literals_. 
That allows documentation to be generated easily using pyLODE - e.g. see http://linked.data.gov.au/def/placenames (conneg for HTML of TTL) - to build the kind of documentation that might help a developer.

**Comment by mathib** [comment]
Aha, I misunderstood Frans' comment. He was wondering if it makes sense to refer from the RDF back to the HTML that describes the RDF, right? I would follow the approach followed by Simon, to keep the example triples closer to the source. The only 'downside' is that it might clutter the Turtle view as I find it difficult to separate the literal containing the Turtle from the actual ontology in Turtle while reading it as a human without additional tooling.

**Comment by FransKnibbe** [comment]
Yes, I think there is something to say for referring from the RDF in the ontology back to the HTML that describes the ontology term:

- It allows follow-your-nose access to explanations
- It automatically gives consistency between ontology and documentation

Using the documentation HTML as the source of examples has some benefits:
- It will make documentation easier to maintain (no changes to the ontology are required if documentation is  improved)
- It allows more freedom in examples. They don't have to be valid RDF in that case. 
- It could result in more elaborate descriptions being available when a consumer uses the ontology as an access point.
- As @mathib mentioned, there is less clutter in the ontology.

Perhaps some kind of automation instead of the pyLODE scheme could be adopted, e.g. always have `#<ontology term>_Example` as the fragment identifier?

**Comment by nicholascar** [comment]
Closing since this has been _Done_ for ages.
