### ISSUE TITLE
VOTE: Nicholas Car to represent the SWG at the OGC Naming Authority

### ISSUE THREAD

**Issue by jabhay** [opengeospatial/ogc-geosparql#66]
On 10/12/20 10:34, Joseph Abhayaratna wrote:

Hi All,
 
We've had just the one nomination, Nicholas Car (Surround Australia). We did not achieve quorum at our last meeting. I took an action to send out an email vote, so...
 
I'd like to propose an email vote on the following motion: 
 
That Nicholas Car be elected as the GeoSPARQL SWG's representative to the OGC Naming Authority.
 
Via reply all, could I ask for a second? 
 
And can members please indicate (by reply all) any or no objections to unanimous consent.
 
This vote will close in 2 weeks from the sending of this message.
 
Thanks in advance.
 
Cheers,
Jo

**Comment by jabhay** [comment]
From: Nicholas Car <nicholas.car@surroundaustralia.com> 
Sent: 10 December 2020 11:05
To: Joseph Abhayaratna <joseph.abhayaratna@geoscape.com.au>
Cc: geosparql.swg@lists.opengeospatial.org; Simon.Cox@csiro.au; Cripps Paul J <pcripps@dstl.gov.uk>; reh@bgs.ac.uk; Timo Homburg <timo.homburg@gmx.de>; Krzysztof Janowicz <janowicz@ucsb.edu>; Frans Knibbe <fjknibbe@gmail.com>; Dimitris Kotzinos <kotzino@gmail.com>; Little, Chris <chris.little@metoffice.gov.uk>; Christine Perey <cperey@perey.com>; Matthew Perry <matthew.perry@oracle.com>; Panagiotis (Peter) A. Vretanos <pvretano@cubewerx.com>; g.wiersma@geonovum.nl
Subject: Re: Invitation for nominations for representatives to the OGC Naming Authority
 
No objections from me, of course.
 
Nick

**Comment by jabhay** [comment]
From: Cripps Paul J <pcripps@mail.dstl.gov.uk>
Thu 10/12/2020 10:35 PM
To: Nicholas Car <nicholas.car@surroundaustralia.com>; Joseph Abhayaratna
Cc: geosparql.swg@lists.opengeospatial.org; Simon.Cox@csiro.au; reh@bgs.ac.uk+9 others
Classification: UK OFFICIAL


Hi Jo,
I second that. No objections here.
All best,
Paul.

**Comment by jabhay** [comment]
From: Frans Knibbe <fjknibbe@gmail.com>
Thu 10/12/2020 10:10 PM
To: Joseph Abhayaratna
Cc: geosparql.swg@lists.opengeospatial.org+12 others
Hi Jo,

No objections here!

Greetings,
Frans

**Comment by jabhay** [comment]
From: Panagiotis (Peter) A. Vretanos <pvretano@cubewerx.com>
Date: Wednesday, 16 December 2020 at 10:06 am
To: Joseph Abhayaratna <joseph.abhayaratna@geoscape.com.au>, geosparql.swg@lists.opengeospatial.org <geosparql.swg@lists.opengeospatial.org>, Nicholas Car <nicholas.car@surroundaustralia.com>, Simon.Cox@csiro.au <Simon.Cox@csiro.au>, Cripps Paul J <pcripps@mail.dstl.gov.uk>, reh@bgs.ac.uk <reh@bgs.ac.uk>, Timo Homburg <timo.homburg@gmx.de>, Krzysztof Janowicz <janowicz@ucsb.edu>, Frans Knibbe <fjknibbe@gmail.com>, Dimitris Kotzinos <kotzino@gmail.com>, Little, Chris <chris.little@metoffice.gov.uk>, Christine Perey <cperey@perey.com>, Matthew Perry <matthew.perry@oracle.com>, g.wiersma@geonovum.nl <g.wiersma@geonovum.nl>
Subject: Re: Invitation for nominations for representatives to the OGC Naming Authority

Jo,
No objection to unanimous consent.
Ciao.

**Comment by pvretano** [comment]
No objection from me.

**Comment by situx** [comment]
No objection from me

**Comment by kjano** [comment]
No objection from me

**Comment by jabhay** [comment]
Matthew Perry <matthew.perry@oracle.com>
Fri 11/12/2020 3:50 AM

To: janowicz@ucsb.edu; Dimitris Kotzinos <kotzino@gmail.com>; Joseph Abhayaratna+11 others
No objections from me.

- Matt

**Comment by jabhay** [comment]
From: Dimitris Kotzinos 
Thu 10/12/2020 11:04 PM
Hi all,

happy to second the motion!
And of course vote in favor.

Best regards,
Dimitris

**Comment by jabhay** [comment]
From: Krzysztof Janowicz 
Fri 11/12/2020 2:55 AM
On 12/10/20 4:04 AM, Dimitris Kotzinos wrote:
> Hi all,
>
> happy to second the motion!
> And of course vote in favor.


Same here.

**Comment by jabhay** [comment]
From: Heaven, Rachel E. <reh@bgs.ac.uk>
Sent: Thursday, 24 December 2020 9:10 AM
To: Joseph Abhayaratna ; Cripps Paul J ; Nicholas Car 
Cc: geosparql.swg@lists.opengeospatial.org <geosparql.swg@lists.opengeospatial.org>; Simon Cox; Timo Homburg ; Krzysztof Janowicz ; Frans Knibbe ; Dimitris Kotzinos ; Little, Chris ; Christine Perey ; Matthew Perry ; Panagiotis (Peter) A. Vretanos ; g wiersma
Subject: RE: [UK OFFICIAL] RE: Invitation for nominations for representatives to the OGC Naming Authority
 
Hi all,

No objections to unanimous consent

Best wishes,

Rachel

**Comment by jabhay** [comment]
Result: Quorum achieved 10/15 members voted, motion unanimously passed.
