### ISSUE TITLE
Support KML literals in GeoSPARQL

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#69]
As per the note in GeoSPARQL 1.0 Sec. 12:

> ...Obvious extensions are to define new conformance classes for other standard serializations of geometry data (e.g. KML, GeoJSON). ...

We should add support for KML literals for completeness. Given the added support for GeoJSON, this should be an extremely simple task.

A small review of the status of KML should be conducted and used to justify/exclude this task.

**Comment by situx** [comment]
I have implemented KML literals before. I think it should be straightforward to do. 
It would need the same restriction as GeoJSON that only WGS84 is a valid CRS.
Apart from that, I see no reasons to not include it. In fact, I think as an OGC standard I would find it logical to support at least all standards defined by the OGC as literals.

**Comment by nicholascar** [comment]
> I would find it logical to support at least all standards defined by the OGC as literals.

Yes, we should! Happy for you to put this through- I have a lot of other GeoSPARQL things on...

**Comment by situx** [comment]
Since I had some time just now, I made a draft in #75 
We can discuss whether or not to include it in the next meeting.

**Comment by situx** [comment]
Closing this issue as the corresponding pull request #75  has been accepted and closed
