### ISSUE TITLE
unnecessary OWL Import statement

### ISSUE THREAD

**Issue by DougalW** [opengeospatial/ogc-geosparql#77]
Hi, I opened geosparql in Protege and it sometimes fails to load because of this import statement:

<owl:imports rdf:resource="http://purl.org/dc/elements/1.1/"/>

I think this is unnecessary, as you have already defined that you are using the Dublin Core namespace upfront, so don't need to import this.

**Comment by dr-shorthair** [comment]
Imports generally do not be retained in the distributed ontology (RDF file) - though they are helpful during the design phase.

**Comment by nicholascar** [comment]
The imports statement has been removed from GeoSPARQL 1.1, see https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl, so I'm closing this issue as dealt with.

**Comment by DougalW** [comment]
Tested and loads fine now. Thanks.
