### ISSUE TITLE
Datatype or class for 'spatial measure'

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#83]
Continuing discussion on Spatial Measure from #72

**Comment by dr-shorthair** [comment]
The [tail end of the discussion in #72](https://github.com/opengeospatial/ogc-geosparql/pull/72#issuecomment-780840823) is: 

>> @kjano I mean length/area/volume provides a single (scaled) number to describe an aspect of a spatial thing. Components of a coordinate are single (scaled/offset) numbers that describe other aspects. Sometimes a single measure is useful for some application, but none of these is 'complete' without a whole lot of other numbers. Maybe the analogy is a bit tortured. But my point is that a single coordinate-component is not a 'spatial thing' and a measure of its 1D/2D/3D extent is not usefully 'spatial' in my opinion. It is just a measure. Measures only become 'spatial' when combined with other measures, and embedded in some N-dimensional space.

> @dr-shorthair, @nicholascar I am looking at this again and still agree (and like) the idea of expressing areas, length, and so on as results of observations. This is great because it gives us a nice framework to also model how we arrived at these values and so on. The same can be said about geometries. I also understand why we would want to name these spatial measures. What I hope could be discussed in more detail is how this relates to observations. If observations (in O&M and SSN/SOSA) are events, would spatial measures also be events or would they be the results of observations? In both cases, it would be unclear why SpatialMeasure would be a subclass of SpatialObject.

**Comment by dr-shorthair** [comment]
The goal of these predicates is to provide a compact home for indicating the size of a spatial object. For example
```
my:Garden a geo:Feature ;
    geo:hasGeometry my:GardensGeometry ;
    geo:hasArea "55 m2"^^some:ScaledQuantity ;
.
```
The challenge is in how to represent the value. In the example here I used a form suggested by Maxime's group, as a formatted literal with the UCUM code embedded. Alternatively, the value of `geo:hasArea` could be an object, with the amount and scale separated, like 
```
my:Garden a geo:Feature ;
    geo:hasGeometry my:GardensGeometry ;
    geo:hasArea [ a geo:SpatialMeasure ;
        geo:amount 55.0 ;
        geo:unit <http://qudt.org/vocabulary/unit/M2> ;
    ] ;
.
```
This latter formulation also allows for additional information which might qualify the value, such as the CRS within which it was computed. Not sure how often that will matter though.

**Comment by situx** [comment]
Just my 2 cents...
I believe @kjano might be referring to sth. Like this https://github.com/HajoRijgersberg/OM/blob/master/Weather-example.md
So we could connect the SpatialMeasure to some concepts of the aforementioned ontology.

**Comment by nicholascar** [comment]
@dr-shorthair can this be closed now after the GeoX PR merge?

**Comment by dr-shorthair** [comment]
No - I don't think discussion is complete or consensus reached.

**Comment by nicholascar** [comment]
Can you make a suggestion on the ont as it now stands? We have the SpatialMeasure class in there without the subclassing of SpatialObject: <https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/geo.ttl#L511>

**Comment by kjano** [comment]
@nicholascar, yes, thanks for that. As written before SpatialMeasure should not be a subclass of SpatialObject. Thanks again. @dr-shorthair, in your example SpatialMeasure is more of a 'result' than an 'event', would you agree? Is this where we should be taking this and how would this relate to our and other work on observations?

**Comment by dr-shorthair** [comment]
Yes, the SpatialMeasure is a result, not an event.

**Comment by nicholascar** [comment]
We have removed any class for spatial meansrements from GeoSPARQL and use `hasXXX` and `hasMetrixXXX` pair properties for area, length etc.
